package org.apache.jsp.WEB_002dINF.jsps.solutions.leasing.cust_005finfo.cust_005fcompany;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kernal.utils.FileUtil;
import com.kernal.utils.WebUtil;

public final class cust_005fcompany_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.List<java.lang.String> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList<java.lang.String>(1);
    _jspx_dependants.add("/WEB-INF/tlds/permission.tld");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fpermission_005faction_0026_005fcode;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.List<java.lang.String> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fpermission_005faction_0026_005fcode = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    if (_005fjspx_005ftagPool_005fpermission_005faction_0026_005fcode != null) _005fjspx_005ftagPool_005fpermission_005faction_0026_005fcode.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>法人客户 - 法人客户</title>\r\n");
      out.write("    <!--css sheet-->\r\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/dtree/dtree.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/jquery-easyui/easyui.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/jquery-easyui/icon.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/tracywindy/tracywindy.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/tracywindy/button.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/tracywindy/workFlowUtil.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t<!--javascript libray-->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/workFlowUtil.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyUtils.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyJsonUtil.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyAjax.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery/jquery.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery/jquery.easyui.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyLoadMask.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyTable.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyComboBox.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyComboBoxCust.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindySerializeFormToJsonObject.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/my97DatePicker/WdatePicker.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/validator.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyOperationTable.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/MustFillIn.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/custType.js\"></script>\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t   html,body{\r\n");
      out.write("\t     overflow:hidden;\r\n");
      out.write("\t   }\r\n");
      out.write("\t   td.td-content{\r\n");
      out.write("\t     text-align:left;\r\n");
      out.write("\t   }\r\n");
      out.write("\t   td.td-content input{\r\n");
      out.write("\t      width:165px;\r\n");
      out.write("\t      float:left;\r\n");
      out.write("\t      border:1px solid #DDD;\r\n");
      out.write("\t   }\r\n");
      out.write("\t   td.td-content textarea{\r\n");
      out.write("\t      width:90%;\r\n");
      out.write("\t      overflow:auto;\r\n");
      out.write("\t      float:left;\r\n");
      out.write("\t      border:1px solid #DDD;\r\n");
      out.write("\t   }\r\n");
      out.write("\t</style>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tvar currentLoginUserId = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope['login_userid']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("\t\tvar isAdmin=false;\r\n");
      out.write("\t\tvar operButtons='';\r\n");
      out.write("\t\tvar deptname='';\r\n");
      out.write("\t\tif(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope['loginUserDeptObj'].name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"=='子公司项目部'){\r\n");
      out.write("\t\t\tdeptname=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope['loginUserDeptObj'].name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script >\r\n");
      if (_jspx_meth_permission_005faction_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_permission_005faction_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar constantFlagTable = \"User\";\r\n");
      out.write("\tvar pageWidth  = document.documentElement.clientWidth-2;\r\n");
      out.write("\tvar pageHeight = document.documentElement.clientHeight-2;\r\n");
      out.write("\tjQuery(function(){\r\n");
      out.write("\t\t//构建页面中的combox\r\n");
      out.write("\t\t//客户类别\r\n");
      out.write("\t\tvar custtype = new tracywindyComboBoxCust({\r\n");
      out.write("\t\t\t\tlazyLoad:true,\r\n");
      out.write("\t\t       id:'id_combo_custtypename',\r\n");
      out.write("\t\t       renderTo:'custtype',\r\n");
      out.write("\t\t       xmlFileName:'\\\\combos\\\\comboDict.xml',\r\n");
      out.write("\t\t       loadMode:'ajax',\r\n");
      out.write("\t\t       readOnly:true,\r\n");
      out.write("\t\t\t   isContainEmpty:false,\r\n");
      out.write("\t\t\t   otherAttributes:'label=\"客户类别\"',\r\n");
      out.write("\t\t       name:'custtype',\r\n");
      out.write("\t\t       width:510,\r\n");
      out.write("\t\t       displayField:'name',\r\n");
      out.write("\t\t       valueField:'code',\r\n");
      out.write("\t\t       leftAdd:0,\r\n");
      out.write("\t\t       loadComplete:changeCustType,\r\n");
      out.write("\t\t       value:'cust_type.cust',\r\n");
      out.write("\t\t       isCheck:true,\r\n");
      out.write("\t\t       params:{\r\n");
      out.write("\t\t          pid:'cust_type'\r\n");
      out.write("\t\t       },\r\n");
      out.write("\t\t\t   onSelect:changeCustType\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t    //2013-11-29 15:08 修改人 陈兴  原因：银行登记验证 提示信息为空\r\n");
      out.write("\t\tdictOnSelect('id_is_banklevel','banklevel','credit_rating',null,null,'label=\"银行信用等级\"',true,165,true,null); //银行信用等级\r\n");
      out.write("\t\tdictOnSelect('custkindname','custkind','cust_kind',null,null,'label=\"客户内部行业\"');//客户内部行业\r\n");
      out.write("\t\tcommonSelectOverall('industryname',\"(select id,name from t_industry where pid is null) rs\",'id',\"name\",'industry','','','label=\"客户所属行业门类\"',function(combo,data){choseNext(combo,'id_combo_industrylevelbigname','t_industry');},true);//客户所属行业门类\r\n");
      out.write("\t\tcommonSelectOverall('industrylevelbigname',\"(select id,name from t_industry where 1=2) rs\",'id',\"name\",'industrylevelbig','','','label=\"客户所属行业大类\"',function(combo,data){choseNext(combo,'id_combo_industrylevelmiddlename','t_industry');},true);//客户所属行业大类\r\n");
      out.write("\t\tcommonSelectOverall('industrylevelmiddlename',\"(select id,name from t_industry where 1=2) rs\",'id',\"name\",'industrylevelmiddle','','','label=\"客户所属行业中类\"',function(combo,data){choseNext(combo,'id_combo_industrylevelsmallname','t_industry');},true);//客户所属行业中类\r\n");
      out.write("\t\tcommonSelectOverall('industrylevelsmallname',\"(select id,name from t_industry where 1=2) rs\",'id',\"name\",'industrylevelsmall','','','label=\"客户所属行业小类\"',null,true);//客户所属行业小类\r\n");
      out.write("\t\tcommonSelectOverall('provincename',\"(select id,name from t_district where pid in('HB','DB','HD','HZ','XN','XB','HN','TQ')) rs\",'id',\"name\",'province','','','require=\"true\"  label=\"省份\"', function(combo,data){ choseNext(combo,'id_combo_cityname','t_district');},true);//省份\r\n");
      out.write("\t\tcommonSelectOverall('cityname',\"(select id,name from t_district where 1=2) rs\",'id',\"name\",'city','','','require=\"true\"  label=\"城市\"', function(combo,data){ choseNext(combo,'id_combo_countyname','t_district');},true);//城市\r\n");
      out.write("\t\tcommonSelectOverall('countyname',\"(select id,name from t_district where 1=2) rs\",'id',\"name\",'county','','','require=\"true\"  label=\"区县\"',null,true);//地区\r\n");
      out.write("\t\tdictOnSelect('ownershipname','ownership','ownership',null,null,'label=\"企业性质\"');//企业性质\r\n");
      out.write("\t\tdictOnSelect('custscalename','custscale','cust_scale',null,null,'label=\"客户规模\"');//客户规模\r\n");
      out.write("\t\tdictOnSelect('taxlevelname','taxlevel','tax_level_name',null,null,'label=\"纳税人类别\"');//纳税人\r\n");
      out.write("\t\tdictYesOrNoByCode('iscompanymanagename','iscompanymanage',null,null,true,'label=\"是否已办企业管理\"');//是否已办企业管理\r\n");
      out.write("\t\tdictYesOrNoByCode('draftname','draft',null,null,null,'label=\"是否草稿\"');//是否草稿\r\n");
      out.write("\t\tdictHadOrNoByCode('valuationfile','valuationfile',null,null,null,'require=\"true\" label=\"有无估价文件\"');//有无估价文件\r\n");
      out.write("\r\n");
      out.write("\t\tnew tracywindyComboBox({\r\n");
      out.write("\t\t\tid : 'id_combo_id_is_dealerorcompany',\r\n");
      out.write("\t\t\twidth : 167,\r\n");
      out.write("\t\t\trenderTo : 'id_is_dealerorcompany',\r\n");
      out.write("\t\t\txmlFileName : '\\\\eleasing\\\\workflow\\\\public\\\\SimpleCustSelect.xml',\r\n");
      out.write("\t\t\tloadMode : 'ajax',\r\n");
      out.write("\t\t\treadOnly : false,\r\n");
      out.write("\t\t\tisAjaxLenovo : true,\r\n");
      out.write("\t\t\totherAttributes:'require=\"true\" label=\"经销商\"',\r\n");
      out.write("\t\t\ttopAdd : 0,\r\n");
      out.write("\t\t\tleftAdd : 0,\r\n");
      out.write("\t\t\tpositionDropIconLeftAdd : -1,\r\n");
      out.write("\t\t\tname : 'dealerorcompany',\r\n");
      out.write("\t\t\tdisplayField : 'name',\r\n");
      out.write("\t\t\tvalueField : 'id',\r\n");
      out.write("\t\t\tvalue:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope['currentDealerCustInfoId']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\",\r\n");
      out.write("\t\t\trawValue:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope['currentDealerCustInfoName']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\",\r\n");
      out.write("\t\t\tparams : {\r\n");
      out.write("\t\t\t\tcust_class:'CUST_INFO_DEALER',\r\n");
      out.write("\t\t\t\tcooperate_status:'dealer_symbiosis1',\r\n");
      out.write("\t\t\t\tdealer_id:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope['currentDealerCustInfoId']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t,onSelect:changeDealerorInfo\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tfunction changeDealerorInfo()\r\n");
      out.write("\t\t{\r\n");
      out.write("\t\t\tif ( getTracywindyObject(\"id_combo_id_is_dealerorcompany\").getValue()!=\"\")\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\tif(window.confirm(\"您是否确认选中的经销商为该经销商下的客户？\"))\r\n");
      out.write("\t\t\t\t{\r\n");
      out.write("\t\t\t\t\tvar custid=$(\"#custid\").val();\r\n");
      out.write("\t\t\t\t\tvar tempStr=getTracywindyObject(\"id_combo_id_is_dealerorcompany\").getValue();//新下拉选中经销商id\r\n");
      out.write("\t\t\t\t\tvar url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/leasing/checkDealerCompayInfo.action\";\r\n");
      out.write("\t\t\t\t\tvar params = {dealerid:tempStr,custid:custid};\r\n");
      out.write("\t\t\t\t\t ajaxRequest({\r\n");
      out.write("\t\t\t\t    \t method:'POST',\r\n");
      out.write("\t\t\t\t         url:url,\r\n");
      out.write("\t\t\t\t         params:params,\r\n");
      out.write("\t\t\t\t         failure:function(res){},\r\n");
      out.write("\t\t\t\t         success:function(res)\r\n");
      out.write("\t\t\t\t         {\r\n");
      out.write("\t\t \t\t\t \t   \t\tres=res.responseText;\r\n");
      out.write("\t\t \t\t\t \t   \t\tres=res.replace(/(^\\s+)|(\\s+$)/g, \"\"); \r\n");
      out.write("\t\t \t\t\t     \t    if(res != '')\r\n");
      out.write("\t\t \t\t\t     \t    {\r\n");
      out.write("\t\t \t\t\t     \t    \tif( res ==\"yes\")\r\n");
      out.write("\t\t\t\t     \t    \t\t{\r\n");
      out.write("\t\t\t\t     \t    \t\t\talert(\"下拉修改完毕后请单击确认!\");\r\n");
      out.write("\t\t\t\t     \t    \t\t}\r\n");
      out.write("\t\t \t\t\t     \t    \telse if(res == \"custidIsNull\")\r\n");
      out.write("\t \t\t\t     \t    \t\t{\r\n");
      out.write("\t \t\t\t     \t    \t\t\t//新增\r\n");
      out.write("\t \t\t\t     \t    \t\t\t//alert(\"新增\");\r\n");
      out.write("\t \t\t\t     \t    \t\t}\r\n");
      out.write("\t\t \t\t\t     \t    \telse{\r\n");
      out.write("\t\t\t\t     \t    \t\t\talert(\"操作失败!\");\r\n");
      out.write("\t\t\t\t     \t    \t\t}\r\n");
      out.write("\t\t \t\t\t     \t    }\r\n");
      out.write("\t\t \t\t\t  }\r\n");
      out.write("\t\t\t\t    });\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tnew tracywindyComboBox({\r\n");
      out.write("\t\t\tid : 'id_combo_creatordeptname',\r\n");
      out.write("\t\t\twidth : 167,\r\n");
      out.write("\t\t\trenderTo : 'creatordeptname',\r\n");
      out.write("\t\t\txmlFileName : '\\\\eleasing\\\\workflow\\\\public\\\\department_combox.xml',\r\n");
      out.write("\t\t\tloadMode : 'ajax',\r\n");
      out.write("\t\t\treadOnly : false,\r\n");
      out.write("\t\t\tisAjaxLenovo : true,\r\n");
      out.write("\t\t\totherAttributes:'require=\"true\" label=\"登记人部门\"',\r\n");
      out.write("\t\t\ttopAdd : 0,\r\n");
      out.write("\t\t\tleftAdd : 0,\r\n");
      out.write("\t\t\tpositionDropIconLeftAdd : -1,\r\n");
      out.write("\t\t\tname : 'creatordept',\r\n");
      out.write("\t\t\tdisplayField : 'name',\r\n");
      out.write("\t\t\tvalueField : 'id',\r\n");
      out.write("\t\t\tvalue:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope['loginUserDeptObj'].id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\",\r\n");
      out.write("\t\t\trawValue:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope['loginUserDeptObj'].name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\",\r\n");
      out.write("\t\t\tparams : {\r\n");
      out.write("\t\t\t\tdealer_id:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope['currentDealerCustInfoId']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\tvar assure_type = new tracywindyComboBox({\r\n");
      out.write("\t\t\tlazyLoad:true,\r\n");
      out.write("    \t    id:'id_combo_provideassuretype',\r\n");
      out.write("    \t    width:510,\r\n");
      out.write("    \t    renderTo:'id_provideassuretype',\r\n");
      out.write("    \t    loadMode:'local',\r\n");
      out.write("    \t    //pledgetype,collateraltype,warrantertype\r\n");
      out.write("    \t    datas:[{title:'抵押方式',name:'collateraltype'},{title:'质押方式',name:'pledgetype'},{title:'第三方保证',name:'warrantertype'}],\r\n");
      out.write("    \t    readOnly:true,\r\n");
      out.write("    \t    isContainEmpty:true,\r\n");
      out.write("    \t    isCheck:true,\r\n");
      out.write("    \t    dropListHeight:200,\r\n");
      out.write("    \t    positionDropIconLeftAdd:-1,\r\n");
      out.write("    \t    //value:'',\r\n");
      out.write("    \t    name:'provideassuretype',\r\n");
      out.write("    \t\tdisplayField:'title',\r\n");
      out.write("    \t\tvalueField:'name',\r\n");
      out.write("    \t    //otherAttributes:'require=\"true\" label=\"可提供担保方式\"',\r\n");
      out.write("    \t    onSelect:changeAssureType\r\n");
      out.write("    \t });\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//加载页面列表\r\n");
      out.write("\t   \t var table = new tracywindyOperationTable({\r\n");
      out.write("   \t\t resetFormCallback:function(table,$form,operFlag){\r\n");
      out.write("\t   \t\t \r\n");
      out.write("\t\t\tif(\"add\" == operFlag){\r\n");
      out.write("\t\t\t\t//客户类型为承租人时不能修改\r\n");
      out.write("\t\t\t\tgetTracywindyObject(\"id_combo_custtypename\").isDisabled=false;\r\n");
      out.write("\t\t\t\tgetTracywindyObject(\"id_combo_custtypename\").setValue(\"cust_type.cust\");\r\n");
      out.write("\t\t\t\tgetTracywindyObject(\"id_combo_draftname\").readOnlyData = false;\r\n");
      out.write("   \t   \t  \t\tgetTracywindyObject(\"id_combo_draftname\").reload();\r\n");
      out.write("\t\t\t\tgetTracywindyObject(\"id_combo_draftname\").setRawValue(\"否\");\r\n");
      out.write("\t\t\t\tgetTracywindyObject(\"id_combo_draftname\").setValue(\"1\");\r\n");
      out.write("\t\t\t\tjQuery(\"#invalidname\").val(\"否\");\r\n");
      out.write("\t\t\t\tjQuery(\"#invalid\").val(\"1\");\r\n");
      out.write("\t\t\t\tjQuery(\"#creatorname\").val('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginUser.realname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("');\r\n");
      out.write("\t\t\t\tMustFillIn.setRequire(custType.lawCust);//默认承租人\r\n");
      out.write("\t\t\t\tMustFillIn.GoCheck(document.getElementById(\"id_detailInfoForm\"));\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tgetTracywindyObject(\"id_combo_id_is_dealerorcompany\").setValue(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope['currentDealerCustInfoId']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\");\r\n");
      out.write("   \t   \t        getTracywindyObject(\"id_combo_creatordeptname\").setValue(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope['loginUserDeptObj'].id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\");\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (\"update\" == operFlag){\r\n");
      out.write("\t\t\t\t//客户类型为承租人时不能修改\r\n");
      out.write("\t\t\t\tgetTracywindyObject(\"id_combo_custtypename\").isDisabled=true;\r\n");
      out.write("\t \t\t\t//changeCustType();//修改时加载必填\r\n");
      out.write("\t\t\t}\r\n");
      out.write("   \t     },\r\n");
      out.write("   \t\t loadFormDataCallBack:function(table,$form,rowIndex){\r\n");
      out.write("\t\t\tvar rowData = table.getRowDataAt(rowIndex);\r\n");
      out.write("\t\t\t\r\n");
      out.write(" \t\t\tvar objMappingArr = [\r\n");
      out.write(" \t\t\t       \t\t\t    {comboId:'custtypename',rowDataMapping:'custtype'},\r\n");
      out.write(" \t\t\t       \t\t\t    {comboId:'provideassuretype',rowDataMapping:'provideassuretype'},\r\n");
      out.write(" \t\t\t                    {comboId:'custkindname',rowDataMapping:'custkind'},\r\n");
      out.write(" \t\t\t                    {comboId:'industryname',rowDataMapping:'industry'},\r\n");
      out.write(" \t\t\t                    {comboId:'industrylevelbigname',rowDataMapping:'industrylevelbig',parentRowDataMapping:'industry',tableName:'t_industry'},\r\n");
      out.write(" \t\t\t                    {comboId:'industrylevelmiddlename',rowDataMapping:'industrylevelmiddle',parentRowDataMapping:'industrylevelbig',tableName:'t_industry'},\r\n");
      out.write(" \t\t\t                    {comboId:'industrylevelsmallname',rowDataMapping:'industrylevelsmall',parentRowDataMapping:'industrylevelmiddle',tableName:'t_industry'},\r\n");
      out.write(" \t\t\t                    {comboId:'provincename',rowDataMapping:'province'},\r\n");
      out.write(" \t\t\t                    {comboId:'cityname',rowDataMapping:'city',parentRowDataMapping:'province',tableName:'t_district'},\r\n");
      out.write(" \t\t\t                    {comboId:'countyname',rowDataMapping:'county',parentRowDataMapping:'city',tableName:'t_district'},\r\n");
      out.write(" \t\t\t                    {comboId:'ownershipname',rowDataMapping:'ownership'},\r\n");
      out.write(" \t\t\t                    {comboId:'custscalename',rowDataMapping:'custscale'},\r\n");
      out.write(" \t\t\t                    {comboId:'taxlevelname',rowDataMapping:'taxlevel'},\r\n");
      out.write(" \t\t\t                    {comboId:'iscompanymanagename',rowDataMapping:'iscompanymanage'},\r\n");
      out.write(" \t\t\t                    {comboId:'draftname',rowDataMapping:'draft'},\r\n");
      out.write(" \t\t\t                    {comboId:'creatordeptname',rowDataMapping:'creatordept'},\r\n");
      out.write(" \t\t\t                    {comboId:'id_is_banklevel',rowDataMapping:'banklevel'},\r\n");
      out.write(" \t\t\t                    {comboId:'id_is_dealerorcompany',rowDataMapping:'dealerorcompany'},\r\n");
      out.write(" \t\t\t                    {comboId:'valuationfile',rowDataMapping:'valuationfile'}\r\n");
      out.write(" \t\t\t                  ];\r\n");
      out.write("\t\t\t \t\t\t    \r\n");
      out.write("\t\t     for(var j=0;j<objMappingArr.length;j++){\r\n");
      out.write("\t\t\t     var objMapping = objMappingArr[j];\r\n");
      out.write("\t\t\t     var parentRowDataMapping = objMapping['parentRowDataMapping'];\r\n");
      out.write("\t\t\t     var rowDataValue         = rowData[objMapping['rowDataMapping']];\r\n");
      out.write("\t\t\t     var comboId   =  (\"id_combo_\"+objMapping['comboId']);\r\n");
      out.write("\t\t\t     var currentCombo = getTracywindyObject(comboId);\r\n");
      out.write("\t\t\t     if(parentRowDataMapping){\r\n");
      out.write("\t\t\t\t     var parentRowDataMappingValue = rowData[parentRowDataMapping];\r\n");
      out.write("\t\t\t\t     var tableName = objMapping['tableName'];\r\n");
      out.write("\t\t\t\t     currentCombo.setParams({tableName:\"(select id,name from \"+tableName+\" where pid='\"+parentRowDataMappingValue+\"') rs \"}) ;\r\n");
      out.write("\t\t\t\t\t var loadCompleteFunc = (function(combo,rowDataValue){\r\n");
      out.write("\t\t\t\t\t\t       return function(combo){\r\n");
      out.write("\t\t\t\t\t\t    \t   combo.setValue(rowDataValue);\r\n");
      out.write("\t\t\t\t\t\t\t  };\r\n");
      out.write("\t\t\t\t\t })(currentCombo,rowDataValue);\r\n");
      out.write("\t\t\t\t\t currentCombo.loadComplete = loadCompleteFunc;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t    else{\r\n");
      out.write("\t\t\t    \tcurrentCombo.setValue(rowDataValue);\r\n");
      out.write("\t\t\t   }\r\n");
      out.write("\t\t\t    currentCombo.reload();\r\n");
      out.write("\t\t\t }\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\tchangeCustType();//修改时加载必填\r\n");
      out.write("\t\t\tchangeAssureType();//处理可提供担保方式\r\n");
      out.write("\t\t\tif(getTracywindyObject(\"id_combo_draftname\").getValue()=='1'){//不是草稿的时候不能修改\r\n");
      out.write("   \t   \t  \t\t//getTracywindyObject(\"id_combo_draftname\").readOnlyData = true;\r\n");
      out.write("   \t   \t  \t\t//getTracywindyObject(\"id_combo_draftname\").reload();\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tgetTracywindyObject(\"id_combo_draftname\").readOnlyData = false;\r\n");
      out.write("   \t   \t  \t\tgetTracywindyObject(\"id_combo_draftname\").reload();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("    \t },\r\n");
      out.write("    \t //2013-11-29 15:09 修改人 陈兴 原因： 焦经理要求新增法人客户的时候 提示信息由“确认新增【法人客户】么？“改为”确认新增【客户】么？“ ”\r\n");
      out.write("   \t\t tableComment:'客户',\r\n");
      out.write("   \t\t constantFlagTable:'CustLaw',\r\n");
      out.write("   \t\t windowTop:20,\r\n");
      out.write("   \t     border:true,\r\n");
      out.write("         renderTo:'id_tableContainer',\r\n");
      out.write("         title:'法人客户',\r\n");
      out.write("         width:pageWidth,\r\n");
      out.write("         height:pageHeight,\r\n");
      out.write("         id:'id_table',\r\n");
      out.write("         xmlFileName:'/eleasing/jsp/law_manage/law_info.xml',\r\n");
      out.write("         loadMode:'ajax',\r\n");
      out.write("         isPage:true,\r\n");
      out.write("         isFit:false,\r\n");
      out.write("         operButtons:operButtons,\r\n");
      out.write("         enabledPromit:'有效',\r\n");
      out.write("         disabledPromit:'无效',\r\n");
      out.write("         enabledDefaultValue:'1',\r\n");
      out.write("         isNeedEnabled:isAdmin,\r\n");
      out.write("         isNeedEnabled:true,\r\n");
      out.write("         isAutoBreakContent:true,\r\n");
      out.write("         lockedNames:['custname'],\r\n");
      out.write("         columns:[\r\n");
      out.write("\t\t\t\t\t{header:'客户名称',name:'custname',renderer:showCustName,width:180,queryConfig:{}},\r\n");
      out.write("\t\t            {header:'id',name:'id',hidden:true},\r\n");
      out.write("\t\t\t\t\t{header:'客户ID',name:'custid',hidden:true},\r\n");
      out.write("\t\t\t\t\t{header:'客户编号',name:'custnumber',hidden:true},\r\n");
      out.write("\t\t\t\t\t{header:'经销商id',name:'dealerorcompany',hidden:true},\r\n");
      out.write("\t\t\t\t\t{header:'经销商',name:'dealerorcompanyname',width:120,queryConfig:{}},\r\n");
      out.write("\t\t\t\t\t{header:'组织机构代码',name:'orgcode',queryConfig:{}},\r\n");
      out.write("\t\t\t\t\t{header:'客户规模',name:'custscalename'},\r\n");
      out.write("\t\t\t\t\t{header:'客户规模ID',name:'custscale',hidden:true},\r\n");
      out.write("\t\t\t\t\t{header:'客户类别',name:'custtype',hidden:true},\r\n");
      out.write("\t\t            {header:'客户类别',name:'custtypename',width:140,type:'combobox',\r\n");
      out.write("\t\t\t            queryConfig:{\r\n");
      out.write("\t\t\t\t\t   isNewLine:true,\r\n");
      out.write("\t\t\t           width:165,\r\n");
      out.write("\t\t \t\t       xmlFileName:'\\\\combos\\\\comboDict.xml',\r\n");
      out.write("\t\t \t\t       loadMode:'ajax',\r\n");
      out.write("\t\t \t\t       readOnly:true,\r\n");
      out.write("\t\t \t\t\t   isContainEmpty:false,\r\n");
      out.write("\t\t \t\t       name:'custtype',\r\n");
      out.write("\t\t \t\t       displayField:'name',\r\n");
      out.write("\t\t \t\t       valueField:'code',\r\n");
      out.write("\t\t \t\t       leftAdd:0,\r\n");
      out.write("\t\t \t\t       isCheck:true,\r\n");
      out.write("\t\t \t\t       params:{\r\n");
      out.write("\t\t \t\t          pid:'cust_type'\r\n");
      out.write("\t\t \t\t       }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t            }},\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t{header:'客户类别',name:'custtype',hidden:true},\r\n");
      out.write("\t\t\t\t\t{header:'纳税人类别',name:'taxlevelname'},\r\n");
      out.write("\t\t\t\t\t{header:'纳税人识别号/国税登记号',name:'taxregcode'},\r\n");
      out.write("\t\t\t\t\t{header:'开户行',name:'taxbank',width:140},\r\n");
      out.write("\t\t\t\t\t{header:'开户账号',name:'taxacc',width:140},\r\n");
      out.write("\t\t\t\t\t{header:'货款卡号',name:'creditcard',width:140},\r\n");
      out.write("\t\t\t\t\t{header:'是否已办企业管理',name:'iscompanymanagename'},\r\n");
      out.write("\t\t\t\t\t{header:'客户内部行业',name:'custkindname'},\r\n");
      out.write("\t\t\t\t\t{header:'客户内部行业',name:'custkind',hidden:true},\r\n");
      out.write("\t\t\t\t\t{header:'省份',name:'provincename'},\r\n");
      out.write("\t\t\t\t\t{header:'省份',name:'province',hidden:true},\r\n");
      out.write("\t\t\t\t\t{header:'城市',name:'cityname'},\r\n");
      out.write("\t\t\t\t\t{header:'城市',name:'city',hidden:true},\r\n");
      out.write("\t\t\t\t\t{header:'区县',name:'countyname'},\r\n");
      out.write("\t\t\t\t\t{header:'区县',name:'county',hidden:true},\r\n");
      out.write("\t\t\t\t\t{header:'企业性质',name:'ownershipname'},\r\n");
      out.write("\t\t\t\t\t{header:'公司邮寄地址',name:'mailadd',width:160},\r\n");
      out.write("\t\t\t\t\t{header:'邮编',name:'postcode'},\r\n");
      out.write("\t\t\t\t\t{header:'公司网址',name:'website',width:160},\r\n");
      out.write("\t\t\t\t\t{header:'公司地址',name:'postaddr'},\t\r\n");
      out.write("\t\t\t\t\t{header:'传真',name:'faxnumber'},\r\n");
      out.write("\t\t\t\t\t{header:'登记注册号（营业执照号）',name:'regnumber',width:150},\r\n");
      out.write("\t\t\t\t\t//{header:'注册资本',name:'regcapital'},\r\n");
      out.write("\t\t\t\t\t//{header:'实收资本',name:'calledcapital'},\r\n");
      out.write("\t\t\t\t\t{header:'注册地址',name:'regaddr',width:160},\r\n");
      out.write("\t\t\t\t\t{header:'法人代表名称',name:'legalrepresentative',width:140},\r\n");
      out.write("\t\t\t\t\t{header:'法人代表身份证号',name:'idcardno',width:140},\r\n");
      out.write("\t\t\t\t\t{header:'法人代表手机',name:'mobilenumber'},\r\n");
      out.write("\t\t\t\t\t{header:'法人代表电话',name:'phone'},\r\n");
      out.write("\t\t\t\t\t{header:'银行信用等级',name:'banklevel',hidden:true},\r\n");
      out.write("\t\t\t\t\t{header:'净资产',name:'netassets',hidden:true},\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t{header:'客户所属行业门类',name:'industry',hidden:true},\r\n");
      out.write("\t\t\t\t\t{header:'客户所属行业大类',name:'industrylevelbig',hidden:true},\r\n");
      out.write("\t\t\t\t\t{header:'客户所属行业中类',name:'industrylevelmiddle',hidden:true},\r\n");
      out.write("\t\t\t\t\t{header:'客户所属行业小类',name:'industrylevelsmall',hidden:true},\r\n");
      out.write("\t\t\t\t\t{header:'是否作废',name:'invalidname'},\r\n");
      out.write("\t\t\t\t\t{header:'是否草稿',name:'draftname',type:'combobox',\r\n");
      out.write("\t\t\t            queryConfig:{\r\n");
      out.write("\t\t\t\t\t\twidth:165,\r\n");
      out.write("\t\t\t\t\t\tcolSpan:3, \r\n");
      out.write("\t\t\t\t\t\tloadMode:'local',\r\n");
      out.write("\t\t\t\t\t\tdatas:[{title:'否',name:'1'},{title:'是',name:'0'}],\r\n");
      out.write("\t\t\t            displayField:'title',\r\n");
      out.write("\t\t\t            valueField:'name',\r\n");
      out.write("\t\t\t            defaultValue:1\r\n");
      out.write("\t\t\t            }},\r\n");
      out.write("\t\t\t            {header:'操作',name:'enabled',hidden:!isAdmin,renderer:resetCust}\r\n");
      out.write("\t        ],\r\n");
      out.write("\t        params:{\r\n");
      out.write("\t\t     \t\tenabled:\"1\",\r\n");
      out.write("\t\t     \t\tdealer_id:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope['currentDealerCustInfoId']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\",\r\n");
      out.write("\t\t     \t\tlogindeptname:deptname,\r\n");
      out.write("\t\t     \t\tloginuser:currentLoginUserId//\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope['login_userid']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"\r\n");
      out.write("\t\t\t   }\r\n");
      out.write("   \t });\r\n");
      out.write("   });\r\n");
      out.write("\tfunction resetCust(value,tableObj,columnName,columnIndex,rowData){\r\n");
      out.write("    \tvar field=\"-\";\r\n");
      out.write("        var invalid=rowData.invalidname;\r\n");
      out.write("        if(invalid==\"是\"){\r\n");
      out.write("\t    \tvar base = \"<a href='#' onclick='doResetCust(\\\"\"+rowData.custid+\"\\\",\\\"\"+rowData.custname+\"\\\")'>{1}</a>\";\r\n");
      out.write("\t        var updateFlag=\"撤销删除\";\r\n");
      out.write("\t        field=base.replace(\"{1}\",updateFlag);\r\n");
      out.write("        }\r\n");
      out.write("        return field;\r\n");
      out.write("    }\r\n");
      out.write("    var currentLoadMask;\r\n");
      out.write("    function doResetCust(custId,name){\r\n");
      out.write("    \tif(confirm(\"是否撤销删除[\"+name+\"]法人客户?\")){\r\n");
      out.write("    \t\tvar loadMaskMsg = (\"正在撤销删除[\"+name+\"]法人客户,请稍后... \");\r\n");
      out.write("            if(null == currentLoadMask){\r\n");
      out.write("            \tcurrentLoadMask = new tracywindyLoadMask(document.body,loadMaskMsg);\r\n");
      out.write("\t        }\r\n");
      out.write("            currentLoadMask.show();\r\n");
      out.write("            ajaxRequest({\r\n");
      out.write("                url:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/leasing/acl/resetCustEwlp.acl\",\r\n");
      out.write("                params:{\"id\":custId},\r\n");
      out.write("                timeout:30*1000,\r\n");
      out.write("                success:function(res){\r\n");
      out.write("        \t   \t\tres=res.responseText;\r\n");
      out.write("        \t   \t\tres=res.replace(/(^\\s+)|(\\s+$)/g, \"\"); \r\n");
      out.write("\t\t     \t    if(res!=''){\r\n");
      out.write("\t\t\t    \t \talert(res);\r\n");
      out.write("\t\t     \t    }else{\r\n");
      out.write("\t\t     \t    \talert(\"撤销成功[\"+name+\"]!\");\r\n");
      out.write("\t\t     \t    \tgetTracywindyObject(\"id_table\").reload();\r\n");
      out.write("\t\t     \t    }\r\n");
      out.write("                    currentLoadMask.hide();\r\n");
      out.write("                },\r\n");
      out.write("                failure:function(res){\r\n");
      out.write("                    alert(\"服务器通信失败!\");\r\n");
      out.write("                    currentLoadMask.hide();\r\n");
      out.write("                }\r\n");
      out.write("           });\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\t   \r\n");
      out.write("\tfunction showCustName(value,tableObj,columnName,columnIndex,rowData){\r\n");
      out.write("        var base = \"<a href='javascript:void(0);' onclick='showLawCustInfo(\\\"\"+rowData.custid+\"\\\")'>{1}</a>{2}\";\r\n");
      out.write("        var separator = \"&nbsp;&nbsp;\";\r\n");
      out.write("        var updateFlag=value;\r\n");
      out.write("        var updateClickFunc=\"other\";\r\n");
      out.write("        var field=base.replace(\"{1}\",updateFlag).replace(\"{2}\",separator);\r\n");
      out.write("        return field;\r\n");
      out.write("      }\r\n");
      out.write("\t function showLawCustInfo(cust_id){\r\n");
      out.write("\t    \tvar URL = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/leasing/cust_info/cust_info.bi\";\r\n");
      out.write("\t    \tvar params = {cust_id:cust_id,read_only :true};\r\n");
      out.write("\t\t    openFullScreenWindow(URL,params);\r\n");
      out.write("\t        //window.open(getRootPath()+\"/leasing/law_cust/show_template.bi?cust_id=\"+cust_id+\"&jsp=law_cust_all_info\",'','height=500px,width=1000px,top=0,left=0,toolbar=no,menubar=no,scrollbars=no, resizable=no,location=no, status=no');\r\n");
      out.write("\t    }\r\n");
      out.write("\t\t  \r\n");
      out.write("//combox的相关onselect函数\r\n");
      out.write("function choseNext(parentCombo,childComboId,table){//多级联动函数\r\n");
      out.write("\t var parentValue = parentCombo.getValue();\r\n");
      out.write("\t var childCombo  = getTracywindyObject(childComboId);\r\n");
      out.write("\t childCombo.params['tableName'] =\"(select id,name from \"+table+\" where pid='\"+parentValue+\"') rs\" ;\r\n");
      out.write("\t childCombo.reload();\r\n");
      out.write("}\r\n");
      out.write("function changeCustType(){//选择客户类别联动校验函数\r\n");
      out.write("\tMustFillIn.cancelRequireAll(document.getElementById(\"id_detailInfoForm\"));//清除所有必填\r\n");
      out.write("\tvar tempStr=getTracywindyObject(\"id_combo_custtypename\").getValue();\r\n");
      out.write("\tif(tempStr!=\"\"){\r\n");
      out.write("\t\tvar checkLis=tempStr.split(\",\");\r\n");
      out.write("\t\tfor(var i=0;i<checkLis.length;i++){\r\n");
      out.write("\t\t\t//此处需要和数据字典中的值关联起来 如果增加数据字典想需要在此增加设置\r\n");
      out.write("\t\t\tcust_type=custType.getCheckField(\"law\",checkLis[i]);\r\n");
      out.write("\t\t\tMustFillIn.setRequire(cust_type);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tMustFillIn.GoCheck(document.getElementById(\"id_detailInfoForm\"));\r\n");
      out.write("\t}else{//当没有勾选时必须填写名字和客户类别\r\n");
      out.write("\t\tMustFillIn.setRequire([\"custname\",\"rawValue_custtype\",\"rawValue_creatordept\",\"rawValue_dealerorcompany\"]);\r\n");
      out.write("\t\tMustFillIn.GoCheck(document.getElementById(\"id_detailInfoForm\"));\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function changeAssureType(){\r\n");
      out.write("\tvar tempStr=getTracywindyObject(\"id_combo_provideassuretype\").getValue();\r\n");
      out.write("\t$(\"#collateraltype_TR1\").hide();\r\n");
      out.write("\t$(\"#collateraltype_TR2\").hide();\r\n");
      out.write("\t$(\"#pledgetype_TR1\").hide();\r\n");
      out.write("\t$(\"#warrantertype_TR\").hide();\r\n");
      out.write("\tif(tempStr!=\"\"){\r\n");
      out.write("\t\tvar checkLis=tempStr.split(\",\");\r\n");
      out.write("\t\tfor(var i=0;i<checkLis.length;i++){\r\n");
      out.write("\t\t\tvar temp=checkLis[i];\r\n");
      out.write("\t\t\tif(temp==\"collateraltype\"){\r\n");
      out.write("\t\t\t\t$(\"#collateraltype_TR1\").show();\r\n");
      out.write("\t\t\t\t$(\"#collateraltype_TR2\").show();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(temp==\"pledgetype\"){\r\n");
      out.write("\t\t\t\t $(\"#pledgetype_TR1\").show();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(temp==\"warrantertype\"){\r\n");
      out.write("\t\t\t\t$(\"#warrantertype_TR\").show();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function checkDraft(){//确认是否草稿\r\n");
      out.write("\tvar cancelkDraft = false;\r\n");
      out.write("\tif(getTracywindyObject(\"id_combo_draftname\").getValue()=='0'){\r\n");
      out.write("\t\tif(confirm(\"您确认存为草稿吗?\")){\r\n");
      out.write("\t\t\tMustFillIn.cancelRequireAll(document.getElementById(\"id_detailInfoForm\"));//清除所有必填\r\n");
      out.write("\t\t\tMustFillIn.setRequire([\"custname\",\"rawValue_custtype\",\"rawValue_creatordept\",\"rawValue_dealerorcompany\"]);\r\n");
      out.write("\t\t\tMustFillIn.GoCheck(document.getElementById(\"id_detailInfoForm\"));\r\n");
      out.write("\t\t}else{\r\n");
      out.write("\t\t\t//选择取消的时候，直接修改是否为草稿为否，直接返回不做操作。\r\n");
      out.write("\t\t\tchangeCustType();\r\n");
      out.write("\t\t\tgetTracywindyObject(\"id_combo_draftname\").setRawValue(\"否\");\r\n");
      out.write("\t\t\tgetTracywindyObject(\"id_combo_draftname\").setValue(\"1\");\r\n");
      out.write("\t\t\tgetTracywindyObject(\"id_combo_draftname\").reload();\r\n");
      out.write("\t\t\tcancelkDraft = true; \r\n");
      out.write("\t\t}\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tchangeCustType();\r\n");
      out.write("\t}\r\n");
      out.write("\treturn cancelkDraft;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function submitCust(){//提交表单\r\n");
      out.write("\t if ( \"\" != getTracywindyObject(\"id_combo_taxlevelname\").getValue() && \"tax_level_name.1\" == getTracywindyObject(\"id_combo_taxlevelname\").getValue() )\r\n");
      out.write("\t {\r\n");
      out.write("\t\t if($(\"#taxregcode\").val() ==\"\")\r\n");
      out.write("\t\t {\r\n");
      out.write("\t\t\talert(\"现在您选定的是 一般纳税人【纳税人识别号/国税登记号】必填！\");\r\n");
      out.write("\t\t\t$(\"#taxregcode\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t }\r\n");
      out.write("\t\t if($(\"#regnumber\").val() ==\"\")\r\n");
      out.write("\t\t {\r\n");
      out.write("\t\t\talert(\"现在您选定的是 一般纳税人【登记注册号（营业执照号）】必填！\");\r\n");
      out.write("\t\t\t$(\"#regnumber\").focus();\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t }\r\n");
      out.write("\t }\r\n");
      out.write("\tvar tempStr=getTracywindyObject(\"id_combo_provideassuretype\").getValue();\r\n");
      out.write("\tif(tempStr!=\"\"){\r\n");
      out.write("\t\tvar checkLis=tempStr.split(\",\");\r\n");
      out.write("\t\tfor(var i=0;i<checkLis.length;i++){\r\n");
      out.write("\t\t\tvar temp=checkLis[i];\r\n");
      out.write("\t\t\tif(temp==\"collateraltype\"){\r\n");
      out.write("\t\t\t\tif(document.getElementById(\"collateralname\").value==\"\"){\r\n");
      out.write("\t\t\t\t\talert(\"请输入抵押物品名称！\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(document.getElementById(\"valuationfile\").value==\"\"){\r\n");
      out.write("\t\t\t\t\talert(\"请输入有无估价文件！\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(document.getElementById(\"gagevalue\").value==\"\"){\r\n");
      out.write("\t\t\t\t\talert(\"请输入抵押物价值！\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t }\r\n");
      out.write("\t\t\t if(temp==\"pledgetype\"){\r\n");
      out.write("\t\t\t\tif(document.getElementById(\"pledgename\").value==\"\"){\r\n");
      out.write("\t\t\t\t\talert(\"请输入质物名称！\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(document.getElementById(\"pledgevalue\").value==\"\"){\r\n");
      out.write("\t\t\t\t\talert(\"请输入质物价值！\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t }\r\n");
      out.write("\t\t\t if(temp==\"warrantertype\"){\r\n");
      out.write("\t\t\t\tif(document.getElementById(\"warrantername\").value==\"\"){\r\n");
      out.write("\t\t\t\t\talert(\"请输入保证人名称！\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t }\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif(check){\r\n");
      out.write("\t\tif(checkDraft()){return false;}\r\n");
      out.write("\t\tif(getTracywindyObject(\"id_combo_draftname\").getValue()=='1'){\r\n");
      out.write("\t\t\tif(getTracywindyObject(\"id_combo_custtypename\").getValue().indexOf(\"cust_type.cust\")>-1){\r\n");
      out.write("\t\t\t\tvar phone=jQuery(\"#id_phone\").val();\r\n");
      out.write("\t\t\t\tvar mobilenumber=jQuery(\"#id_mobilenumber\").val();\r\n");
      out.write("\t\t\t\tif(phone==\"\"&&mobilenumber==\"\"){\r\n");
      out.write("\t\t\t\t\tjQuery(\"#id_mobilenumber\").focus();\r\n");
      out.write("\t\t\t\t\talert(\"手机电话必须填写其中任意一个!\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tgetTracywindyObject(\"id_table\").operationTable();\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\talert(\"请输入正确的组织机构代码!\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("\treturn true;\r\n");
      out.write("}\r\n");
      out.write("function checkORG(obj){\r\n");
      out.write("\tif(checkORGRight(obj)){\r\n");
      out.write("\t\tif(checkORGPrmary()){\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\treturn false;\r\n");
      out.write("}\r\n");
      out.write("function checkORGRight(obj){//校验组织机构代码\r\n");
      out.write("\t  var financecode=obj.value;\r\n");
      out.write("\t   var fir_value, sec_value;\r\n");
      out.write("\t   var w_i = new Array(8);\r\n");
      out.write("\t   var c_i = new Array(8);\r\n");
      out.write("\t   var j, s = 0;\r\n");
      out.write("\t   var c, i;\r\n");
      out.write("\r\n");
      out.write("\t   var code = financecode;\r\n");
      out.write("\r\n");
      out.write("\t   if (code.length<1) {\r\n");
      out.write("\t     //alert(\"请输入组织机构代码!\");\r\n");
      out.write("\t     //obj.select();\r\n");
      out.write("\t       return false;\r\n");
      out.write("\t   }\r\n");
      out.write("\r\n");
      out.write("\t   if (code == \"00000000-0\") {\r\n");
      out.write("\t     alert(\"组织机构代码错误!\");\r\n");
      out.write("\t     //obj.select();\r\n");
      out.write("\t       return false;\r\n");
      out.write("\t   }\r\n");
      out.write("\r\n");
      out.write("\t   re = /[A-Z0-9]{8}-[A-Z0-9]/;    \r\n");
      out.write("\t   r = code.match(re);   \r\n");
      out.write("\t   if (r == null) {\r\n");
      out.write("\t\t alert(\"组织机构代码错误!\");\r\n");
      out.write("\t     //obj.select();\r\n");
      out.write("\t     return false;\r\n");
      out.write("\t   }        \r\n");
      out.write("\r\n");
      out.write("\t\t   w_i[0] = 3;\r\n");
      out.write("\t\t   w_i[1] = 7;\r\n");
      out.write("\t\t   w_i[2] = 9;\r\n");
      out.write("\t\t   w_i[3] = 10;\r\n");
      out.write("\t\t   w_i[4] = 5;\r\n");
      out.write("\t\t   w_i[5] = 8;\r\n");
      out.write("\t\t   w_i[6] = 4;\r\n");
      out.write("\t\t   w_i[7] = 2;\r\n");
      out.write("\r\n");
      out.write("\t\t   if (financecode.charAt(8) != '-') {\r\n");
      out.write("\t\t   alert(\"组织机构代码错误!\");\r\n");
      out.write("\t\t\t //obj.select();\r\n");
      out.write("\t\t\t   return false;\r\n");
      out.write("\t\t   }\r\n");
      out.write("\r\n");
      out.write("\t\t   for (i = 0; i < 10; i++) {\r\n");
      out.write("\t\t\t   c = financecode.charAt(i);\r\n");
      out.write("\t\t\t   if ((c <= 'z') && (c >= 'a')) \r\n");
      out.write("\t\t\t  {\r\n");
      out.write("\t\t\t   alert(\"组织机构代码错误!\");\r\n");
      out.write("\t\t\t //obj.select();\r\n");
      out.write("\t\t\t\t   return false;\r\n");
      out.write("\t\t\t   }\r\n");
      out.write("\t\t   }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t   fir_value = financecode.charCodeAt(0);\r\n");
      out.write("\t\t   sec_value = financecode.charCodeAt(1);\r\n");
      out.write("\r\n");
      out.write("\t\t   if (fir_value >= 'A'.charCodeAt(0) && fir_value <= 'Z'.charCodeAt(0)) {\r\n");
      out.write("\t\t\t   c_i[0] = fir_value + 32 - 87;\r\n");
      out.write("\t\t   } else {\r\n");
      out.write("\t\t\t\tif (fir_value >= '0'.charCodeAt(0) && fir_value <= '9'.charCodeAt(0)) {\r\n");
      out.write("\t\t\t\tc_i[0] = fir_value - '0'.charCodeAt(0);\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\talert(\"组织机构代码错误!\");\r\n");
      out.write("\t\t\t //obj.select();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t   }\r\n");
      out.write("\r\n");
      out.write("\t\t   s = s + w_i[0] * c_i[0];\r\n");
      out.write("\r\n");
      out.write("\t\t   if (sec_value >= 'A'.charCodeAt(0) && sec_value <= 'Z'.charCodeAt(0)) {\r\n");
      out.write("\t\t\t   c_i[1] = sec_value + 32 - 87;\r\n");
      out.write("\t\t   } else if (sec_value >= '0'.charCodeAt(0) && sec_value <= '9'.charCodeAt(0)) {\r\n");
      out.write("\t\t\t   c_i[1] = sec_value - '0'.charCodeAt(0);\r\n");
      out.write("\t\t   } else {\r\n");
      out.write("\t\t   alert(\"组织机构代码错误!\");\r\n");
      out.write("\t\t\t //obj.select();\r\n");
      out.write("\t\t\t   return false;\r\n");
      out.write("\t\t   }\r\n");
      out.write("\r\n");
      out.write("\t\t   s = s + w_i[1] * c_i[1];\r\n");
      out.write("\t\t   for (j = 2; j < 8; j++) {\r\n");
      out.write("\t\t\t   if (financecode.charAt(j) < '0' || financecode.charAt(j) > '9') {\r\n");
      out.write("\t\t\t   alert(\"组织机构代码错误!\");\r\n");
      out.write("\t\t\t //obj.select();\r\n");
      out.write("\t\t\t\t   return false;\r\n");
      out.write("\t\t\t   }\r\n");
      out.write("\t\t\t   c_i[j] = financecode.charCodeAt(j) - '0'.charCodeAt(0);\r\n");
      out.write("\t\t\t   s = s + w_i[j] * c_i[j];\r\n");
      out.write("\t\t   }\r\n");
      out.write("\r\n");
      out.write("\t\t   c = 11 - (s % 11);\r\n");
      out.write("\r\n");
      out.write("\t\t   if (!((financecode.charAt(9) == 'X' && c == 10) ||\r\n");
      out.write("\t\t\t\t (c == 11 && financecode.charAt(9) == '0') || (c == financecode.charCodeAt(9) - '0'.charCodeAt(0)))) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t  alert(\"组织机构代码错误!\");\r\n");
      out.write("\t\t\t\t  // obj.select();\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t   }\r\n");
      out.write("\t   return true;\r\n");
      out.write("}\r\n");
      out.write("var check=true;\r\n");
      out.write("function checkORGPrmary(){//校验组织结构代码唯一\r\n");
      out.write("\tvar custid=jQuery(\"#custid\").val();\r\n");
      out.write("\tvar orgcode=jQuery(\"#orgcode\").val();\r\n");
      out.write("\tvar dealerorcompany=jQuery(\"#id_is_dealerorcompany\").val();\r\n");
      out.write("\tif(orgcode!=\"\"){\r\n");
      out.write("\t\tvar url = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/acl/checkCustLaw.acl';\r\n");
      out.write("\t\tvar param={};\r\n");
      out.write("\t\tparam.custid=custid;\r\n");
      out.write("\t\tparam.orgcode=orgcode;\r\n");
      out.write("        ajaxRequest({\r\n");
      out.write("             url:url,\r\n");
      out.write("             params:param,\r\n");
      out.write("\t\t     success:function(res){\r\n");
      out.write("\t\t\t     \tif(res!=''){\r\n");
      out.write("\t\t\t     \t\tvar svote=res.responseText;\r\n");
      out.write("\t\t\t     \t    svote=svote.replace(/(^\\s+)|(\\s+$)/g, \"\"); \r\n");
      out.write("\t\t\t     \t    if(svote!=''){\r\n");
      out.write("\t\t\t\t    \t \talert(svote);\r\n");
      out.write("\t\t\t\t     \t\tcheck=false;\r\n");
      out.write("\t\t\t     \t    }else{\r\n");
      out.write("\t\t\t     \t    \tcheck=true;\r\n");
      out.write("\t\t\t     \t    }\r\n");
      out.write("\t\t\t     \t}\r\n");
      out.write("\t\t\t     },\r\n");
      out.write("\t\t     failure:function(res){alert(\"校验组织机构代码唯一失败!\");}\r\n");
      out.write("        });\r\n");
      out.write("\t}\r\n");
      out.write("\treturn check;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<script type='text/javascript'>\r\n");
      out.write("       var currentClientWidth = document.documentElement.clientWidth;\r\n");
      out.write("       jQuery(function(){\r\n");
      out.write("           jQuery(\"#id_detailInfoWindowContainer\").css({\r\n");
      out.write("               width:currentClientWidth*0.95\r\n");
      out.write("           });\r\n");
      out.write("       });\r\n");
      out.write("    </script>\r\n");
      out.write("    <div id=\"id_tableContainer\"></div>\r\n");
      out.write("\t<div id=\"id_detailInfoWindowContainer\" buttons=\"#id-dlg-buttons\" closed=\"true\" modal=\"true\" title=\"法人客户\" style=\"display:none;\">\r\n");
      out.write("\t        <center>\r\n");
      out.write("\t\t        <form id=\"id_detailInfoForm\">\r\n");
      out.write("\t\t\t        <table style=\"width:100%\" class=\"fillTable\">\r\n");
      out.write("\t\t\t             <tr style=\"display:none\"><td><input name=\"id\"  type=\"hidden\" value=\"\"/><input name=\"custid\" id=\"custid\" type=\"hidden\" value=\"\"/></td></tr>\r\n");
      out.write("\t\t\t            <tr class=\"tr-even\">\r\n");
      out.write("\t\t\t            <td class=\"td-content-title\">客户编号:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\" colspan=\"3\">\r\n");
      out.write("\t\t\t            \t\t<input name=\"custnumber\" id=\"custnumber\" maxB=\"100\" label=\"客户编号\" readonly=\"readonly\"  class=\"td-content-input td-content-readonly\"  type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t            <tr  class=\"tr-odd\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">客户名称:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\" colspan=\"3\">\r\n");
      out.write("\t\t\t            \t\t<input style=\"width:91%\" name=\"custname\" id=\"custname\"  maxlength=\"255\"  label=\"客户名称\" maxB=\"255\" class=\"td-content\"   type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            \t\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t            \r\n");
      out.write("\t\t\t               <tr  class=\"tr-even\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">组织机构代码:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\" nowrap=\"nowrap\">\r\n");
      out.write("\t\t\t            \t\t<input name=\"orgcode\" id=\"orgcode\"  onblur=\"checkORG(this)\" label=\"组织结构代码\" maxB=\"100\"  maxlength=\"18\" class=\"td-content\"   type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">客户规模:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<div style=\"float:left\" class=\"leftComboContainer\" id=\"custscalename\"></div>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t            <tr  class=\"tr-odd\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">客户类别:  </td>\r\n");
      out.write("\t\t\t            \t<td class=\"td-content\" colspan=\"3\" id=\"ccc\">\r\n");
      out.write("\t\t\t            \t\t<div style=\"float:left\" class=\"leftComboContainer\" style=\"width:91%\" id=\"custtype\"></div>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t            \t\t<tr class=\"tr-even\">\r\n");
      out.write("\t\t            \t\t<td class=\"td-content-title\">纳税人类别:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<div style=\"float:left\" class=\"leftComboContainer\" id=\"taxlevelname\"></div>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">纳税人识别号/国税登记号:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<input name=\"taxregcode\" id =\"taxregcode\" label=\"纳税人识别号/国税登记号\" maxB=\"100\"  type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t            \t\t</tr>\r\n");
      out.write("\t            \t\t<tr class=\"tr-odd\">\r\n");
      out.write("\t\t            \t\t<td class=\"td-content-title\">开户行:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<input name=\"taxbank\"  label=\"开户行\"  maxB=\"100\"  maxlength=\"100\"  type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">开户账号:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<input name=\"taxacc\"  label=\"开户账号\"  maxB=\"100\"  maxlength=\"30\"  type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t            \t\t</tr>\r\n");
      out.write("\t            \t\t<tr class=\"tr-even\">\r\n");
      out.write("\t            \t\t\t<td class=\"td-content-title\">货款卡号:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<input name=\"creditcard\"  label=\"货款卡号\"  maxB=\"100\"  maxlength=\"30\"  type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">电话:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<input name=\"taxphone\"  label=\"电话\"   maxB=\"100\"   type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t            \t\t</tr>\r\n");
      out.write("\t\t\t            <tr  class=\"tr-odd\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">是否已办企业管理:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<div style=\"float:left\" class=\"leftComboContainer\" id=\"iscompanymanagename\"></div>\r\n");
      out.write("\t\t\t            \t</td>\t\t          \r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">银行信用等级</td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t <div id=\"id_is_banklevel\" class=\"leftComboContainer\" style=\"display:inline-block\"></div></td>\t\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t            <tr  class=\"tr-even\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">企业在职人数:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<input name=\"enterpriseNumber\"  label=\"企业在职人数\" dataType=\"Number\"  maxlength=\"20\"   maxB=\"100\"  type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">企业总人数:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<input name=\"enterpriseTotal\"  label=\"企业总人数\" dataType=\"Number\"  maxB=\"100\"  maxlength=\"20\"  type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t            <tr class=\"tr-odd\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">年营业收入:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<input name=\"annualRevenue\"  label=\"年营业收入\"  maxB=\"100\"  maxlength=\"100\"  dataType=\"PMoney\" type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">净资产:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<input name=\"netassets\"  label=\"净资产\"  maxB=\"100\" dataType=\"PMoney\" maxlength=\"100\"  type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t              <tr  class=\"tr-even\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">客户内部行业:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<div style=\"float:left\" class=\"leftComboContainer\" id=\"custkindname\"></div>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">客户所属行业门类:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<div style=\"float:left\" class=\"leftComboContainer\" id=\"industryname\"></div>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t            <tr  class=\"tr-odd\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">客户所属行业大类:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<div style=\"float:left\" class=\"leftComboContainer\" id=\"industrylevelbigname\"></div>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">客户所属行业中类:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<div style=\"float:left\" class=\"leftComboContainer\" id=\"industrylevelmiddlename\"></div>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t            <tr  class=\"tr-even\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">客户所属行业小类:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<div style=\"float:left\" class=\"leftComboContainer\" id=\"industrylevelsmallname\"></div>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">国家:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t中国\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t             <tr  class=\"tr-odd\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">省份:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<div style=\"float:left\" class=\"leftComboContainer\" id=\"provincename\"></div>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">城市:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<div style=\"float:left\" class=\"leftComboContainer\" id=\"cityname\"></div>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t            <tr  class=\"tr-even\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">区县:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<div style=\"float:left\" class=\"leftComboContainer\" id=\"countyname\"></div>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">企业性质:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<div style=\"float:left\" class=\"leftComboContainer\" id=\"ownershipname\"></div>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t             <tr  class=\"tr-odd\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">法人代表:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<input name=\"legalrepresentative\"  label=\"法人代表\"  maxlength=\"50\"  maxB=\"50\" type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">法人代表身份证号:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<input name=\"idcardno\"  label=\"法人代表身份证号\" maxB=\"30\"  maxlength=\"18\" dataType=\"IdCard\" type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t             <tr  class=\"tr-even\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">手机:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<input name=\"mobilenumber\"  label=\"手机\" dataType=\"Mobile\"  maxlength=\"11\" maxB=\"20\" type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">电话:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<input name=\"phone\"  label=\"电话\"   maxB=\"100\"  type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t             <tr  class=\"tr-odd\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">公司邮寄地址:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\" colspan=\"3\">\r\n");
      out.write("\t\t\t            \t\t<textarea name=\"mailadd\"  label=\"公司邮寄地址\" maxB=\"255\" maxlength=\"255\" style=\"width:92%\"  type=\"text\" ></textarea>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t            <tr   class=\"tr-even\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">邮编:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<input name=\"postcode\"  label=\"邮编\"  dataType=\"Zip\"  maxlength=\"6\" maxB=\"50\" type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">公司网址:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<input name=\"website\"  label=\"公司网址\" dataType=\"Url\" maxB=\"100\" maxlength=\"100\" type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t            <tr  class=\"tr-odd\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">公司地址: </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\" colspan=\"3\">\r\n");
      out.write("\t\t\t            \t\t<textarea name=\"postaddr\"  label=\"公司地址\" style=\"width:92%\" maxB=\"255\" type=\"text\" ></textarea>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t            <tr class=\"tr-even\">\r\n");
      out.write("\t\t\t            <td class=\"td-content-title\">传真:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\" colspan=\"3\">\r\n");
      out.write("\t\t\t            \t\t<input name=\"faxnumber\"  label=\"传真\" maxB=\"100\" type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t            <tr  class=\"tr-odd\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\"><B>注册资本 </B> </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\"></td> \r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\"></td> \r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\"></td> \r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t             <tr   class=\"tr-even\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">出资方式及金额(货币、实物等):  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<input name=\"investmentamoun\"  label=\"出资方式及金额(货币、实物等)\" maxB=\"100\" maxlength=\"100\" dataType=\"PMoney\"  type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">注册登记机关: </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<textarea name=\"registrationauthority\" style=\"width:77%\"  label=\"注册登记机关\" maxB=\"100\" maxlength=\"100\" type=\"text\" ></textarea>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t            <tr  class=\"tr-odd\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">认缴额:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<input name=\"subscriptions\"  label=\"认缴额\" dataType=\"PMoney\" maxB=\"100\" maxlength=\"100\" type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">登记注册号（营业执照号）: </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<textarea name=\"regnumber\" style=\"width:77%\" id=\"regnumber\"  label=\"登记注册号（营业执照号）\"  maxB=\"100\" maxlength=\"100\" type=\"text\" ></textarea>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t            <tr   class=\"tr-even\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">实缴额:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<input name=\"paidinamount\" id=\"paidinamount\" label=\"实缴额\" dataType=\"PMoney\" maxB=\"200\" maxlength=\"20\" type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("             \t\t\t\t<td class=\"td-content-title\">成立时间:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<input name=\"fundtime\" id=\"fundtime\"  label=\"成立时间\"  class=\"Wdate td-content-input td-content-readonly\"  onClick=\"WdatePicker(this,{readOnly:true})\" readOnly   type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            \t\r\n");
      out.write("          \t\t\t    </tr>\r\n");
      out.write("          \t\t\t    <tr id=\"pledgetype_TR\"  class=\"tr-odd\">\r\n");
      out.write("          \t\t\t    \t\t<td class=\"td-content-title\"><B>可提供担保方式</B></td>\r\n");
      out.write("          \t\t\t    \t\t<td class=\"td-content\"  colspan=\"3\">\r\n");
      out.write("\t\t\t\t            \t\t<div style=\"float:left;\" class=\"leftComboContainer\" id=\"id_provideassuretype\"></div>\r\n");
      out.write("\t\t\t\t            \t</td>\r\n");
      out.write("          \t\t\t    \t</tr>\r\n");
      out.write("          \t\t\t    \t<tr id=\"collateraltype_TR1\" style=\"display: none;\" class=\"tr-even\">\r\n");
      out.write("          \t\t\t    \t\t<td class=\"td-content-title\">抵押物品名称:</td>\r\n");
      out.write("\t\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t\t            \t\t<input name=\"collateralname\" id=\"collateralname\" label=\"抵押物品名称\"  maxB=\"50\"  type=\"text\" />\r\n");
      out.write("\t\t\t\t            \t</td>\r\n");
      out.write("\t\t\t\t            \t<td class=\"td-content-title\">有无估价文件:  </td>  \r\n");
      out.write("\t\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t\t            \t\t<div style=\"float:left\" class=\"leftComboContainer\" id=\"valuationfile\"></div>\r\n");
      out.write("\t\t\t\t            \t</td>\r\n");
      out.write("          \t\t\t    \t</tr>\r\n");
      out.write("          \t\t\t    \t<tr id=\"collateraltype_TR2\" style=\"display: none;\"  class=\"tr-odd\">\r\n");
      out.write("          \t\t\t    \t\t<td class=\"td-content-title\">抵押物价值:</td>\r\n");
      out.write("\t\t\t\t            \t<td class=\"td-content\" colspan=\"3\">\r\n");
      out.write("\t\t\t\t            \t\t<input name=\"gagevalue\" id=\"gagevalue\" label=\"抵押物价值\"  maxB=\"22\" maxlength=\"22\" type=\"text\" dataType=\"PMoney\" />\r\n");
      out.write("\t\t\t\t            \t</td>\r\n");
      out.write("          \t\t\t    \t</tr>\r\n");
      out.write("          \t\t\t    \t<tr id=\"pledgetype_TR1\" style=\"display: none;\" class=\"tr-even\">\r\n");
      out.write("          \t\t\t    \t\t<td class=\"td-content-title\">质物名称:</td>\r\n");
      out.write("\t\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t\t            \t\t<input name=\"pledgename\" id=\"pledgename\"  label=\"质物名称\"  maxB=\"50\" maxlength=\"50\" type=\"text\" />\r\n");
      out.write("\t\t\t\t            \t</td>\r\n");
      out.write("\t\t\t\t            \t<td class=\"td-content-title\">质物价值:  </td>  \r\n");
      out.write("\t\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t\t            \t\t<input name=\"pledgevalue\" dataType=\"PMoney\" id=\"pledgevalue\" label=\"质物价值\" maxB=\"22\" maxlength=\"22\"  type=\"text\" />\r\n");
      out.write("\t\t\t\t            \t</td>\r\n");
      out.write("          \t\t\t    \t</tr>\r\n");
      out.write("          \t\t\t    \t<tr id=\"warrantertype_TR\"  style=\"display: none;\" class=\"tr-odd\">\r\n");
      out.write("          \t\t\t    \t\t<td class=\"td-content-title\">保证人名称:</td>\r\n");
      out.write("\t\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t\t            \t\t<input name=\"warrantername\" id=\"warrantername\"  label=\"保证人名称\" maxlength=\"50\" maxB=\"50\"  type=\"text\" />\r\n");
      out.write("\t\t\t\t            \t</td>\r\n");
      out.write("\t\t\t\t           \t\t\t           \r\n");
      out.write("\t\t\t\t            \t<td class=\"td-content-title\"> </td>  \r\n");
      out.write("\t\t\t\t            \t<td class=\"td-content\" >\r\n");
      out.write("\t\t\t\t            \t</td>\r\n");
      out.write("          \t\t\t    \t</tr>\r\n");
      out.write("\t\t\t           <tr class=\"tr-even\">\r\n");
      out.write("\t\t\t           <td class=\"td-content-title\">注册地址 : </td>  \r\n");
      out.write("\t\t\t\t\t\t            \t<td class=\"td-content\" colspan=\"3\">\r\n");
      out.write("\t\t\t\t\t\t            \t\t<input name=\"taxregadd\" label=\"注册地址 : \"  maxB=\"255\" maxlength=\"255\" style=\"width:92%\"  type=\"text\"/>\r\n");
      out.write("\t\t\t\t\t\t            \t</td>\r\n");
      out.write("\t\t\t           </tr>\r\n");
      out.write("\t\t\t            <tr  class=\"tr-odd\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">经营方式 : </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\" colspan=\"3\">\r\n");
      out.write("\t\t\t            \t\t<textarea name=\"bizmethod\"  label=\"经营方式: \" maxB=\"2000\" maxlength=\"2000\" style=\"width:92%\"  type=\"text\" ></textarea>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t            <tr  class=\"tr-even\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">经营范围（主营） : </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\" colspan=\"3\">\r\n");
      out.write("\t\t\t            \t\t<textarea name=\"bizscopeprimary\"  label=\"经营范围（主营） \" maxB=\"2000\" maxlength=\"2000\" style=\"width:92%\" type=\"text\" ></textarea>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t            <tr  class=\"tr-odd\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">经营范围（兼营） : </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\" colspan=\"3\">\r\n");
      out.write("\t\t\t            \t\t<textarea name=\"bizscopesecondary\"  label=\"经营范围（兼营） : \"  style=\"width:92%\" maxB=\"2000\" maxlength=\"2000\" type=\"text\" ></textarea>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t            <tr  class=\"tr-even\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">客户概况 : </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\" colspan=\"3\">\r\n");
      out.write("\t\t\t            \t\t<textarea name=\"cimemo\"  label=\"客户概况\"  maxB=\"2000\" maxlength=\"2000\" style=\"width:92%\" type=\"text\" ></textarea>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t            <tr  class=\"tr-odd\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">是否作废: </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<input name=\"invalidname\" id=\"invalidname\"  label=\"是否作废 \" class=\"td-content-readonly\" readonly=\"readonly\"  type=\"text\" />\r\n");
      out.write("\t\t\t            \t\t<input name=\"invalid\" id=\"invalid\"  label=\"是否作废 \" class=\"td-content-readonly\" readonly=\"readonly\"  type=\"hidden\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">是否草稿: </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<div style=\"float:left\" class=\"leftComboContainer\" id=\"draftname\"></div>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t            \t<tr class=\"tr-even\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">经销商:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t<div style=\"float: left\" class=\"leftComboContainer\" id=\"id_is_dealerorcompany\" ></div></td>\r\n");
      out.write("\t\t\t            \t\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">登记人 :  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<input name=\"creatorname\" id=\"creatorname\" label=\"登记人 \" class=\"td-content-readonly\" readonly=\"readonly\" type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t             <tr  class=\"tr-odd\">\r\n");
      out.write("\t\t\t           \t \t<td class=\"td-content-title\">登记人部门:</td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<div style=\"float:left\" class=\"leftComboContainer\" label=\"登记人部门 \" id=\"creatordeptname\"></div>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">登记时间:</td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<input name=\"createdate\" id=\"createdate\" isDefaultDate=\"true\" label=\"登记时间 \" class=\"td-content-readonly\"  readonly=\"readonly\" type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            \t</tr>\r\n");
      out.write("\t\t\t        </table>\r\n");
      out.write("\t\t        </form>\r\n");
      out.write("\t        </center>\r\n");
      out.write("\t        <div style=\"text-align:center;width:800px;display:none;height:40px;line-height:40px;\" id=\"id-dlg-buttons\">\r\n");
      out.write("\t\t  <a  style=\"margin-left:20px;\" href=\"javascript:void(0);\" class=\"btn btn-primary\" onclick='submitCust();'><span>确定</span></a>\r\n");
      out.write("\t\t  <a  style=\"margin-left:20px;\" href=\"javascript:void(0);\" class=\"btn btn-primary\" onclick='jQuery(\"#id_detailInfoWindowContainer\").window(\"close\");'><span>取消</span></a>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_permission_005faction_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  permission:action
    com.kernal.tags.ActionPermissionTag _jspx_th_permission_005faction_005f0 = (com.kernal.tags.ActionPermissionTag) _005fjspx_005ftagPool_005fpermission_005faction_0026_005fcode.get(com.kernal.tags.ActionPermissionTag.class);
    _jspx_th_permission_005faction_005f0.setPageContext(_jspx_page_context);
    _jspx_th_permission_005faction_005f0.setParent(null);
    // /WEB-INF/jsps/solutions/leasing/cust_info/cust_company/cust_company_list.jsp(63,0) name = code type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_permission_005faction_005f0.setCode("cust_add_update");
    int _jspx_eval_permission_005faction_005f0 = _jspx_th_permission_005faction_005f0.doStartTag();
    if (_jspx_eval_permission_005faction_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_permission_005faction_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_permission_005faction_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_permission_005faction_005f0.doInitBody();
      }
      do {
        out.write("\r\n");
        out.write("<script type=\"text/javascript\">\r\n");
        out.write("isAdmin=true;\r\n");
        out.write("operButtons='新增|修改';\r\n");
        out.write("</script >\r\n");
        int evalDoAfterBody = _jspx_th_permission_005faction_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_permission_005faction_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_permission_005faction_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fpermission_005faction_0026_005fcode.reuse(_jspx_th_permission_005faction_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fpermission_005faction_0026_005fcode.reuse(_jspx_th_permission_005faction_005f0);
    return false;
  }

  private boolean _jspx_meth_permission_005faction_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  permission:action
    com.kernal.tags.ActionPermissionTag _jspx_th_permission_005faction_005f1 = (com.kernal.tags.ActionPermissionTag) _005fjspx_005ftagPool_005fpermission_005faction_0026_005fcode.get(com.kernal.tags.ActionPermissionTag.class);
    _jspx_th_permission_005faction_005f1.setPageContext(_jspx_page_context);
    _jspx_th_permission_005faction_005f1.setParent(null);
    // /WEB-INF/jsps/solutions/leasing/cust_info/cust_company/cust_company_list.jsp(69,0) name = code type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_permission_005faction_005f1.setCode("admin_action");
    int _jspx_eval_permission_005faction_005f1 = _jspx_th_permission_005faction_005f1.doStartTag();
    if (_jspx_eval_permission_005faction_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_permission_005faction_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_permission_005faction_005f1.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_permission_005faction_005f1.doInitBody();
      }
      do {
        out.write("\r\n");
        out.write("<script type=\"text/javascript\">\r\n");
        out.write("isAdmin=true;\r\n");
        out.write("operButtons='新增|修改|删除|状态';\r\n");
        out.write("</script >\r\n");
        int evalDoAfterBody = _jspx_th_permission_005faction_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_permission_005faction_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_permission_005faction_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fpermission_005faction_0026_005fcode.reuse(_jspx_th_permission_005faction_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fpermission_005faction_0026_005fcode.reuse(_jspx_th_permission_005faction_005f1);
    return false;
  }
}
