package org.apache.jsp.WEB_002dINF.jsps.solutions.leasing.voucher;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kernal.utils.FileUtil;
import com.kernal.utils.WebUtil;

public final class voucher_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.List<java.lang.String> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.List<java.lang.String> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>凭证信息</title>\r\n");
      out.write("<!--css sheet-->\r\n");
      out.write("<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/dtree/dtree.css\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/jquery-easyui/easyui.css\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/jquery-easyui/icon.css\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/tracywindy/tracywindy.css\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/tracywindy/button.css\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<link\r\n");
      out.write("\thref=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/tracywindy/workFlowUtil.css\"\r\n");
      out.write("\trel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<!--javascript libray-->\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/workFlowUtil.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyUtils.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyJsonUtil.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyAjax.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery/jquery.easyui.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyLoadMask.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyTable.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyComboBox.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindySerializeFormToJsonObject.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/my97DatePicker/WdatePicker.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/validator.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyOperationTable.js\"></script>\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("html, body {\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar pageWidth  = document.documentElement.clientWidth-2;\r\n");
      out.write("\tvar pageHeight = document.documentElement.clientHeight-2;\r\n");
      out.write("\tjQuery(function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar table = new tracywindyOperationTable({\r\n");
      out.write("\t   \t\tresetFormCallback:function(table,$form,operFlag){\r\n");
      out.write("\t   \t\t if(\"add\" == operFlag){\r\n");
      out.write("\t   \t\t\tvar rowData = table.getRowDataAt(0);\r\n");
      out.write("\t\t   \t  var select_contract = getTracywindyObject(\"id_combo_iscardname\");\r\n");
      out.write("\t\t   \t     select_contract.setValue(\"1\");\r\n");
      out.write("\t\t   \t  \r\n");
      out.write("\t   \t     }\r\n");
      out.write("\t     \t },\r\n");
      out.write("\t\t\t \r\n");
      out.write("\t   \t\t loadFormDataCallBack:function(table,$form,rowIndex){\r\n");
      out.write("\t\t   \t\t var rowData = table.getRowDataAt(rowIndex);\r\n");
      out.write("\t\t   \t  \t var select_contract = getTracywindyObject(\"id_combo_iscardname\");\r\n");
      out.write("\t\t   \t     select_contract.setValue(rowData[\"iscard\"]);\r\n");
      out.write("\t\t   \r\n");
      out.write("\t\t   \t    \r\n");
      out.write("\t\t },\r\n");
      out.write("\t\t\t tableComment:'凭证信息',\r\n");
      out.write("\t   \t\t constantFlagTable:'ContractDebit',\r\n");
      out.write("\t         renderTo:'id_tableContainer',\r\n");
      out.write("\t         title:'凭证信息',\r\n");
      out.write("\t         width:pageWidth,\r\n");
      out.write("\t         height:pageHeight,\r\n");
      out.write("\t         id:'id_table',\r\n");
      out.write("\t         xmlFileName:'eleasing/jsp/voucher/voucher_list.xml',\r\n");
      out.write("\t         loadMode:'ajax',\r\n");
      out.write("\t         isPage:true,\r\n");
      out.write("\t         isFit:false,\r\n");
      out.write("\t         border:true,\r\n");
      out.write("\t         isRank:true,\r\n");
      out.write("\t         lazyLoad:true,\r\n");
      out.write("\t         isCheck:true,\r\n");
      out.write("\t         checkType:'checkbox',\r\n");
      out.write("\t         operButtons:'',\r\n");
      out.write("\t         tools : [ {\r\n");
      out.write("\t\t  \t\t\thtml : '<font color=\"red\">修改</font>',\r\n");
      out.write("\t\t  \t\t\thandler : function(table) {\r\n");
      out.write("\t\t \t\t\t\tvar voucherIDValue = table.getCheckedRowDatas();\r\n");
      out.write("\t\t \t\t\t\tif (0 == voucherIDValue.length) {\r\n");
      out.write("\t\t \t\t\t\t\talert(\"请选择需要修改的数据！\");\r\n");
      out.write("\t\t \t\t\t\t\treturn false;\r\n");
      out.write("\t\t \t\t\t\t}\r\n");
      out.write("\t\t \t\t\t\tvar id = voucherIDValue[0].id;\r\n");
      out.write("\t\t \t\t\t\tvar URL = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/leasing/updateInsuranceInfo.action\";\r\n");
      out.write("\t\t\t        \tvar params = {id:id,read_only:false};\r\n");
      out.write("\t\t\t    \t    openFullScreenWindow(URL,params);\r\n");
      out.write("\t\t \t\t\t\t//window.open(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/leasing/voucher/voucher_mod.bi\",\"_blank\");\r\n");
      out.write("\t\t  \t\t\t},\r\n");
      out.write("\t\t  \t\t\ticonCls : 'icon-update'\r\n");
      out.write("\t\t  \t\t},\r\n");
      out.write("\t\t  \t\t{\r\n");
      out.write("\t\t  \t\t\thtml : '<font color=\"red\">导出</font>',\r\n");
      out.write("\t\t  \t\t\thandler : function(table) {\r\n");
      out.write("\t\t  \t\t\t\tvar voucherIDValue = table.getCheckedRowDatas();\r\n");
      out.write("\t\t  \t\t\t\tvar voucherid=new Array();\r\n");
      out.write("\t\t  \t\t\t\tfor (var i=0;i<voucherIDValue.length;i++){\r\n");
      out.write("\t\t  \t\t\t\t\tif(voucherIDValue[i].easflag=='已导出'){\r\n");
      out.write("\t\t  \t\t\t\t\t\talert(voucherIDValue[i].modlename+\"的\"+voucherIDValue[i].vouchernumber+\"凭证状态为已导出，不能再导出\");\r\n");
      out.write("\t\t  \t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t  \t\t\t\t\t}else{\r\n");
      out.write("\t\t  \t\t\t\t\t\tvoucherid[i]=voucherIDValue[i].id;\r\n");
      out.write("\t\t  \t\t\t\t\t}\r\n");
      out.write("\t\t  \t\t\t\t}\r\n");
      out.write("\t\t  \t\t\t\t//alert(voucherid.length);\r\n");
      out.write("\t\t  \t\t\t\tvar params=getQueryAreaParams(table,false);\r\n");
      out.write("\t\t  \t\t\t\tparams.voucherid = JsonUtil.encode(voucherid);\r\n");
      out.write("\t\t  \t\t\t\t//params.url = 'eleasing/jsp/voucher/voucher_list.xml';\r\n");
      out.write("\t\t  \t\t\t\t$.post(\"leasing/toEas.action\", params);\r\n");
      out.write("\t\t  \t\t\t\t//console.info(params);\r\n");
      out.write("\t\t  \t\t\t},\r\n");
      out.write("\t  \t\t\t\t iconCls : 'icon-add'\r\n");
      out.write("\t  \t\t\t \r\n");
      out.write("\t  \t\t} ],\r\n");
      out.write("\t         columns:[\r\n");
      out.write("\t\t\t\t\t\t{header:'id',name:'id',hidden:true},\r\n");
      out.write("\t\t\t\t\t\t{header:'客户名称',name:'custname',queryConfig:{}},\r\n");
      out.write("\t\t\t\t\t\t{header:'业务合同号',name:'contract_number',width:200,queryConfig:{}},\r\n");
      out.write("\t\t\t\t\t\t{header:'经销商名称',name:'dealname',width:200,queryConfig:{}},\r\n");
      out.write("\t\t\t\t\t\t{header:'系统模块',name:'modlename',width:150,type:'combobox',\r\n");
      out.write("\t\t\t\t\t\tqueryConfig:{\r\n");
      out.write("\t\t\t\t\t\t\t   width:165,\r\n");
      out.write("\t\t\t\t\t\t       xmlFileName:'eleasing/jsp/voucher/voucher_status.xml',\r\n");
      out.write("\t\t\t\t\t\t       loadMode:'ajax',\r\n");
      out.write("\t\t\t\t\t\t       readOnly:false,\r\n");
      out.write("\t\t\t\t\t\t       isAjaxLenovo:true,\r\n");
      out.write("\t\t\t\t\t\t       displayField:'name',\r\n");
      out.write("\t\t\t\t\t\t       valueField:'id',\r\n");
      out.write("\t\t\t\t\t\t       isForceModify:true\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t}},\r\n");
      out.write("\t\t\t\t\t\t{header:'导出备注',name:'easmemo'},\r\n");
      out.write("\t\t\t\t\t\t{header:'摘要',name:'voucherabstract',queryConfig:{isNewLine:true,}},\r\n");
      out.write("\t\t\t\t\t\t{header:'凭证号',name:'vouchernumber',width:150,queryConfig:{}},\r\n");
      out.write("\t\t\t\t\t\t{header:'到账日期',name:'bookeddate',width:150,type:\"date\",isRange:true,queryConfig:{}},\r\n");
      out.write("\t\t\t\t\t\t{header:'记账日期',name:'bizdate',width:150},\r\n");
      out.write("\t\t\t\t\t\t{header:'凭证字',name:'vouchertype'},\r\n");
      out.write("\t\t\t\t\t\t{header:'财务客户',name:'', renderer:function(value,tableObj,columnName,columnIndex,rowData){\r\n");
      out.write("\t\t\t\t\t       \t return \"<a href='javascript:void(0);' onclick='showName(\\\"\"+rowData.id+\"\\\")'>详情</a>\";\r\n");
      out.write("\t\t\t\t         }},\r\n");
      out.write("\t\t\t\t\t\t{header:'凭证状态',name:'status',type:'combobox',\r\n");
      out.write("\t\t\t\t\t\t\t\t queryConfig:{\r\n");
      out.write("\t\t\t\t\t\t\t\t\tcolSpan:1,\r\n");
      out.write("\t\t\t\t\t\t\t\t\tloadMode:'local',\r\n");
      out.write("\t\t\t\t\t\t\t\t\tdatas:[{title:'已完整',name:'已完整'},{title:'未完整',name:'未完整'}],\r\n");
      out.write("\t\t\t\t\t\t            displayField:'title',\r\n");
      out.write("\t\t\t\t\t\t            valueField:'name'\r\n");
      out.write("\t\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\t\t{header:'导出状态',name:'easflag',type:'combobox',\r\n");
      out.write("\t\t\t\t\t\t\tqueryConfig:{\r\n");
      out.write("\t\t\t\t\t\t\tcolSpan:2,\r\n");
      out.write("\t\t\t\t\t\t\tloadMode:'local',\r\n");
      out.write("\t\t\t\t\t\t\tdatas:[{title:'未导出',name:'0'},{title:'已导出',name:'1'}],\r\n");
      out.write("\t\t\t\t            displayField:'title',\r\n");
      out.write("\t\t\t\t            valueField:'name',\r\n");
      out.write("\t\t\t\t            isNewLine:true,\r\n");
      out.write("\t\t\t\t            defaultValue:1\r\n");
      out.write("\t\t\t\t\t\t\t}},\r\n");
      out.write("\t\t\t\t\t\t{header:'操作时间',name:'generatedate',type:\"date\",isRange:true,queryConfig:{colSpan:2}},\r\n");
      out.write("\t\t\t\t\t\t{header:'导出时间',name:'expdate'},\r\n");
      out.write("\t\t\t\t\t\t{header:'金额',name:'originalamount',queryConfig:{}}\r\n");
      out.write("\t\t        ]\r\n");
      out.write("   \t });\r\n");
      out.write("   });\r\n");
      out.write("\r\n");
      out.write("     \tfunction showName(vouchernumber){\r\n");
      out.write("     \t\tvar URL = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/leasing/addInsuranceInfo.action\";\r\n");
      out.write("        \tvar params = {vouchernumber:vouchernumber,read_only:false};\r\n");
      out.write("    \t    openFullScreenWindow(URL,params);\r\n");
      out.write("     \t   //window.open(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/leasing/addInsuranceInfo.action\",\"_blank\");\r\n");
      out.write("     \t}\r\n");
      out.write("\r\n");
      out.write("     \t/*var currentLoadMask;\r\n");
      out.write("     \tfunction showName(vouchernumber){\r\n");
      out.write("     \t\t\r\n");
      out.write("     \t\t\r\n");
      out.write("     \t\t    var params = {vouchernumber:vouchernumber};\r\n");
      out.write("     \t        ajaxRequest({\r\n");
      out.write("     \t            url:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/leasing/addInsuranceInfo.action\",\r\n");
      out.write("     \t           params:params,\r\n");
      out.write("     \t            timeout:30*1000,\r\n");
      out.write("     \t            method:'POST',\r\n");
      out.write("     \t            success:function(res){\r\n");
      out.write("     \t    \t   \t\tres=res.responseText;\r\n");
      out.write("     \t    \t   \t\tres=res.replace(/(^\\s+)|(\\s+$)/g, \"\"); \r\n");
      out.write("     \t\t     \t    if(res!=''){\r\n");
      out.write("         \t\t     \t    alert(res);\r\n");
      out.write("     \t\t     \t    }else{\r\n");
      out.write("         \t\t     \t    \r\n");
      out.write("     \t\t  \t    \t}\r\n");
      out.write("     \t            },\r\n");
      out.write("     \t            \r\n");
      out.write("     \t            failure:function(res){\r\n");
      out.write("     \t                jQuery.messager.alert('错误提示',\"<div style='font-size:18px;line-height:30px;'>服务器通信失败!</div>\",'error');\r\n");
      out.write("     \t                //currentLoadMask.hide();\r\n");
      out.write("     \t            }\r\n");
      out.write("     \t       });\r\n");
      out.write("     \t    \r\n");
      out.write("     \t}*/\r\n");
      out.write("\t   \r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"id_tableContainer\"></div>\r\n");
      out.write("<div id=\"id_detailInfoWindowContainer\" buttons=\"#id-dlg-buttons\" closed=\"true\" modal=\"true\" title=\"凭证信息\" style=\"display:none;width:800px;height:400px\">\r\n");
      out.write("  <center>\r\n");
      out.write("    <form id=\"id_detailInfoForm\">\r\n");
      out.write("      <table style=\"width: 90%\">\r\n");
      out.write("        <tr style=\"display:none\">\r\n");
      out.write("          <td colspan=\"4\"><input name=\"id\" type=\"hidden\" value=\"\"/><input name=\"contractid\" type=\"hidden\" value=\"\"/></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <!--  <tr class=\"tr-even\">\r\n");
      out.write("          <td class=\"input_label_desc\" align=\"left\">客户名:</td>\r\n");
      out.write("          <td class=\"td-content\" colspan=\"3\"><input name=\"custname\" id=\"custname\" style=\"width:520px\"  label=\"客户名\" class=\"td-content-input td-content-readonly\"  readonly type=\"text\" /></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr class=\"tr-even\">\r\n");
      out.write("          <td class=\"input_label_desc\" align=\"left\">经销商:</td>\r\n");
      out.write("          <td class=\"td-content\" colspan=\"3\"><input name=\"dealername\" id=\"dealername\" style=\"width:520px\" label=\"经销商\" class=\"td-content-input td-content-readonly\"  readonly type=\"text\" /></td>\r\n");
      out.write("        </tr>\r\n");
      out.write("        <tr class=\"tr-even\">\r\n");
      out.write("          <td class=\"input_label_desc\" align=\"left\">项目名:</td>\r\n");
      out.write("          <td class=\"td-content\" colspan=\"3\"><input name=\"projectname\" id=\"projectname\" style=\"width:520px\" label=\"项目名\" class=\"td-content-input td-content-readonly\"  readonly type=\"text\" /></td>\r\n");
      out.write("        </tr>        \r\n");
      out.write("        <tr class=\"tr-even\">\r\n");
      out.write("          <td class=\"input_label_desc\" align=\"left\">合同号:</td>\r\n");
      out.write("          <td class=\"td-content\"><input name=\"cid\" id=\"cid\"   label=\"合同号\" class=\"td-content-input td-content-readonly\"  readonly type=\"text\" /></td>\r\n");
      out.write("          <td class=\"input_label_desc\" align=\"left\">业务合同号:</td>\r\n");
      out.write("          <td class=\"td-content\"><input name=\"contractnumber\" id=\"contractnumber\"   label=\"业务合同号\" class=\"td-content-input td-content-readonly\"  readonly type=\"text\" /></td>\r\n");
      out.write("          </tr>   \r\n");
      out.write("        <tr class=\"tr-odd\">\r\n");
      out.write("        <td class=\"input_label_desc\" align=\"left\">是否卡扣:</td>\r\n");
      out.write("          <td class=\"td-content\"><div style=\"float: left\" class=\"leftComboContainer\"\r\n");
      out.write("\t\t\t\tid=\"iscardname\"></div>\r\n");
      out.write("            <span class=\"content-required\">*</span></td>\r\n");
      out.write("          <td class=\"input_label_desc\" align=\"left\">银行卡号:</td>\r\n");
      out.write("          <td class=\"td-content\"><input name=\"cardnum\" require=\"true\"  class=\"td-content-input\"\r\n");
      out.write("\t\t\t\tlabel=\"银行卡号\" type=\"text\" />\r\n");
      out.write("            <span class=\"content-required\">*</span></td>\r\n");
      out.write("        </tr>-->\r\n");
      out.write("      </table>\r\n");
      out.write("    </form>\r\n");
      out.write("  </center>\r\n");
      out.write("</div>\r\n");
      out.write("<div style=\"text-align:center;width:800px;display:none;height:40px;line-height:40px;\" id=\"id-dlg-buttons\">\r\n");
      out.write("\t\t  <a  style=\"margin-left:20px;\" href=\"javascript:void(0);\" class=\"btn btn-primary\" onclick='getTracywindyObject(\"id_table\").operationTable();'><span>确定</span></a> \r\n");
      out.write("\t\t  <a  style=\"margin-left:20px;\" href=\"javascript:void(0);\" class=\"btn btn-primary\" onclick='jQuery(\"#id_detailInfoWindowContainer\").window(\"close\");'><span>取消</span></a>\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
