package org.apache.jsp.WEB_002dINF.jsps.solutions.workflow.forms.rent_005freckon.rent_005fterminate;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.List<java.lang.String> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.List<java.lang.String> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<div class=\"fillTableContainer\"><!-- 分支版本提交测试-->\r\n");
      out.write("   <table class=\"fillTable\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("    <tr>\r\n");
      out.write("        <td class=\"x-panel-table-div-title\">\r\n");
      out.write("        <div class=\"toggle-icon-expanded\" title=\"折叠\" toggleClass=\"tr-contract-plan-terminate\"></div>结算条件\r\n");
      out.write("        </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr class=\"tr-contract-plan-terminate\" >\r\n");
      out.write("\t    <td>\r\n");
      out.write("\t    \t<table class=\"fillTable\" id=\"plan_rent_terminate_form\">\r\n");
      out.write("\t\t    \t<tr class=\"tr-even\" >\r\n");
      out.write("\t\t\t       \t<td >资产所有权</td>\r\n");
      out.write("\t\t\t        <td ><input class=\"td-content-input\" id=\"id_fund_rent_adjust_assetownership\"  name=\"fund_rent_adjust.assetownership\" id=\"assetOwnerShip\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['fund_rent_adjust.assetownership']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" maxlength=\"100\" maxB=\"100\" Require=\"true\" label='资产所有权'><font class=\"required-content\">*</font></td>\r\n");
      out.write("\t\t\t\t\t<td >提前结清比例(百分比)%</td>\r\n");
      out.write("\t\t\t        <td ><input class=\"td-content-input\"  name=\"fund_rent_adjust.advancerate\" id=\"id_advancerate\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope['fund_rent_adjust.advancerate']?100:requestScope['fund_rent_adjust.advancerate']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" datatype=\"Double\" Require=\"true\" label='提前结清比例'  onchange=\"arrangeEndDate()\"><font class=\"required-content\">*</font></td>\r\n");
      out.write("\t\t\t\t\t<td >约定终止日</td>\r\n");
      out.write("\t\t\t\t\t<td ><input class=\"Wdate td-content-input td-content-readonly\"   name=\"fund_rent_adjust.paydayadjust\" id=\"paydayAdjust\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope['fund_rent_adjust.paydayadjust']?'':requestScope['fund_rent_adjust.paydayadjust']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"  dataType=\"Date\"  onclick=\"WdatePicker(this,{readOnly:true})\"  Require=\"true\"  label='约定终止日' onchange=\"arrangeEndDate()\"><font class=\"required-content\">*</font></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t    <tr class=\"tr-odd\" >\r\n");
      out.write("\t\t\t       \t<td >其他应收</td>\r\n");
      out.write("\t\t\t           <td ><input class=\"td-content-input td-content-readonly\"  name=\"fund_rent_adjust.otherin\" id=\"otherIn\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['fund_rent_adjust.otherin']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"  datatype=\"Double\" Require=\"true\" label='其它应收' readonly>\r\n");
      out.write("\t\t\t           </td>\r\n");
      out.write("\t\t\t\t\t<td >其他应退</td>\r\n");
      out.write("\t\t\t           <td ><input class=\"td-content-input td-content-readonly\"  name=\"fund_rent_adjust.otherout\" id=\"otherOut\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['fund_rent_adjust.otherout']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" datatype=\"Double\" Require=\"true\" label='其它应退' readonly></td>\r\n");
      out.write("\t\t\t       \t<td >已到期未支付租金</td>\r\n");
      out.write("\t\t            <td ><input class=\"td-content-input td-content-readonly\"  name=\"fund_rent_adjust.dunrent\" id=\"dunRent\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope['fund_rent_adjust.dunrent']?0:requestScope['fund_rent_adjust.dunrent']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" readonly></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t    <tr class=\"tr-even\" >\r\n");
      out.write("\t\t\t\t\t<td >逾期罚息</td>\r\n");
      out.write("\t\t\t\t\t<td ><input class=\"td-content-input td-content-readonly\"  name=\"fund_rent_adjust.dunpenalty\" id=\"dunPenalty\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope['fund_rent_adjust.dunpenalty']?0:requestScope['fund_rent_adjust.dunpenalty']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"  readonly></td>\r\n");
      out.write("\t\t\t       \t<td >未到期本金</td>\r\n");
      out.write("\t\t\t        <td ><input class=\"td-content-input td-content-readonly\"  name=\"fund_rent_adjust.corpusoverage\" id=\"corpusOverage\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope['fund_rent_adjust.corpusoverage']?0:requestScope['fund_rent_adjust.corpusoverage']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" readonly></td>\r\n");
      out.write("\t\t\t       \t<td >买断本金</td>\r\n");
      out.write("\t\t\t        <td ><input class=\"td-content-input td-content-readonly\"  name=\"fund_rent_adjust.monopolizecorpusfund\" id=\"monopolizecorpusfund\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope['fund_rent_adjust.monopolizecorpusfund']?0:requestScope['fund_rent_adjust.monopolizecorpusfund']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" readonly></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t    <tr class=\"tr-odd\" >\r\n");
      out.write("\t\t\t\t\t<td >违约手续费</td>\r\n");
      out.write("\t\t\t\t\t<td ><input class=\"td-content-input\"  name=\"fund_rent_adjust.handlingcharge\" id=\"handlingCharge\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['fund_rent_adjust.handlingcharge']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" datatype=\"Double\" Require=\"true\" label='违约手续费' onblur=\"contractClaimTotal()\"><font class=\"required-content\">*</font></td>\r\n");
      out.write("\t\t\t       \t<td > 商定罚息</td>\r\n");
      out.write("\t\t\t        <td ><input class=\"td-content-input\"  name=\"fund_rent_adjust.agreedpenalty\" id=\"agreedPenalty\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope['fund_rent_adjust.agreedpenalty']?0:requestScope['fund_rent_adjust.agreedpenalty']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" datatype=\"Double\" Require=\"true\" label='商定罚息' onblur=\"contractClaimTotal()\"><font class=\"required-content\">*</font></td>\r\n");
      out.write("\t\t\t\t\t<td > 商定利息</td>\r\n");
      out.write("\t\t\t\t\t<td ><input class=\"td-content-input\"  name=\"fund_rent_adjust.agreedinterest\" id=\"agreedInterest\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope['fund_rent_adjust.agreedinterest']?0:requestScope['fund_rent_adjust.agreedinterest']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" datatype=\"Double\"  Require=\"true\" label='商定利息'><font class=\"required-content\">*</font></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t    <tr class=\"tr-even\">\r\n");
      out.write("\t\t\t       \t<td >\r\n");
      out.write("\t\t\t\t       \t<input name=\"fund_rent_adjust.adjustsavetype\" id=\"adjustsavetype\"  type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['fund_rent_adjust.adjustsavetype']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t\t\t\t        <input name=\"fund_rent_adjust.adjusttype\" id=\"adjuststype\"  type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['fund_rent_adjust.adjusttype']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t\t\t\t        <input name=\"fund_rent_adjust.contractid\"  type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['fund_rent_adjust.contractid']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"  ><!-- 合同表中的主键Id -->\r\n");
      out.write("\t\t\t\t        <input name=\"fund_rent_adjust.contract\"  type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['fund_rent_adjust.contract']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"  ><!-- 合同表中的合同号 -->\r\n");
      out.write("\t\t\t\t        <input name=\"fund_rent_adjust.docid\"  type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['fund_rent_adjust.docid']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"  >\r\n");
      out.write("\t\t\t\t        <input name=\"fund_rent_adjust.startlist\" id=\"startList\"  type=\"hidden\" dataType=\"PInteger\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['fund_rent_adjust.startlist']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" >\r\n");
      out.write("        \t\t\t\t<input name=\"fund_rent_adjust.adjustlist\" id=\"adjustList\"   type=\"hidden\" dataType=\"PInteger\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['fund_rent_adjust.adjustlist']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("        \t\t\t\t<input name=\"fund_rent_adjust.yearrate\" id=\"adjustYearRate\"  type=\"hidden\" dataType=\"Rate\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['fund_rent_adjust.yearrate']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t\t\t\t        <input type=\"hidden\" id=\"id_json_fund_rent_plan_str\" name=\"json_fund_rent_plan_str\" value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty json_fund_rent_plan_str ? \"[]\" : json_fund_rent_plan_str}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('\'');
      out.write('/');
      out.write('>');
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<input type=\"hidden\" id=\"id_json_fund_cash_flow_str\" name=\"json_fund_cash_flow_str\" value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty json_fund_cash_flow_str ? \"[]\" : json_fund_cash_flow_str }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('\'');
      out.write('/');
      out.write('>');
      out.write("\r\n");
      out.write("\t\t\t\t\t剩余保证金\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td><input class=\"td-content-input td-content-readonly\"  name=\"fund_rent_adjust.deductible\" id=\"deductible\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['fund_rent_adjust.deductible']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" disabled=\"disabled\"></td>\r\n");
      out.write("\t\t\t\t \t<td>本次抵扣保证金</td>\r\n");
      out.write("\t\t\t\t \t<td><input class=\"td-content-input\"  type=\"text\" name=\"fund_rent_adjust.currentcautionmoney\" id=\"currentcautionmoney\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope['fund_rent_adjust.currentcautionmoney']?0:requestScope['fund_rent_adjust.currentcautionmoney']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" onchange=\"contractClaimTotal()\" ></input></td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<tr class=\"tr-odd\">\r\n");
      out.write("\t\t\t\t<td > 合同债权总计</td>\r\n");
      out.write("\t\t\t\t<td ><input class=\"td-content-input td-content-readonly\"  name=\"fund_rent_adjust.contracttotal\" id=\"contractTotal\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['fund_rent_adjust.contracttotal']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" readonly></td>\r\n");
      out.write("\t\t\t    <td class=\"td-content\">\r\n");
      out.write("\t\t        <input style=\"margin-top:2px;margin-bottom:2px;\" id=\"btn_rent_cal_adjust\" class=\"btn btn-primary\" type=\"button\" value=\"结算\" onclick=\"submitTerminate()\"/>\r\n");
      out.write("\t\t\t\t<input style=\"margin-top:2px;margin-bottom:2px;\" id=\"btn_rent_cal_reset\" class=\"btn btn-primary\" type=\"button\" value=\"撤销\" onclick=\"resetTerminate()\"/>\r\n");
      out.write("\t\t        </td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t    </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr class=\"tr-contract-plan-terminate-data\">\r\n");
      out.write("\t\t<td  class=\"td-tabs-container\" style=\"text-indent: 0px;\">\r\n");
      out.write("\t\t\t<div id='id_contract_terminate_tabs_content' style=\"\">\r\n");
      out.write("\t\t\t\t<div title=\"商务条件[结算后]\">\r\n");
      out.write("\t\t\t\t\t<div id=\"id_table_leasing_rent_plan_container\"\tstyle=\"overflow: hidden;\">\r\n");
      out.write("\t\t\t\t\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "fund_rent_plan_frame.jsp", out, false);
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr> \r\n");
      out.write("    </table>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("jQuery(function() {\r\n");
      out.write("\tjQuery(\".toggle-icon-expanded\").click(toggleLeasingOperation);\r\n");
      out.write("\t$(\"#id_contract_terminate_tabs_content\").css(\"width\", (formWidth) + \"px\");\r\n");
      out.write("\t$(\"#id_contract_terminate_tabs_content\").tabs();\r\n");
      out.write("\r\n");
      out.write("\t//4、\t约定终止日默认值为当天，可以手动选择\r\n");
      out.write("\t//alert(new Date().Format(\"yyyy-MM-dd\"));\r\n");
      out.write("\t//var endDate = $(\"input[name='fund_rent_adjust.paydayadjust']\").val( new Date().Format('yyyy-MM-dd') );\r\n");
      out.write("\t//加载页面时，就先根据结算日重新计算下\r\n");
      out.write("\tarrangeEndDate();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("//对Date的扩展，将 Date 转化为指定格式的String   \r\n");
      out.write("//月(M)、日(d)、小时(h)、分(m)、秒(s)、季度(q) 可以用 1-2 个占位符，   \r\n");
      out.write("//年(y)可以用 1-4 个占位符，毫秒(S)只能用 1 个占位符(是 1-3 位的数字)   \r\n");
      out.write("//例子：   \r\n");
      out.write("//(new Date()).Format(\"yyyy-MM-dd hh:mm:ss.S\") ==> 2006-07-02 08:09:04.423   \r\n");
      out.write("//(new Date()).Format(\"yyyy-M-d h:m:s.S\")      ==> 2006-7-2 8:9:4.18   \r\n");
      out.write("Date.prototype.Format = function(fmt)   \r\n");
      out.write("{ //author: meizz   \r\n");
      out.write("var o = {   \r\n");
      out.write(" \"M+\" : this.getMonth()+1,                 //月份   \r\n");
      out.write(" \"d+\" : this.getDate(),                    //日   \r\n");
      out.write(" \"h+\" : this.getHours(),                   //小时   \r\n");
      out.write(" \"m+\" : this.getMinutes(),                 //分   \r\n");
      out.write(" \"s+\" : this.getSeconds(),                 //秒   \r\n");
      out.write(" \"q+\" : Math.floor((this.getMonth()+3)/3), //季度   \r\n");
      out.write(" \"S\"  : this.getMilliseconds()             //毫秒   \r\n");
      out.write("};   \r\n");
      out.write("if(/(y+)/.test(fmt))   \r\n");
      out.write(" fmt=fmt.replace(RegExp.$1, (this.getFullYear()+\"\").substr(4 - RegExp.$1.length));   \r\n");
      out.write("for(var k in o)   \r\n");
      out.write(" \tif(new RegExp(\"(\"+ k +\")\").test(fmt))   \r\n");
      out.write("\tfmt = fmt.replace(RegExp.$1, (RegExp.$1.length==1) ? (o[k]) : ((\"00\"+ o[k]).substr((\"\"+ o[k]).length)));   \r\n");
      out.write("\treturn fmt;   \r\n");
      out.write("}  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("//结算\r\n");
      out.write("function submitTerminate(){\r\n");
      out.write("\tif(checkTerminateData()){\r\n");
      out.write("\t\t//重新计算合同债权总计\r\n");
      out.write("\t\tcontractClaimTotal();\r\n");
      out.write("\t\tjQuery(\"#adjustsavetype\").val(\"terminate\");\r\n");
      out.write("\t\tterminateCalculateSubmit(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/leasing/adjustCalculateOld.action\");\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function resetTerminate(){\r\n");
      out.write("\tif(confirm(\"你确定要清除调整吗?\")){\r\n");
      out.write("\t\tjQuery(\"#adjustsavetype\").val(\"reset\");\r\n");
      out.write("\t\tterminateCalculateSubmit(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/leasing/resetAdjust.action\");\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function terminateCalculateSubmit(todoAction)\r\n");
      out.write("{\r\n");
      out.write("    //条件通过提交表单\r\n");
      out.write("    jQuery(\"#id_workflowAdviseContainer\").css(\"overflow\",\"hidden\");\r\n");
      out.write("    jQuery(\"#id_workflowFormContainer\").css(\"overflow\",\"hidden\");\r\n");
      out.write("    if(!loadMask)\r\n");
      out.write("    {\r\n");
      out.write("    \tloadMask = new tracywindyLoadMask(document.body,\"数据处理中，请稍等...\");\r\n");
      out.write("    }\r\n");
      out.write("    loadMask.show();\r\n");
      out.write("    window.top.document.body.style.overflow=\"hidden\";\r\n");
      out.write("    var $submitConditionForm = $(\"#plan_rent_terminate_form\");\r\n");
      out.write("    var url = todoAction;\r\n");
      out.write("    var params = $submitConditionForm.tracywindySerializeFormToJsonObject(true,true);\r\n");
      out.write("    ajaxRequest({\r\n");
      out.write("    \t method:'POST',\r\n");
      out.write("         url:url,\r\n");
      out.write("         params:params,\r\n");
      out.write("         failure:function(res){\r\n");
      out.write("    \t\tjQuery(\"#id_workflowAdviseContainer\").css(\"overflow\",\"auto\");\r\n");
      out.write("       \t\tjQuery(\"#id_workflowFormContainer\").css(\"overflow\",\"auto\");\r\n");
      out.write("   \t \t\tloadMask.hide();\r\n");
      out.write("        \talert(\"访问服务器进行测算失败[服务器正忙,或者无法连通,或者服务器出现异常]!\");\r\n");
      out.write("         },\r\n");
      out.write("         success:function(res){\r\n");
      out.write("        \tchenckCondiotn=true;\r\n");
      out.write(" \t   \t\tres=res.responseText;\r\n");
      out.write(" \t   \t\tres=res.replace(/(^\\s+)|(\\s+$)/g, \"\"); \r\n");
      out.write("     \t    if(res!=''){\r\n");
      out.write("     \t    \tajaxTerminateRentCalculateCallBack(res);\r\n");
      out.write("     \t    }else{\r\n");
      out.write("     \t    \tjQuery(\"#id_workflowAdviseContainer\").css(\"overflow\",\"auto\");\r\n");
      out.write("           \t\tjQuery(\"#id_workflowFormContainer\").css(\"overflow\",\"auto\");\r\n");
      out.write("       \t \t\tloadMask.hide();\r\n");
      out.write("     \t    \talert(\"请求测算成功,但无结果返回,请重新尝试!\");\r\n");
      out.write("     \t    }\r\n");
      out.write("         }\r\n");
      out.write("    });\r\n");
      out.write("\treturn false;\r\n");
      out.write("}\r\n");
      out.write("//约定终止日事件\r\n");
      out.write("function arrangeEndDate(){\r\n");
      out.write("\tvar contractId = $(\"input[name='contract_info.id']\").val();\r\n");
      out.write("\tvar endDate = $(\"input[name='fund_rent_adjust.paydayadjust']\").val();\r\n");
      out.write("\tvar advancerate = $(\"input[name='fund_rent_adjust.advancerate']\").val();\r\n");
      out.write("    var url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/leasing/contractMidwayEnd.action\";\r\n");
      out.write("    var params = {contract_id:contractId,end_date:endDate,advancerate:advancerate};\r\n");
      out.write("    ajaxRequest({\r\n");
      out.write("    \t method:'POST',\r\n");
      out.write("         url:url,\r\n");
      out.write("         params:params,\r\n");
      out.write("         failure:function(res){\r\n");
      out.write("        \talert(\"访问服务器进行测算已到期租金、未到期本金、逾期罚息失败!\");\r\n");
      out.write("         },\r\n");
      out.write("         success:function(res){\r\n");
      out.write(" \t   \t\tres=res.responseText;\r\n");
      out.write(" \t   \t\tres=res.replace(/(^\\s+)|(\\s+$)/g, \"\"); \r\n");
      out.write("     \t    if(res!=''){\r\n");
      out.write("     \t    \tvar rs=JsonUtil.decode(res);\r\n");
      out.write("     \t    \t$(\"input[name='fund_rent_adjust.dunrent']\").val(decimal(rs['arrangerentfund'],2));//已到期未支付租金\r\n");
      out.write("     \t    \t$(\"input[name='fund_rent_adjust.corpusoverage']\").val(decimal(rs['noarrangecorpusfund'],2));//未到期本金\r\n");
      out.write("     \t    \t$(\"input[name='fund_rent_adjust.monopolizecorpusfund']\").val(decimal(rs['monopolizecorpusfund'],2));//买断本金\r\n");
      out.write("     \t    \t$(\"input[name='fund_rent_adjust.dunpenalty']\").val(decimal(rs['penaltyoverage'],2));//逾期罚息\r\n");
      out.write("     \t    \t$(\"input[name='fund_rent_adjust.handlingcharge']\").val(decimal(rs['handlingcharge'],2));//违约手续费\r\n");
      out.write("     \t    \t$(\"input[name='fund_rent_adjust.currentcautionmoney']\").val(decimal(rs['incomecharge'],2));//本次抵扣保证金\r\n");
      out.write("     \t    \t\r\n");
      out.write("     \t    \t$(\"input[name='fund_rent_adjust.otherin']\").val(decimal(rs['otherin'],2));//其它应收\r\n");
      out.write("     \t    \t$(\"input[name='fund_rent_adjust.otherout']\").val(decimal(rs['otherout'],2));//其它应退\r\n");
      out.write("     \t    \t//商定罚息默认 = 逾期罚息\r\n");
      out.write("     \t    \t$(\"input[name='fund_rent_adjust.agreedpenalty']\").val(decimal(rs['penaltyoverage'],2));\r\n");
      out.write("     \t    \t\r\n");
      out.write("\t\t\t\t//合同债权统计计算\r\n");
      out.write("     \t    \tcontractClaimTotal();\r\n");
      out.write("     \t    }else{\r\n");
      out.write("     \t    \t$(\"input[name='fund_rent_adjust.dunrent']\").val('0');\r\n");
      out.write("     \t    \t$(\"input[name='fund_rent_adjust.corpusoverage']\").val('0');\r\n");
      out.write("     \t    \t$(\"input[name='fund_rent_adjust.monopolizecorpusfund']\").val('0');\r\n");
      out.write("     \t    \t$(\"input[name='fund_rent_adjust.dunpenalty']\").val('0');\r\n");
      out.write("     \t    \t$(\"input[name='fund_rent_adjust.handlingcharge']\").val('0');//违约手续费\r\n");
      out.write("     \t    \t$(\"input[name='fund_rent_adjust.currentcautionmoney']\").val('0');//本次抵扣保证金\r\n");
      out.write("     \t    \t$(\"input[name='fund_rent_adjust.otherin']\").val('0');//其它应收\r\n");
      out.write("     \t    \t$(\"input[name='fund_rent_adjust.otherout']\").val('0');//其它应退\r\n");
      out.write("     \t    \talert(\"请求测算已到期租金、未到期本金、逾期罚息成功,但无结果返回,请重新尝试!\");\r\n");
      out.write("     \t    }\r\n");
      out.write("         }\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("function ajaxTerminateRentCalculateCallBack(returnResult){\r\n");
      out.write("\t jQuery(\"#id_workflowAdviseContainer\").css(\"overflow\",\"auto\");\r\n");
      out.write("\t jQuery(\"#id_workflowFormContainer\").css(\"overflow\",\"auto\");\r\n");
      out.write("\t loadMask.hide();\r\n");
      out.write("\t var rs=JsonUtil.decode(returnResult);\r\n");
      out.write("\t if(rs['rentcalculaters']==\"yes\"){\r\n");
      out.write("\t  \t var fundRentPlan = getTracywindyObject('table_id_table_leasing_rent_plan_container');\r\n");
      out.write("\t  \t fundRentPlan.tableData = rs['fundrentplan'];\r\n");
      out.write("\t\t//保存多行控件的值\r\n");
      out.write("\t  \t jQuery('#id_json_finance_rent_plan_str').val(JsonUtil.encode(rs['finarentplan'])) ;\r\n");
      out.write("\t  \t jQuery('#id_json_fund_cash_flow_str').val(JsonUtil.encode(rs['fundcashdetail'])) ;\r\n");
      out.write("\t  \t jQuery('#id_json_finance_cash_flow_str').val(JsonUtil.encode(rs['finacashdetail'])) ;\r\n");
      out.write("\t\t jQuery('#id_json_fund_rent_plan_str').val(JsonUtil.encode(rs['fundrentplan']));\r\n");
      out.write("\t\t fundRentPlan.reload();\r\n");
      out.write("\t }\r\n");
      out.write("     alert(rs['rentcalculatemsg']);\r\n");
      out.write("}\r\n");
      out.write("function checkTerminateData(){\r\n");
      out.write("\tvar submitForm =document.getElementById(\"plan_rent_terminate_form\");\r\n");
      out.write("\tvar isPassed = Validator.Validate(submitForm,1,false);\r\n");
      out.write("\tif(isPassed){\r\n");
      out.write("\t\tvar paydayAdjust=jQuery(\"#paydayAdjust\").val();\r\n");
      out.write("\t\tvar planData=getTracywindyObject('multiTable_id_table_leasing_rent_plan_container').datas;\r\n");
      out.write("\t\tif(paydayAdjust!=''){\r\n");
      out.write("\t\t\tvar nowDate='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope[\"fund_rent_adjust.nowdate\"]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("\t\t\tvar nowDiff=datediff('day',nowDate,paydayAdjust);\r\n");
      out.write("\t\t\t//if(nowDiff*1>0){\r\n");
      out.write("\t\t\t//\talert(\"约定终止日不能小于今天!\");\r\n");
      out.write("\t\t\t//\treturn false;\r\n");
      out.write("\t\t\t//}else{\r\n");
      out.write("\t\t\t\tvar startList=-1;\r\n");
      out.write("\t\t\t\tfor(var index=0;planData.length;index++){\r\n");
      out.write("\t\t\t\t\tvar pd=planData[index];\r\n");
      out.write("\t\t\t\t\tvar beforeDate=pd[\"plandate\"];\r\n");
      out.write("\t\t\t\t\tnowDiff=datediff('day',beforeDate,paydayAdjust);\r\n");
      out.write("\t\t\t\t\tif(nowDiff*1>=0){\r\n");
      out.write("\t\t\t\t\t\tstartList=(pd[\"rentlist\"]-1);\r\n");
      out.write("\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tif(startList>0){\r\n");
      out.write("\t\t\t\t//\tif(planData[startList][\"planstatusid\"].toLowerCase()!='planmanystatusno'){\r\n");
      out.write("\t\t\t\t//\t\talert(\"只能从[未收款]期项开始!\");\r\n");
      out.write("\t\t\t\t//\t\treturn false;\r\n");
      out.write("\t\t\t\t//\t}else{\r\n");
      out.write("\t\t\t\t\t\tjQuery(\"#startList\").val(startList+1);\r\n");
      out.write("\t\t\t\t\t\tjQuery(\"#adjustList\").val(startList+1);\r\n");
      out.write("\t\t\t\t\t\tjQuery(\"#adjustYearRate\").val(decimal(planData[startList][\"yearrate\"],6));\r\n");
      out.write("\t\t\t\t//\t}\r\n");
      out.write("\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\tif(confirm(\"约定终止日可能不在租赁期限之内，您确定要继续吗？\")){\r\n");
      out.write("\t\t\t\t\t\tjQuery(\"#startList\").val(planData.length);\r\n");
      out.write("\t\t\t\t\t\tjQuery(\"#adjustList\").val(planData.length);\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t//}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("\treturn false;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("//合同债权总计 = 其他应收 — 其他应退 + 已到期未支付租金+ 买断本金 + 违约手续费 + 商定罚息 + 商定利息 — 本次抵扣保证金\r\n");
      out.write("function contractClaimTotal(){// + 逾期罚息 + parseFloat(dunpenalty)这个去掉\r\n");
      out.write("\tvar otherin = $(\"input[name='fund_rent_adjust.otherin']\").val();//其它应收\r\n");
      out.write("\tvar otherout = $(\"input[name='fund_rent_adjust.otherout']\").val();//其它应退\r\n");
      out.write("\tvar dunrent = $(\"input[name='fund_rent_adjust.dunrent']\").val();//已到期未支付租金\r\n");
      out.write("\tvar dunpenalty = $(\"input[name='fund_rent_adjust.dunpenalty']\").val()==\"\" ? \"0\":$(\"input[name='fund_rent_adjust.dunpenalty']\").val();//逾期罚息\r\n");
      out.write("\tvar corpusoverage = $(\"input[name='fund_rent_adjust.monopolizecorpusfund']\").val()==\"\" ? \"0\":$(\"input[name='fund_rent_adjust.monopolizecorpusfund']\").val();//买断本金\r\n");
      out.write("\tvar handlingcharge = $(\"input[name='fund_rent_adjust.handlingcharge']\").val()==\"\" ? \"0\":$(\"input[name='fund_rent_adjust.handlingcharge']\").val();//违约手续费\r\n");
      out.write("\tvar agreedpenalty = $(\"input[name='fund_rent_adjust.agreedpenalty']\").val()==\"\" ? \"0\":$(\"input[name='fund_rent_adjust.agreedpenalty']\").val();//商定罚息\r\n");
      out.write("\tvar agreedinterest = $(\"input[name='fund_rent_adjust.agreedinterest']\").val()==\"\" ? \"0\":$(\"input[name='fund_rent_adjust.agreedinterest']\").val();//商定利息\r\n");
      out.write("\tvar currentcautionmoney = $(\"input[name='fund_rent_adjust.currentcautionmoney']\").val()==\"\" ? \"0\":$(\"input[name='fund_rent_adjust.currentcautionmoney']\").val();//本次抵扣保证金\r\n");
      out.write("\t   \r\n");
      out.write("\tvar agreedpenalty = $(\"input[name='fund_rent_adjust.agreedpenalty']\").val()==\"\" ? \"0\":$(\"input[name='fund_rent_adjust.agreedpenalty']\").val();//提前结清比例\r\n");
      out.write("\tif(!isNaN(handlingcharge) && !isNaN(agreedpenalty)){\r\n");
      out.write("\t\t//其他应收 — 其他应退 + 已到期未支付租金  + 未到期本金 + 违约手续费 + 商定罚息 + 商定利息 — 本次抵扣保证金\r\n");
      out.write("\t\tvar contracttotal = parseFloat(otherin) - parseFloat(otherout) + parseFloat(dunrent)  + parseFloat(corpusoverage) + parseFloat(handlingcharge)+ parseFloat(agreedpenalty)+ parseFloat(agreedinterest) - parseFloat(currentcautionmoney);\r\n");
      out.write("\t\t$(\"input[name='fund_rent_adjust.contracttotal']\").val(decimal(contracttotal,2));\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\talert(\"违约手续费或商定罚息必须为数字\");\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
