package org.apache.jsp.WEB_002dINF.jsps.solutions.leasing.fund_005fbankcardload;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kernal.utils.FileUtil;
import com.kernal.utils.WebUtil;

public final class bankcardload_005finfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.List<java.lang.String> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.List<java.lang.String> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>租赁业务  - 卡扣上传</title>\r\n");
      out.write("    <!--css sheet-->\r\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/dtree/dtree.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/jquery-easyui/easyui.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/jquery-easyui/icon.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/tracywindy/tracywindy.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/tracywindy/button.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/tracywindy/workFlowUtil.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t<!--javascript libray-->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/workFlowUtil.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyUtils.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyJsonUtil.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyAjax.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery/jquery.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery/jquery.easyui.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyLoadMask.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyTable.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyComboBox.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindySerializeFormToJsonObject.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/my97DatePicker/WdatePicker.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/validator.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyOperationTable.js\"></script>\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t   html,body{\r\n");
      out.write("\t     overflow:hidden;\r\n");
      out.write("\t   }\r\n");
      out.write("\t</style>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("   function downloadFile(Id)\r\n");
      out.write("   {\r\n");
      out.write("     attachmentDown({url:\"/leasing/template/downLoadAttachById.action\",id:Id,returnType:'file'});\r\n");
      out.write("    } \r\n");
      out.write("    function showOperator(value,tableObj,columnName,columnIndex,rowData){\r\n");
      out.write("       var base = \"<a href='#' onclick='downloadFile(\\\"\"+rowData.id+\"\\\")'>\"+rowData.filename+\"</a>\";\r\n");
      out.write("       return base;\r\n");
      out.write("    }\r\n");
      out.write("    function importEbankCallBack(message){\r\n");
      out.write("        alert(\"'\"+message+\"'\");\r\n");
      out.write("    \twindow.currentImportExcelLoadMask.hide();\r\n");
      out.write("    \tvar table = getTracywindyObject(\"id_table\");\r\n");
      out.write("    \ttable.reload();\r\n");
      out.write("    }\r\n");
      out.write("    var constantFlagTable = \"User\";\r\n");
      out.write("    var ebankUploadUrl=\"\";\r\n");
      out.write("    var ebankAttachUrl=\"\";\r\n");
      out.write("\tvar pageWidth  = document.documentElement.clientWidth-2;\r\n");
      out.write("\tvar pageHeight = document.documentElement.clientHeight-2;\r\n");
      out.write("\t//普通的卡扣上传列\r\n");
      out.write("\tvar importcolumn= [\r\n");
      out.write("\t\t            {header:'合同号',mapping:'contractid'},\r\n");
      out.write("\t\t            {header:'租金金额',mapping:'incomemoney'}\r\n");
      out.write("\t  \t        ];\r\n");
      out.write("    //农行卡扣上传\r\n");
      out.write("    var agricultureColumn= [    \r\n");
      out.write("                    {header:'serialno',mapping:'incomenum'},          \r\n");
      out.write("                    {header:'enddate',mapping:'incomedate'},          \r\n");
      out.write("\t\t            {header:'actualdebitamt',mapping:'incomemoney'},\r\n");
      out.write("\t\t            {header:'resultdesc',mapping:'incometext'},\r\n");
      out.write("\t\t            {header:'payeeaccountno',mapping:'clientaccount'},\r\n");
      out.write("\t\t            {header:'payeename',mapping:'cilentname'},\r\n");
      out.write("\t\t            {header:'routecenter',mapping:'tradepurpose'}\r\n");
      out.write("\t\t            /* ,\r\n");
      out.write("\t\t            {header:'失败原因',mapping:'返回信息'} */\r\n");
      out.write("\t  \t        ];\r\n");
      out.write("    //建行卡扣上传\r\n");
      out.write("    var ConstructionColumn= [    \r\n");
      out.write("                    //{header:'账户明细编号-交易流水号',mapping:'incomenum'},          \r\n");
      out.write("                    //{header:'交易时间',mapping:'incomedate'},          \r\n");
      out.write("\r\n");
      out.write("\t\t            {header:'付款人姓名',mapping:'cilentname'},\r\n");
      out.write("\t\t            {header:'付款账号',mapping:'clientaccount'},\r\n");
      out.write("\t\t            {header:'金 额',mapping:'incomemoney'},\r\n");
      out.write("\t\t            {header:'交易结果',mapping:'incometext'},\r\n");
      out.write("\t\t            {header:'摘要',mapping:'tradepurpose'},\r\n");
      out.write("\t\t            {header:'失败原因',mapping:'remark'}\r\n");
      out.write("\t  \t        ];  \r\n");
      out.write("    //通用卡扣上传\r\n");
      out.write("    var CommonColumn= [    \r\n");
      out.write("                    {header:'编号',mapping:'incomenum'},          \r\n");
      out.write("                    {header:'交易时间',mapping:'incomedate'},          \r\n");
      out.write("\t\t            {header:'交易金额',mapping:'incomemoney'},\r\n");
      out.write("\t\t            {header:'交易状态',mapping:'tradingresults'},\r\n");
      out.write("\t\t            {header:'对方账号',mapping:'clientaccount'},\r\n");
      out.write("\t\t            {header:'对方户名',mapping:'cilentname'},\r\n");
      out.write("\t\t            {header:'备注',mapping:'tradepurpose'}\r\n");
      out.write("\t  \t        ];  \r\n");
      out.write("\tjQuery(function(){\r\n");
      out.write("   \t var tableebank = new tracywindyOperationTable({\r\n");
      out.write("\r\n");
      out.write("   \t\tresetFormCallback:function(table,$form,operFlag){\r\n");
      out.write("   \t\t if(\"add\" == operFlag){\r\n");
      out.write("   \t\t\tvar rowData = table.getRowDataAt(0);\r\n");
      out.write("   \t   \t\t //document.getElementById(\"custname\").value=rowData[\"custname\"];\r\n");
      out.write("   \t\t\t//$(\"#custname\").val(rowData[\"custname\"]);\r\n");
      out.write("   \t     }\r\n");
      out.write("     \t },\r\n");
      out.write("   \t\t loadFormDataCallBack:function(table,$form,rowIndex){\r\n");
      out.write(" \r\n");
      out.write("        },\r\n");
      out.write("   \t\t tableComment:'[卡扣回笼上传]',\r\n");
      out.write("   \t\t constantFlagTable:'fundebank',\r\n");
      out.write("   \t\t windowTop:20,\r\n");
      out.write("   \t     border:true,\r\n");
      out.write("         renderTo:'id_tableContainer',\r\n");
      out.write("         title:'卡扣回笼上传',\r\n");
      out.write("         width:parseInt(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.tableWidth}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\")||pageWidth,\r\n");
      out.write("         height:parseInt(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.tableHeight}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\")||pageHeight,\r\n");
      out.write("         id:'id_table',\r\n");
      out.write("         xmlFileName:'/eleasing/jsp/fund_bankcarddown/bankcardupload.xml',\r\n");
      out.write("         loadMode:'ajax',\r\n");
      out.write("         isPage:true,\r\n");
      out.write("         isFit:true,\r\n");
      out.write("         isRemoteSortable : false,\r\n");
      out.write("         operButtons:' ',\r\n");
      out.write("       /*   params : {\r\n");
      out.write("        \tisexport : ' ' \r\n");
      out.write("         }, */\r\n");
      out.write("         tools:[{\r\n");
      out.write("        \t    iconCls:'icon-cancel',\r\n");
      out.write("        \t    html:'<font color=\"red\">删除</font>',\r\n");
      out.write("        \t    handler:function(table)\r\n");
      out.write("        \t    { \r\n");
      out.write("        \t    \tvar row = table.getCheckedRowDatas();\r\n");
      out.write("        \t\t    if( row[0]['exp'] == '0' )\r\n");
      out.write("        \t\t    {\r\n");
      out.write("            \t    \tparam = {};\r\n");
      out.write("            \t    \tparam.b_id = row[0]['id'];\r\n");
      out.write("            \t\t\t$.ajax({\r\n");
      out.write("            \t\t\t\ttype : \"post\",\r\n");
      out.write("            \t\t\t\turl : getRootPath()+\"/acl/deleteUploadCardHire.acl\",\r\n");
      out.write("            \t\t\t\tcache : false,\r\n");
      out.write("            \t\t\t\tasync : false,\r\n");
      out.write("            \t\t\t\tdata : param,\r\n");
      out.write("            \t\t\t\tsuccess : function( rs ) \r\n");
      out.write("            \t\t\t\t{\r\n");
      out.write("            \t\t\t\t   var svote = rs;\r\n");
      out.write("            \t\t\t\t   svote = svote.replace(/(^\\s+)|(\\s+$)/g, \"\"); \r\n");
      out.write("            \t\t\t\t\tif (svote!=\"\") \r\n");
      out.write("            \t\t\t\t\t{\r\n");
      out.write("            \t\t\t\t\t\tif ( svote == \"yes\"){\r\n");
      out.write("           \t\t\t\t\t\t\t   alert( \"删除成功!\" );\r\n");
      out.write("            \t\t\t\t\t\t   table.reload();\r\n");
      out.write("            \t\t\t\t\t\t}\r\n");
      out.write("            \t\t\t\t\t\telse\r\n");
      out.write("           \t\t\t\t\t\t\t{\r\n");
      out.write("           \t\t\t\t\t\t   \t   alert(\"删除失败!\");\r\n");
      out.write("            \t\t\t\t\t\t   table.reload();\r\n");
      out.write("           \t\t\t\t\t\t\t}\r\n");
      out.write("            \t\t\t\t\t}\r\n");
      out.write("            \t\t\t\t}\r\n");
      out.write("            \t\t\t});\r\n");
      out.write("            \t    \t\r\n");
      out.write("        \t    \t}\r\n");
      out.write("        \t\t    else alert( \"[不允许操作]该数据已经核销,或者正在核销... \" ); \r\n");
      out.write("                }\r\n");
      out.write("        \t },\r\n");
      out.write("                {\r\n");
      out.write("        \t    iconCls:'icon-import',\r\n");
      out.write("        \t    html:'<font color=\"red\">农行卡扣上传</font>',\r\n");
      out.write("        \t    handler:function(table){ \r\n");
      out.write("        \t    \tvar canStrat = true;\r\n");
      out.write("        \t    \tvar data = table.getRowsData();\r\n");
      out.write("        \t    \tfor(var i = 0; i < data.length; i++ ){\r\n");
      out.write("        \t    \t\tif(data[i]['exp'] != '2'){\r\n");
      out.write("        \t    \t\t\tcanStrat = false;\r\n");
      out.write("        \t    \t\t\tbreak;\r\n");
      out.write("        \t    \t\t}\r\n");
      out.write("        \t    \t}\r\n");
      out.write("        \t     \tif(canStrat){\r\n");
      out.write("\t        \t    \tattachmentUp({url:\"/leasing/template/uploadExcelToDatabase.action\",modelname:'cardupload', filefirstkey : 'card_hire_bank_agricultural', title:'农行卡扣上传','成功':'0','失败':'1',headerIndex:'1',dataIndex:'2',targetClass:'com.business.entity.contract.rent.ContractCardRentIncome',title:'农行卡扣上传',custoperatorMethod:'initCardHire',parames:agricultureColumn});\r\n");
      out.write("        \t    \t} else {\r\n");
      out.write("        \t    \t\talert(\"还有未核销完成的卡扣数据,请核销完成后再上传\");\r\n");
      out.write("        \t    \t}\r\n");
      out.write("        \t    \t\r\n");
      out.write("               }\r\n");
      out.write("        \t },\r\n");
      out.write("        \t {\r\n");
      out.write("         \t    iconCls:'icon-import',\r\n");
      out.write("         \t    html:'<font color=\"red\">建行卡扣上传</font>',\r\n");
      out.write("         \t    handler:function(table){ \r\n");
      out.write("\t         \t   \tvar canStrat = true;\r\n");
      out.write("\t    \t    \tvar data = table.getRowsData();\r\n");
      out.write("\t    \t    \tfor(var i = 0; i < data.length; i++ ){\r\n");
      out.write("\t    \t    \t\tif(data[i]['exp'] != '2'){\r\n");
      out.write("\t    \t    \t\t\tcanStrat = false;\r\n");
      out.write("\t    \t    \t\t\tbreak;\r\n");
      out.write("\t    \t    \t\t}\r\n");
      out.write("\t    \t    \t}\r\n");
      out.write("\t    \t     \tif(canStrat){\r\n");
      out.write("         \t    \t\tattachmentUp({url:\"/leasing/template/uploadExcelToDatabase.action\",modelname:'cardupload',filefirstkey : 'card_hire_bank_construction', title:'建行卡扣上传','成功':'0','失败':'1',headerIndex:'3',dataIndex:'4',targetClass:'com.business.entity.contract.rent.ContractCardRentIncome',custoperatorMethod:'initCardHire',parames:ConstructionColumn});\r\n");
      out.write("\t    \t    \t} else {\r\n");
      out.write("\t    \t    \t\talert(\"还有未核销完成的卡扣数据,请核销完成后再上传\");\r\n");
      out.write("\t    \t    \t}\r\n");
      out.write("                }\r\n");
      out.write("         \t },\r\n");
      out.write("        \t {\r\n");
      out.write("          \t    iconCls:'icon-import',\r\n");
      out.write("          \t    html:'<font color=\"red\">通用卡扣上传</font>',\r\n");
      out.write("          \t    handler:function(table){ \r\n");
      out.write("\t         \t   \tvar canStrat = true;\r\n");
      out.write("\t    \t    \tvar data = table.getRowsData();\r\n");
      out.write("\t    \t    \tfor(var i = 0; i < data.length; i++ ){\r\n");
      out.write("\t    \t    \t\tif(data[i]['exp'] != '2'){\r\n");
      out.write("\t    \t    \t\t\tcanStrat = false;\r\n");
      out.write("\t    \t    \t\t\tbreak;\r\n");
      out.write("\t    \t    \t\t}\r\n");
      out.write("\t    \t    \t}\r\n");
      out.write("\t    \t     \tif(canStrat){\r\n");
      out.write("\t          \t    \tattachmentUp({url:\"/leasing/template/uploadExcelToDatabase.action\",modelname:'cardupload',title:'通用卡扣上传','成功':'0','失败':'1',headerIndex:'1',dataIndex:'2',targetClass:'com.business.entity.contract.rent.ContractCardRentIncome',custoperatorMethod:'',parames:CommonColumn});\r\n");
      out.write("\t    \t    \t} else {\r\n");
      out.write("\t    \t    \t\talert(\"还有未核销完成的卡扣数据,请核销完成后再上传\");\r\n");
      out.write("\t                 }\r\n");
      out.write("          \t  \t}\r\n");
      out.write("          \t },\r\n");
      out.write("        \t {\r\n");
      out.write("         \t    iconCls:'icon-import',\r\n");
      out.write("         \t    html:'<font color=\"red\">卡扣核销</font>',\r\n");
      out.write("         \t    handler:function(table){ \r\n");
      out.write("        \t\t    var row = table.getCheckedRowDatas();\r\n");
      out.write("         \t    \t//console.info(row);\r\n");
      out.write("        \t\t    if(row.length==0 || row.length > 1){\r\n");
      out.write("            \t    \talert(\"请选择需要核销的上传数据!\");\r\n");
      out.write("        \t    \t}else  if(row[0]['exp'] == '2'){\r\n");
      out.write("        \t\t    \talert(\"该数据已经核销过，不能再次核销\");\r\n");
      out.write("        \t\t    } else {\r\n");
      out.write("        \t    \t\tstartProcess(\"租金批量核销(卡扣)-1\",\"&fileid=\"+row[0].id);\r\n");
      out.write("        \t    \t}\r\n");
      out.write("         \t   }\r\n");
      out.write("         \t }\r\n");
      out.write("    \t ],\r\n");
      out.write("         columns:[\r\n");
      out.write("                    {header:'id',name:'id',hidden:true},\r\n");
      out.write("\t\t            {header:'文件名',name:'filename',renderer:showOperator},\r\n");
      out.write("\t\t            {header:'上传人',name:'username'},\r\n");
      out.write("\t\t            {header:'上传时间',name:'createdate'},\r\n");
      out.write("\t\t            {header:'核销状态',name:'exp',renderer:function(value,tableObj,columnName,columnIndex,rowData){\r\n");
      out.write("\t\t \t    \t\r\n");
      out.write("\t\t\t\t\tvar text = \"\";\r\n");
      out.write("\t\t\t\t\tif (rowData.exp) {\r\n");
      out.write("\t\t\t\t\t\tvar key = rowData.exp;\r\n");
      out.write("\t\t\t\t\t\tswitch (key) {\r\n");
      out.write("\t\t\t\t\t\tcase '0':\r\n");
      out.write("\t\t\t\t\t\t\ttext = \"<span>未核销</span>\";\r\n");
      out.write("\t\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\tcase '1':\r\n");
      out.write("\t\t\t\t\t\t\ttext = \"<span>正在核销</span>\";\r\n");
      out.write("\t\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\tcase '2':\r\n");
      out.write("\t\t\t\t\t\t\ttext = \"<span>已核销</span>\";\r\n");
      out.write("\t\t\t\t\t\t\tbreak;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\tdefault:\r\n");
      out.write("\t\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\treturn text;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}]\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"id_tableContainer\"></div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
