package org.apache.jsp.WEB_002dINF.jsps.solutions.workflow.forms.contract.contract_005fapproval;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class contract_005fbase_005finfo_005ffor3_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.List<java.lang.String> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.List<java.lang.String> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("   \r\n");
      out.write("    <!-- 隐藏域 -->\r\n");
      out.write("    <input name=\"contract_info.id\" id=\"contract_info.id\" type=\"hidden\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['contract_info.id'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/>\r\n");
      out.write("    <input name=\"project_info.id\" id=\"project_info.id\" type=\"hidden\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['project_info.id'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/>\r\n");
      out.write("    <input name=\"contract_info.contractid\" id=\"contract_info.id\" type=\"hidden\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['contract_info.contractid'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/>\r\n");
      out.write("    <input name=\"contract_info.custid\" id=\"contract_info.custid\" type=\"hidden\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['contract_info.custid'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/>\r\n");
      out.write("    <input name=\"contract_info.startdate\" id=\"contract_info.startdate\" type=\"hidden\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['contract_info.startdate'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/>\r\n");
      out.write("    <input name=\"contract_info.enddate\" id=\"contract_info.enddate\" type=\"hidden\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['contract_info.enddate'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/>\r\n");
      out.write("    <input name=\"contract_info.contractstatus\" id=\"contract_info.contractstatus\" type=\"hidden\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['contract_info.contractstatus'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/>\r\n");
      out.write("    <input name=\"contract_info.custdealer\" id=\"contract_info.custdealer\" type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['contract_info.custdealer'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/>\r\n");
      out.write("    <input name=\"contract_info.custdealername\" id=\"contract_info.custdealername\" type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['contract_info.custdealername'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/>\r\n");
      out.write("    <input name=\"contract_info.projstatus\" id=\"contract_info.projstatus\" type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['contract_info.projstatus'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/>\r\n");
      out.write("    <input name=\"cust_type\" id=\"proj_info.cust_type\" class=\"td-content-input td-content-readonly\" readOnly  type=\"hidden\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['proj_info.cust_type'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"> \r\n");
      out.write("         <table id=\"contract_base_info\" cellspacing=\"0\" cellpadding=\"0\">\r\n");
      out.write("         <tr>\r\n");
      out.write("             <td class=\"x-panel-table-div-title\" colspan=4><div class=\"toggle-icon-expanded\" title=\"折叠\" toggleClass=\"tr-contractect-info\"></div>合同基本信息</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr class=\"tr-contractect-info tr-even\">\r\n");
      out.write("             <td class=\"td-content-title\">项目编号：</td><td class=\"td-content\"><input name=\"contract_info.projid\" id=\"projid\" class=\"td-content-input td-content-readonly\" readOnly type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['contract_info.projid']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"></td>\r\n");
      out.write("             <td class=\"td-content-title\">合同号：</td><td class=\"td-content\"><input name=\"contract_info.contractnumber\" id=\"contractid\" class=\"td-content-input td-content-readonly\" readOnly type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['contract_info.contractnumber']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"  label=\"合同号\" ><font class=\"required-content\">*</font></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("          <tr class=\"tr-contractect-info tr-odd\">\r\n");
      out.write("             <td class=\"td-content-title\">项目名称：</td><td class=\"td-content\" colspan=5><input style=\"width:60%\" name=\"contract_info.projectname\" id=\"contractect_name\" class=\"td-content-input td-content-readonly\" readOnly type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['contract_info.projectname']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"><font class=\"required-content\">*</font></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr class=\"tr-contractect-info tr-even\">   \r\n");
      out.write("             <td class=\"td-content-title\">承租单位：</td><td class=\"td-content\"><input name=\"contract_info.custname\" class=\"td-content-input td-content-readonly\" readOnly require=\"true\" label=\"承租单位\"  type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['contract_info.custname'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" >\r\n");
      out.write("             <font class=\"required-content\">*</font>\r\n");
      out.write("             <a href=\"javascript:void(0);\">\r\n");
      out.write("               <img alt=\"客户信息\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/menuIcons/department.png\" \r\n");
      out.write("               onclick=\"showEwlpCustInfo('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['contract_info.custid'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("')\"/></a>\r\n");
      out.write("             </td>\r\n");
      out.write("             <td class=\"td-content-title\">客户编号：</td><td class=\"td-content\"><input name=\"contract_info.custnumber\" class=\"td-content-input td-content-readonly\" readOnly  type=\"text\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['contract_info.custnumber'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"><font class=\"required-content\">*</font></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("           <tr class=\"tr-contractect-info tr-even\">\r\n");
      out.write("             <td class=\"td-content-title\">活动类型：</td><td class=\"td-content\"><div class=\"leftComboContainer\" id=\"id_contract_type\"></div></td>\r\n");
      out.write("             <td class=\"td-content-title\">经销商合作协议号：</td><td class=\"td-content\">\r\n");
      out.write("             <input name=\"dealear_xiey\" class=\"td-content-input td-content-readonly\" readOnly  type=\"text\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['dealear_xiey'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr class=\"tr-contractect-info tr-even\">  \r\n");
      out.write("             <td class=\"td-content-title\">项目来源：</td><td class=\"td-content\"><div class=\"leftComboContainer\" id=\"id_contract_source\"></div></td>\r\n");
      out.write("             <td class=\"td-content-title\">是否第三方代付：</td><td class=\"td-content\"><div class=\"leftComboContainer\" id=\"id_cust_kind\"></div><font class=\"required-content\">*</font></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("          <tr class=\"tr-contractect-info tr-odd\">   \r\n");
      out.write("             <td class=\"td-content-title\">固定资产分类：</td><td class=\"td-content\"><div class=\"leftComboContainer\" id=\"id_leas_type\"></div></td>\r\n");
      out.write("             <td class=\"td-content-title\">租赁形式：</td><td class=\"td-content\"><div class=\"leftComboContainer\" id=\"id_leas_form\"></div><font class=\"required-content\">*</font></td>\r\n");
      out.write("         </tr>  \r\n");
      out.write("          <tr class=\"tr-contractect-info tr-even\">   \r\n");
      out.write("             <td class=\"td-content-title\">项目出单部门：</td><td class=\"td-content\"><div class=\"leftComboContainer\" id=\"id_contract_dept\"></div><font class=\"required-content\">*</font></td>\r\n");
      out.write("             <td class=\"td-content-title\">录入人员：</td><td class=\"td-content\"><div class=\"leftComboContainer\" id=\"id_contract_registrar\"></div><font class=\"required-content\">*</font></td>\r\n");
      out.write("         </tr>\r\n");
      out.write("          <tr class=\"tr-contractect-info tr-odd\">   \r\n");
      out.write("             <td class=\"td-content-title\">项目经理：</td><td class=\"td-content\" colspan=\"3\"><div class=\"leftComboContainer\" id=\"id_contract_manage\"></div><font class=\"required-content\">*</font></td>\r\n");
      out.write("             ");
      out.write("\r\n");
      out.write("          </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("        <script language=\"javascript\">\t\r\n");
      out.write("\t        function showEwlpCustInfo(cust_id){\r\n");
      out.write("\t\t    \tvar URL = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/leasing/cust_info/cust_info.bi\";\r\n");
      out.write("\t\t    \tvar params = {cust_id:cust_id,read_only:'false'};\r\n");
      out.write("\t\t\t    openFullScreenWindow(URL,params);\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t        jQuery(\"#contract_base_info\").css(\"width\",formWidth+\"px\");\r\n");
      out.write("\t        jQuery(function(){\r\n");
      out.write("\t        \tjQuery(\"#id_loadMaskContainer\").show();\r\n");
      out.write("\t\t\t    //######合同基本信息#########\r\n");
      out.write("\t\t\t\t//dict(divContainerDivId,fieldName,code,defaultValue,defaultRawValue,otherAttributes,width)\r\n");
      out.write("\t\t\t    dict('id_contract_type','contract_info.projtype','proj_type','");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope[\"contract_info.projtype\"]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope[\"rawValue_contract_info.projtype\"]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("');\r\n");
      out.write("\t\t\t    //dict('id_contract_scale','contract_info.projscale','proj_scale','");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope[\"contract_info.projscale\"]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope[\"rawValue_contract_info.projscale\"]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("');\r\n");
      out.write("\t\t\t    dict('id_contract_source','contract_info.projsource','proj_source','");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope[\"contract_info.projsource\"]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope[\"rawValue_contract_info.projsource\"]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("');\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t    isViewHistoryTask = false;\r\n");
      out.write("\t\t\t    dictYesOrNoByCode('id_cust_kind','proj_info.isthirdpay','");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope[\"proj_info.isthirdpay\"] ? \"0\" : requestScope[\"proj_info.isthirdpay\"] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("','',true,' require=\"true\" label=\"是否第三方代付\"');\r\n");
      out.write("\t\t\t    isViewHistoryTask = true;\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t    dict('id_leas_type','contract_info.leastype','leas_type','");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope[\"contract_info.leastype\"]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope[\"rawValue_contract_info.leastype\"]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("');\r\n");
      out.write("\t\t\t    dict('id_leas_form','contract_info.leasform','leas_form','");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope[\"contract_info.leasform\"]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope[\"rawValue_contract_info.leasform\"]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("','require=\"true\" label=\"租赁形式\"');\r\n");
      out.write("\t\t\t    //########公共下拉############\r\n");
      out.write("\t\t\t    new tracywindyComboBox({\r\n");
      out.write("\t\t\t\t\t\tlazyLoad:true,\r\n");
      out.write("\t\t\t\t\t\tid : 'id_combo_creatordept',\r\n");
      out.write("\t\t\t\t\t\twidth : 167,\r\n");
      out.write("\t\t\t\t\t\trenderTo : 'id_contract_dept',\r\n");
      out.write("\t\t\t\t\t\txmlFileName : '\\\\eleasing\\\\workflow\\\\public\\\\department_combox.xml',\r\n");
      out.write("\t\t\t\t\t\tloadMode : 'ajax',\r\n");
      out.write("\t\t\t\t\t\treadOnly : false,\r\n");
      out.write("\t\t\t\t\t\tisAjaxLenovo : true,\r\n");
      out.write("\t\t\t\t\t\totherAttributes:'require=\"true\"  label=\"项目出单部门\"',\r\n");
      out.write("\t\t\t\t\t\ttopAdd : 0,\r\n");
      out.write("\t\t\t\t\t\tleftAdd : 0,\r\n");
      out.write("\t\t\t\t\t\tpositionDropIconLeftAdd : -1,\r\n");
      out.write("\t\t\t\t\t\tname : 'contract_info.projdept',\r\n");
      out.write("\t\t\t\t\t\tdisplayField : 'name',\r\n");
      out.write("\t\t\t\t\t\tvalueField : 'id',\r\n");
      out.write("\t\t\t\t\t\tvalue:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope['contract_info.projdept'] ? sessionScope['loginUserDeptObj'].id : requestScope['contract_info.projdept'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\",\r\n");
      out.write("\t\t\t\t\t\trawValue:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope['contract_info.projdept'] ? sessionScope['loginUserDeptObj'].name : requestScope['rawValue_contract_info.projdept'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\",\r\n");
      out.write("\t\t\t\t\t\tparams : {\r\n");
      out.write("\t\t\t\t\t\t\tdealer_id:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope['currentDealerCustInfoId']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t        new tracywindyComboBox({\r\n");
      out.write("\t\t\t\t\t\tlazyLoad:true,\r\n");
      out.write("\t\t\t\t\t\tid : 'id_combo_registrar',\r\n");
      out.write("\t\t\t\t\t\twidth : 167,\r\n");
      out.write("\t\t\t\t\t\trenderTo : 'id_contract_registrar',\r\n");
      out.write("\t\t\t\t\t\txmlFileName : '\\\\eleasing\\\\workflow\\\\public\\\\creator_combox.xml',\r\n");
      out.write("\t\t\t\t\t\tloadMode : 'ajax',\r\n");
      out.write("\t\t\t\t\t\treadOnly : false,\r\n");
      out.write("\t\t\t\t\t\tisAjaxLenovo : true,\r\n");
      out.write("\t\t\t\t\t\totherAttributes:'require=\"true\"  label=\"录入人员\"',\r\n");
      out.write("\t\t\t\t\t\ttopAdd : 0,\r\n");
      out.write("\t\t\t\t\t\tleftAdd : 0,\r\n");
      out.write("\t\t\t\t\t\tpositionDropIconLeftAdd : -1,\r\n");
      out.write("\t\t\t\t\t\tname : 'contract_info.projregistrar',\r\n");
      out.write("\t\t\t\t\t\tdisplayField : 'name',\r\n");
      out.write("\t\t\t\t\t\tvalueField : 'id',\r\n");
      out.write("\t\t\t\t\t\tvalue:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope[\"contract_info.projregistrar\"] ? sessionScope.loginUser.id : requestScope[\"contract_info.projregistrar\"]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("',\r\n");
      out.write("\t\t\t\t\t\trawValue:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope[\"contract_info.projregistrar\"] ? sessionScope.loginUser.realname : requestScope[\"contract_info.projregistrar\"]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("',\r\n");
      out.write("\t\t\t\t\t\tparams : {\r\n");
      out.write("\t\t\t\t\t\t\tdealer_id:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope['currentDealerCustInfoId']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t        new tracywindyComboBox({\r\n");
      out.write("\t\t\t\t\t\tlazyLoad:true,\r\n");
      out.write("\t\t\t\t\t\tid : 'id_combo_proj_manage',\r\n");
      out.write("\t\t\t\t\t\twidth : 167,\r\n");
      out.write("\t\t\t\t\t\trenderTo : 'id_contract_manage',\r\n");
      out.write("\t\t\t\t\t\txmlFileName : '\\\\eleasing\\\\workflow\\\\public\\\\creator_project_manager.xml',\r\n");
      out.write("\t\t\t\t\t\tloadMode : 'ajax',\r\n");
      out.write("\t\t\t\t\t\treadOnly : false,\r\n");
      out.write("\t\t\t\t\t\tisAjaxLenovo : true,\r\n");
      out.write("\t\t\t\t\t\totherAttributes:'require=\"true\"  label=\"项目经理\"',\r\n");
      out.write("\t\t\t\t\t\ttopAdd : 0,\r\n");
      out.write("\t\t\t\t\t\tleftAdd : 0,\r\n");
      out.write("\t\t\t\t\t\tpositionDropIconLeftAdd : -1,\r\n");
      out.write("\t\t\t\t\t\tname : 'contract_info.projmanage',\r\n");
      out.write("\t\t\t\t\t\tdisplayField : 'name',\r\n");
      out.write("\t\t\t\t\t\tvalueField : 'id',\r\n");
      out.write("\t\t\t\t\t\tvalue:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope[\"contract_info.projmanage\"] ? \"\" : requestScope[\"contract_info.projmanage\"]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("',\r\n");
      out.write("\t\t\t\t\t\trawValue:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope[\"contract_info.projmanage\"] ? \"\" : requestScope[\"contract_info.projmanage\"]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("',\r\n");
      out.write("\t\t\t\t\t\tparams : {\r\n");
      out.write("\t\t\t\t\t\t\tdealer_id:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope['currentDealerCustInfoId']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t        /*\r\n");
      out.write("\t\t\t        new tracywindyComboBox({\r\n");
      out.write("\t\t\t\t\t\tlazyLoad:true,\r\n");
      out.write("\t\t\t\t\t\tid : 'id_combo_proj_assist',\r\n");
      out.write("\t\t\t\t\t\twidth : 167,\r\n");
      out.write("\t\t\t\t\t\trenderTo : 'id_contract_assist',\r\n");
      out.write("\t\t\t\t\t\txmlFileName : '\\\\eleasing\\\\workflow\\\\public\\\\creator_combox.xml',\r\n");
      out.write("\t\t\t\t\t\tloadMode : 'ajax',\r\n");
      out.write("\t\t\t\t\t\treadOnly : false,\r\n");
      out.write("\t\t\t\t\t\tisAjaxLenovo : true,\r\n");
      out.write("\t\t\t\t\t\totherAttributes:'require=\"true\"  label=\"客户经理\"',\r\n");
      out.write("\t\t\t\t\t\ttopAdd : 0,\r\n");
      out.write("\t\t\t\t\t\tleftAdd : 0,\r\n");
      out.write("\t\t\t\t\t\tpositionDropIconLeftAdd : -1,\r\n");
      out.write("\t\t\t\t\t\tname : 'contract_info.projassist',\r\n");
      out.write("\t\t\t\t\t\tdisplayField : 'name',\r\n");
      out.write("\t\t\t\t\t\tvalueField : 'id',\r\n");
      out.write("\t\t\t\t\t\tvalue:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope[\"contract_info.projassist\"] ? sessionScope.loginUser.id : requestScope[\"contract_info.projassist\"]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("',\r\n");
      out.write("\t\t\t\t\t\trawValue:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope[\"contract_info.projassist\"] ? sessionScope.loginUser.realname : requestScope[\"contract_info.projassist\"]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("',\r\n");
      out.write("\t\t\t\t\t\tparams : {\r\n");
      out.write("\t\t\t\t\t\t\tdealer_id:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope['currentDealerCustInfoId']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t});*/\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t\t\t/*\r\n");
      out.write("\t\t\t    commonSelect('id_contract_dept','t_depts','id_','name_','contract_info.projdept','");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope[\"contract_info.projdept\"] ? sessionScope[\"loginUserDeptObj\"].id : requestScope[\"contract_info.projdept\"] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope[\"rawValue_contract_info.projdept.name\"] ? sessionScope[\"loginUserDeptObj\"].name : requestScope[\"rawValue_contract_info.projdept.name\"] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("', 'require=\"true\" label=\"出单部门\"');\r\n");
      out.write("\t\t\t    commonSelect('id_contract_registrar','t_users','id_','realname_','contract_info.projregistrar','");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope[\"contract_info.projregistrar\"] ? sessionScope.loginUser.id : requestScope[\"contract_info.projregistrar\"]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope[\"rawValue_contract_info.projregistrar.realname\"] ? sessionScope.loginUser.realname : requestScope[\"rawValue_contract_info.projregistrar.realname\"]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("','require=\"true\" label=\"录入人员\"');\r\n");
      out.write("\r\n");
      out.write("\t\t\t    commonSelect('id_contract_manage','t_users','id_','realname_','contract_info.projmanage','");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope[\"contract_info.projmanage\"] ? sessionScope.loginUser.id : requestScope[\"contract_info.projmanage\"]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope[\"rawValue_contract_info.projmanage\"] ? sessionScope.loginUser.realname : requestScope[\"rawValue_contract_info.projmanage.realname\"]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("','require=\"true\" label=\"客户经理\"');\r\n");
      out.write("\t\t\t    commonSelect('id_contract_assist','t_users','id_','realname_','contract_info.projassist','");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope[\"contract_info.projassist\"] ? sessionScope.loginUser.id : requestScope[\"contract_info.projassist\"]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope[\"rawValue_contract_info.projassist\"] ? sessionScope.loginUser.realname : requestScope[\"rawValue_contract_info.projassist.realname\"]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("','require=\"true\" label=\"客户助理\"');\r\n");
      out.write("                */\r\n");
      out.write("\t\t\t    jQuery(\"#id_loadMaskContainer\").hide();\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t    </script>\r\n");
      out.write("        ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
