package org.apache.jsp.WEB_002dINF.jsps.solutions.workflow.forms.rent_005freckon.rent_005freckon;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class condition_005fframe_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.List<java.lang.String> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList<java.lang.String>(1);
    _jspx_dependants.add("/WEB-INF/tlds/permission.tld");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fpermission_005faction_0026_005fcode;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.List<java.lang.String> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fpermission_005faction_0026_005fcode = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    if (_005fjspx_005ftagPool_005fpermission_005faction_0026_005fcode != null) _005fjspx_005ftagPool_005fpermission_005faction_0026_005fcode.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("//合同审批判断死否做过租金测算\r\n");
      out.write("var contract_approval=false;\r\n");
      out.write("//#############5.留购价款=100元*车头数，车头数即非挂车数量\r\n");
      out.write("var leaveTheToy = 0;\r\n");
      out.write("jQuery(function(){\r\n");
      out.write("    if(isSubTable==true){\r\n");
      out.write("\t\tdictOnSelect('id_period_type','framework_condition.periodtype','period_type','");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope[\"framework_condition.periodtype\"] ? \"period_type_1\" : requestScope[\"framework_condition.periodtype\"] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("',null,'require=\"true\" label=\"付租方式\"',null,null,true,'期末');\r\n");
      out.write("\t\tdictOnSelect('id_income_number_year','framework_condition.incomenumberyear','income_number_year','");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope[\"framework_condition.incomenumberyear\"] ? \"income_1\" : requestScope[\"framework_condition.incomenumberyear\"] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("',incomeNumber,'require=\"true\" label=\"付租类型\"',null,null,true,'月 付' );\r\n");
      out.write("\t\tdictOnSelect('id_insurer_type','framework_condition.insurertype','insurer_type','");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope[\"framework_condition.insurertype\"] ? \"insurer_type.assign\" : requestScope[\"framework_condition.insurertype\"] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("',null,'require=\"true\" label=\"付租类型\"',null,null,true,'月 付' );\r\n");
      out.write("\t\tdictYesOrNoByCode('id_is_registration','framework_condition.isregistration','");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope[\"framework_condition.isregistration\"] ? \"0\" : requestScope[\"framework_condition.isregistration\"] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("',null,false,'require=\"true\" label=\"是否上牌\"',165,null,true,'否');\r\n");
      out.write("\t\tdictYesOrNoByCode('id_is_guaranty','framework_condition.isguaranty','");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope[\"framework_condition.isguaranty\"] ? \"0\" : requestScope[\"framework_condition.isguaranty\"] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("',null,false,'require=\"true\" label=\"是否抵押\"',165,null,true,'否');\r\n");
      out.write("\t\tnew tracywindyComboBox({\r\n");
      out.write("\t\t\tid:'id_combo_id_default_year_rate',\r\n");
      out.write("\t\t\twidth:defaultInputWidth,\r\n");
      out.write("\t\t\trenderTo:'id_default_year_rate',\r\n");
      out.write("\t\t\txmlFileName:'/combos/comboCommonSelect.xml',\r\n");
      out.write("\t\t\tloadMode:'ajax',\r\n");
      out.write("\t\t\treadOnly:false,\r\n");
      out.write("\t\t\totherAttributes:'',\r\n");
      out.write("\t\t\tname:'framework_condition.defaultyearrate',\r\n");
      out.write("\t\t\trawValue:'default_year_rate_one',\r\n");
      out.write("\t\t\tdisplayField:'name',\r\n");
      out.write("\t\t\tvalueField:'value',\r\n");
      out.write("\t\t\tisContainEmpty: false,\r\n");
      out.write("\t\t\tloadComplete : function(combo){\r\n");
      out.write("\t\t\t\tvar yearRateVal = getNumber('yearRate');\r\n");
      out.write("\t\t\t\tvar defaultVal = combo.getValue();\r\n");
      out.write("\t\t\t\tif(!yearRateVal && defaultVal){\r\n");
      out.write("\t\t\t\t\t$('#yearRate').val(defaultVal);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\tparams : {\r\n");
      out.write("\t\t\t\t tableName:\"(select code_ as code, prop_two_ as val from t_dicts_datas where code_='default_year_rate_one') rs\",\r\n");
      out.write("\t\t\t\t displayColumnName:\"code\",\r\n");
      out.write("\t\t\t\t valueColumnName:\"val\"\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//#################5.留购价款=100元*车头数，车头数即非挂车数量\r\n");
      out.write("\t    if('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${business_type}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("'=='bussiness_type_car'){\r\n");
      out.write("\t\t\tvar contractEquip = getTracywindyObject('table_id_table_leasing_proj_equip_container');//租赁物件\r\n");
      out.write("\t\t\tif (contractEquip != null) {\r\n");
      out.write("\t\t\t\tvar datas = contractEquip.getRowsJsonData();\r\n");
      out.write("\t\t\t\tvar carType;\r\n");
      out.write("\t\t\t\tvar totle = 0;\r\n");
      out.write("\t\t\t\tfor (var i = 0; i < datas.length; i++) {\r\n");
      out.write("\t\t\t\t\tcarType = datas[i].equipclass;\r\n");
      out.write("\t\t\t\t\t//2013-11-22 9:54,修改原因：应该是非挂车，判断成挂车了\r\n");
      out.write("\t\t\t\t\tif (carType != \"equip_class_2\") {\r\n");
      out.write("\t\t\t\t\t\ttotle++;\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tleaveTheToy = 100 * totle;\r\n");
      out.write("\t\t\t\t//修改了商务条件就需要重新测算租金\r\n");
      out.write("\t\t\t     if($(\"#nominalPrice\").val()!=leaveTheToy){\r\n");
      out.write("\t\t\t    \t$(\"#nominalPrice\").val(leaveTheToy);\r\n");
      out.write("\t\t\t\t    //chenckCondiotn=false;\r\n");
      out.write("\t\t\t\t    //ie以外的浏览器需要不支持js改变值的事件，需重新计算商务条件\r\n");
      out.write("\t\t\t\t\tequipAmt();\r\n");
      out.write("\t\t\t     }\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t//##################5.留购价款=100元*车头数，车头数即非挂车数量\r\n");
      out.write("    }\r\n");
      out.write("\tvar rentPlanList = JsonUtil.decode('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty json_fund_rent_plan_str ? \"[]\" : json_fund_rent_plan_str }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("');\r\n");
      out.write("\tvar rentPlanListLength = rentPlanList.length;\r\n");
      out.write("\tvar rentTotal = 0;\r\n");
      out.write("\tfor ( var i = 0; i < rentPlanListLength; i++) {\r\n");
      out.write("\t\tvar renPlan = rentPlanList[i];\r\n");
      out.write("\t\tvar rent = renPlan['rent'];\r\n");
      out.write("\t\trentTotal += rent*1;\r\n");
      out.write("\t}\r\n");
      out.write("\tjQuery('#rentTotalMoney').val(rentTotal);\r\n");
      out.write("});\r\n");
      out.write("</script>\r\n");
      out.write("<div id=\"id_submitFrameworkConditionForm\">\r\n");
      out.write("  <table class=\"fillTable\" cellspacing=\"0\" cellpadding=\"0\" id=\"contract_condition\">\r\n");
      out.write("  <!-- \r\n");
      out.write("  \t\t<input  name=\"framework_condition.freedefainterday\" id=\"freedefainterday\"  type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['framework_condition.freedefainterday']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" >\r\n");
      out.write("\t\t  -->\r\n");
      out.write("\t\t  <tr>\r\n");
      out.write("             <td class=\"x-panel-table-div-title\" colspan=6><div class=\"toggle-icon-expanded\" title=\"折叠\" toggleClass=\"tr-condition-info\"></div>商务条件</td>\r\n");
      out.write("          </tr> \r\n");
      out.write("          <tr class=\"tr-condition-info tr-odd\" id=\"rentCalUtil\">\r\n");
      out.write("             <td class=\"td-content-title\">客户名称：</td>\r\n");
      out.write("             <td colspan=\"3\" class=\"td-content\" >\r\n");
      out.write("             \t<input style=\"width:85%\"  name=\"framework_condition.custname\" id=\"conditionCustName\" class=\"td-content-input td-content-readonly\"  type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['framework_condition.custname']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" readonly>\r\n");
      out.write("             </td>\r\n");
      out.write("             <td class=\"td-content-title\">报价编号：</td><td class=\"td-content\"><input name=\"framework_condition.quotid\" class=\"td-content-input td-content-readonly\"  readonly type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['framework_condition.quotid']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"   /></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr class=\"tr-condition-info tr-even\" >\r\n");
      out.write("\t\t\t <td class=\"td-content-title\">设备款：</td><td class=\"td-content\"><input name=\"framework_condition.equipamt\" id=\"equipAmt\" class=\"td-content-input\" type=\"text\" oninput=\"OnInput (event)\" onpropertychange=\"OnPropChanged (event)\" datatype=\"PMoney\" require=\"true\" label=\"设备款\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['framework_condition.equipamt']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("               <font class=\"required-content\">*</font></td>\r\n");
      out.write("             <td class=\"td-content-title\">融资额：</td>\r\n");
      out.write("               <td class=\"td-content\"><input name=\"framework_condition.leasemoney\" id=\"leaseMoney\" class=\"td-content-input td-content-readonly\" readonly type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope['framework_condition.leasemoney'] ? 0 : requestScope['framework_condition.leasemoney']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"  /></td>\r\n");
      out.write("             <td class=\"td-content-title\">净融资额  ：</td><td class=\"td-content\"><input name=\"framework_condition.cleanleasemoney\" id=\"cleanLeaseMoney\" class=\"td-content-input td-content-readonly\" readonly=\"readonly\"  type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope['framework_condition.cleanleasemoney']?0:requestScope['framework_condition.cleanleasemoney']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" /></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr class=\"tr-condition-info tr-odd\" id=\"onHireProcessDataTR\">\r\n");
      out.write("            <td class=\"td-content-title\" id=\"onhiredatatext\">计划起租日期：</td>\r\n");
      out.write("            <td class=\"td-content\"><input name=\"framework_condition.startdate\" id=\"startDate\" class=\"Wdate td-content-input td-content-readonly\"  \r\n");
      out.write("             type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['framework_condition.startdate'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" dataType=\"Date\"  onclick=\"WdatePicker(this,{readOnly:true})\" require=\"true\" label=\"起租日期\" readonly=\"readonly\" onchange=\"OnchangeDate()\"/>\r\n");
      out.write("              <font class=\"required-content\">*</font></td>\r\n");
      out.write("              <td class=\"td-content-title\">第一期租金支付日：</td>\r\n");
      out.write("            <td class=\"td-content\"><input name=\"framework_condition.firstplandate\" dataType=\"Date\" id=\"firstPlanDate\" class=\"Wdate td-content-input td-content-readonly\" type=\"text\" onclick=\"WdatePicker(this,{readOnly:true})\" require=\"true\"  label=\"第一期租金支付日\" readonly=\"readonly\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['framework_condition.firstplandate'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/><font class=\"required-content\">*</font></td>\r\n");
      out.write("            <td class=\"td-content-title\">租赁年利率：</td>\r\n");
      out.write("            <td class=\"td-content\"><input name=\"framework_condition.yearrate\" id=\"yearRate\" class=\"td-content-input\" require=\"true\" datatype=\"Rate\" label=\"租赁年利率\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['framework_condition.yearrate']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("            <font class=\"required-content\">%&nbsp;*</font></td>\r\n");
      out.write("            \r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr class=\"tr-condition-info tr-even\">\r\n");
      out.write("          <td class=\"td-content-title\">起租比例：</td>\r\n");
      out.write("            <td class=\"td-content\"><span class=\"td-content-title\">\r\n");
      out.write("              <input name=\"framework_condition.firstpaymentratio\" class=\"td-content-input\"  type=\"text\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['framework_condition.firstpaymentratio']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"  id=\"firstPaymentRatio\" require=\"true\" datatype=\"Double\" label=\"起租比例\" oninput=\"OnInput (event)\" onpropertychange=\"OnPropChanged (event)\"/>\r\n");
      out.write("              <font class=\"required-content\">%&nbsp;*</font></span></td>\r\n");
      out.write("            <td class=\"td-content-title\">起租租金：</td>\r\n");
      out.write("            <td class=\"td-content\"><input name=\"framework_condition.firstpayment\" id=\"firstPayment\" readonly require=\"true\" class=\"td-content-input td-content-readonly\"   type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope['framework_condition.firstpayment'] ? 0 : requestScope['framework_condition.firstpayment']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" datatype=\"PMoney\" label=\"起租租金\"  />\r\n");
      out.write("              <font class=\"required-content\">*</font></td>\r\n");
      out.write("            \r\n");
      out.write("            <td class=\"td-content-title\">还租次数：</td>\r\n");
      out.write("            <td class=\"td-content\"><input name=\"framework_condition.incomenumber\" id=\"incomeNumber\" class=\"td-content-input\" oninput=\"OnInput (event)\" onpropertychange=\"OnPropChanged (event)\"  require=\"true\"  datatype=\"Number\" label=\"还租次数\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['framework_condition.incomenumber']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("            <font class=\"required-content\">*</font></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr class=\"tr-condition-info tr-even\">\r\n");
      out.write("             <td class=\"td-content-title\">付租类型 ：</td><td class=\"td-content\"><div id=\"id_income_number_year\" class=\"leftComboContainer\"></div><font class=\"required-content\">*</font></td>\r\n");
      out.write("             <td class=\"td-content-title\">付租方式：</td><td class=\"td-content\"><div id=\"id_period_type\" class=\"leftComboContainer\"></div><font class=\"required-content\">*</font></td>\r\n");
      out.write("             <td class=\"td-content-title\">租赁期限(月)：</td><td class=\"td-content\"><input name=\"framework_condition.leaseterm\" id=\"leaseTerm\" class=\"td-content-input td-content-readonly\" label=\"租赁期限\" readonly type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ requestScope['framework_condition.leaseterm'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"   /></td>\r\n");
      out.write("          </tr>         \r\n");
      out.write("          <tr class=\"tr-condition-info tr-odd\">\r\n");
      out.write("             <td class=\"td-content-title\">保险费：</td><td class=\"td-content\"><input name=\"framework_condition.insuremoney\" id=\"insureMoney\" class=\"td-content-input\"   datatype=\"PMoney\" label=\"保险费\"  type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope['framework_condition.insuremoney']?0:requestScope['framework_condition.insuremoney']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" oninput=\"OnInput (event)\" onpropertychange=\"OnPropChanged (event)\"/></td>\r\n");
      out.write("             <td class=\"td-content-title\">天行健服务费：</td><td class=\"td-content\"><input name=\"framework_condition.gpsmoney\" id=\"gpsMoney\" class=\"td-content-input\"   datatype=\"PMoney\"  type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope['framework_condition.gpsmoney']?0:requestScope['framework_condition.gpsmoney']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" oninput=\"OnInput (event)\" onpropertychange=\"OnPropChanged (event)\"/></td>\r\n");
      out.write("             <td class=\"td-content-title\">留购价款：</td><td class=\"td-content\"><input name=\"framework_condition.nominalprice\" id=\"nominalPrice\" class=\"td-content-input\"  datatype=\"PMoney\"  oninput=\"OnInput (event)\" onpropertychange=\"OnPropChanged (event)\" require=\"true\" label=\"留购价款\"  type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope['framework_condition.nominalprice'] ? 0 : requestScope['framework_condition.nominalprice']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("             <font class=\"required-content\">*</font></td>\r\n");
      out.write("          </tr>         \r\n");
      out.write("          <tr class=\"tr-condition-info tr-even\">\r\n");
      out.write("             <td class=\"td-content-title\">是否上牌：</td><td class=\"td-content\"><div id=\"id_is_registration\" class=\"leftComboContainer\"></div>\r\n");
      out.write("               <font class=\"required-content\">*</font></td>\r\n");
      out.write("             <td class=\"td-content-title\">保证金比例：</td><td class=\"td-content\"><input name=\"framework_condition.cautionmoneyratio\" id=\"cautionMoneyRatio\" class=\"td-content-input\" require=\"true\" label=\"保证金比例\" datatype=\"Rate\" oninput=\"OnInput (event)\" onpropertychange=\"OnPropChanged (event)\"  type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty  requestScope['framework_condition.cautionmoneyratio']?5:requestScope['framework_condition.cautionmoneyratio']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("               <font class=\"required-content\">%&nbsp;*</font></td>\r\n");
      out.write("             <td class=\"td-content-title\">保证金：</td><td class=\"td-content\"><input name=\"framework_condition.cautionmoney\" id=\"cautionMoney\" class=\"td-content-input td-content-readonly\" dataType=\"PMoney\" readonly type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope['framework_condition.cautionmoney'] ? 0 : requestScope['framework_condition.cautionmoney'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"   /></td>\r\n");
      out.write("          </tr>         \r\n");
      out.write("          <tr class=\"tr-condition-info tr-odd\">\r\n");
      out.write("            <td class=\"td-content-title\">是否抵押：</td>\r\n");
      out.write("            <td class=\"td-content\"><div id=\"id_is_guaranty\" class=\"leftComboContainer\"></div>\r\n");
      out.write("               <font class=\"required-content\">*</font></td>\r\n");
      out.write("            <td class=\"td-content-title\">手续费比例  ：</td>\r\n");
      out.write("            <td class=\"td-content\"><input name=\"framework_condition.handlingchargemoneyratio\" id=\"handlingChargeMoneyRatio\" class=\"td-content-input\" require=\"true\" label=\"手续费比例\" datatype=\"Rate\" oninput=\"OnInput (event)\" onpropertychange=\"OnPropChanged (event)\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope['framework_condition.handlingchargemoneyratio']?1:requestScope['framework_condition.handlingchargemoneyratio']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("            <font class=\"required-content\">%&nbsp;*</font></td>\r\n");
      out.write("            <td class=\"td-content-title\">手续费 ：</td>\r\n");
      out.write("            <td class=\"td-content\"><input name=\"framework_condition.handlingchargemoney\" id=\"handlingChargeMoney\" class=\"td-content-input  td-content-readonly\"  readonly datatype=\"PMoney\" label=\"手续费\"  type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope['framework_condition.handlingchargemoney']?0:requestScope['framework_condition.handlingchargemoney'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"   /></td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr class=\"tr-condition-info tr-even\">\r\n");
      out.write("            <td class=\"td-content-title\">租金总额：</td><td class=\"td-content\"><input name=\"framework_condition.renttotalmoney\" id=\"rentTotalMoney\" class=\"td-content-input td-content-readonly\" readonly  datatype=\"PMoney\"  type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope['framework_condition.renttotalmoney']?0:requestScope['framework_condition.renttotalmoney']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" /></td>\r\n");
      out.write("             <td class=\"td-content-title\">期初付款总计：</td><td class=\"td-content\"><input title=\"期初付款总计=起租租金+保证金+手续费+留购价款+保险费+天行健服务费+其他费用\" name=\"framework_condition.firstpaymenttotal\" id=\"firstPaymentTotal\" class=\"td-content-input td-content-readonly\" readonly=\"readonly\" type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['framework_condition.firstpaymenttotal'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" /></td>\r\n");
      out.write("             <td class=\"td-content-title\">其他费用  ：</td>\r\n");
      out.write("            <td class=\"td-content\"><input name=\"framework_condition.otherincome\" id=\"otherIncome\" class=\"td-content-input\" datatype=\"PMoney\" label=\"其他收入\"  type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope['framework_condition.otherincome'] ? 0 : requestScope['framework_condition.otherincome']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" oninput=\"OnInput (event)\" onpropertychange=\"OnPropChanged (event)\"/></td>\r\n");
      out.write("             \r\n");
      out.write("          </tr>    \r\n");
      out.write("          \r\n");
      out.write("          <tr class=\"tr-condition-info tr-odd\">\r\n");
      out.write("            <td class=\"td-content-title\" >保险方式:</td>\r\n");
      out.write("            <td class=\"td-content\"><div id=\"id_insurer_type\" class=\"leftComboContainer\"></div><font class=\"required-content\">*</font></td>\r\n");
      out.write("            <td  id=\"irr_no_purview_irr\" class=\"td-content-title\">内部收益率：</td>\r\n");
      out.write("            <td  id=\"irr_no_purview_irr_content\" class=\"td-content\"><input name=\"framework_condition.irr\" id=\"irr\" class=\"td-content-input td-content-readonly\" readonly type=\"text\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope['framework_condition.irr']?0:requestScope['framework_condition.irr'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("            <font class=\"required-content\">%</font></td>\r\n");
      out.write("            <td class=\"td-content-title\">&nbsp;</td>\r\n");
      out.write("            <td class=\"td-content\">&nbsp;</td>\r\n");
      out.write("          </tr>\r\n");
      out.write("          <tr class=\"tr-condition-info tr-even\">\r\n");
      out.write("          \t <td  colspan=6 align=\"right\">\r\n");
      out.write("          \t \t<div id=\"id_default_year_rate\" class=\"leftComboContainer\" style=\"display: none;\"></div>\r\n");
      out.write("          \t \t<input name=\"framework_condition.leaseamtdate\" id=\"leaseAmtDate\" type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['framework_condition.leaseamtdate'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/>          \t \t\r\n");
      out.write("          \t \t<input name=\"framework_condition.settlemethod\" id=\"settleMethod\" type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope['framework_condition.settlemethod']?'even_rent':requestScope['framework_condition.settlemethod'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"/>\r\n");
      out.write("          \t \t<input name=\"framework_condition.ismerger\" id=\"ismerger\" type=\"hidden\" value=\"1\"/>\r\n");
      out.write("\t\t\t\t<input name=\"framework_condition.id\"  id=\"conditionId\" type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['framework_condition.id']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t\t\t\t<input name=\"framework_condition.custid\" id=\"conditionCustId\" type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['framework_condition.custid']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t\t\t\t<input name=\"framework_condition.contractid\" id=\"conditionContractId\"  type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['framework_condition.contractid']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t\t\t\t<input name=\"framework_condition.projid\" id=\"conditionProjId\"  type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['framework_condition.projid']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t\t\t\t<input name=\"framework_condition.docid\" id=\"conditionDocId\" type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['framework_condition.docid']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t\t\t\t<input name=\"framework_condition.process\" id=\"reckonProcess\" type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['framework_condition.process']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">\r\n");
      out.write("\t\t\t\t<input name=\"framework_condition.reckontype\" id=\"reckonType\"  type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope['framework_condition.reckontype']?'condition':requestScope['framework_condition.reckontype'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t\t\t\t<input name=\"framework_condition.enddate\" id=\"enddate\"  type=\"hidden\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope['framework_condition.enddate']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" />\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"id_json_fund_rent_plan_str\" name=\"json_fund_rent_plan_str\" value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty json_fund_rent_plan_str ? \"[]\" : json_fund_rent_plan_str}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('\'');
      out.write('/');
      out.write('>');
      out.write("\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"id_json_fund_cash_flow_str\" name=\"json_fund_cash_flow_str\" value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty json_fund_cash_flow_str ? \"[]\" : json_fund_cash_flow_str }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write('\'');
      out.write('/');
      out.write('>');
      out.write("\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" id=\"id_json_fund_fund_charge_str\" name=\"json_fund_fund_charge_str\"  value='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty json_fund_fund_charge_str ? \"[]\" : json_fund_fund_charge_str }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("'/>\r\n");
      out.write("\t\t\t\t<input style=\"margin-top:2px;margin-bottom:2px;\" id=\"btn_rent_cal\" class=\"btn btn-primary\" type=\"button\" value=\"租金测算\" onclick=\"conditionReckon();\"/>\r\n");
      out.write("          \t </td>\r\n");
      out.write("          </tr>                \r\n");
      out.write("\t</table>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("//租金测算默认为false,如果修改商务条件，然后保存，再从草稿中打开，是可以提交任务的\r\n");
      out.write("var chenckCondiotn=false;//是否改变过租金测算的代码为点租金测算  (false不能提交,true允许提交)\r\n");
      out.write("//页面各种赋值自动计算\r\n");
      out.write(" // Firefox, Google Chrome, Opera, Safari, Internet Explorer from version 9\r\n");
      out.write("        \r\n");
      out.write("\t \tfunction resetMoneyScale(event){\r\n");
      out.write("\t \t\tvar targetId = getTarget(event).id;\r\n");
      out.write("\t        var value = getTarget(event).value;\r\n");
      out.write("\t        if(targetId && value && !isNaN(value)){\r\n");
      out.write("\t        \tvar $targetDocument = jQuery('#' + targetId);\r\n");
      out.write("\t            var dataType = $targetDocument.attr('datatype');\r\n");
      out.write("\t            if(dataType && (dataType == 'PMoney'||dataType == 'Money')){\r\n");
      out.write("\t            \tif(decimal(value, 0) != value){\r\n");
      out.write("\t            \t\t$targetDocument.val(decimal(value, 0));\r\n");
      out.write("\t            \t}\r\n");
      out.write("\t            }\r\n");
      out.write("\t        }\r\n");
      out.write("\t\t}\r\n");
      out.write(" \r\n");
      out.write(" \t\tfunction OnInput (event) {\r\n");
      out.write("            var targetId = getTarget(event).id;\r\n");
      out.write("            resetMoneyScale(event);\r\n");
      out.write("            equipAmt();\r\n");
      out.write("            if (targetId == 'incomeNumber'||targetId == 'grace'){//期限计算\r\n");
      out.write("            \tincomeNumber();\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    // Internet Explorer\r\n");
      out.write("        function OnPropChanged (event) {\r\n");
      out.write("        \tvar targetId = getTarget(event).id;\r\n");
      out.write("        \tresetMoneyScale(event);\r\n");
      out.write("            if (event.propertyName.toLowerCase () == \"value\") {\r\n");
      out.write("                equipAmt();\r\n");
      out.write("                if (targetId == 'incomeNumber'||targetId == 'grace'){//期限计算\r\n");
      out.write("                \tincomeNumber();\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        //净融资额=设备款-保证金-手续费-厂商返佣-其他收入+其他支出 -租前息-管理费-首付款\r\n");
      out.write("        function  equipAmt(){//设备款改变 影响 首付款,融资额,保证金(比例) 保证金抵扣 预收租金 手续费 管理费 首付款\r\n");
      out.write("        \tvar equipAmt = getNumber(\"equipAmt\");//设备款\r\n");
      out.write("            var firstPaymentRatio = getNumber(\"firstPaymentRatio\");//起租比例\r\n");
      out.write("            var firstPayment = decimal((equipAmt * firstPaymentRatio)/100,0);//起租租金\r\n");
      out.write("            var leaseMoney = decimal(equipAmt*1-firstPayment*1,0);//融资额\r\n");
      out.write("            \r\n");
      out.write("            var handlingChargeMoneyRatio = getNumber(\"handlingChargeMoneyRatio\");\r\n");
      out.write("            var handlingChargeMoney = decimal((leaseMoney * handlingChargeMoneyRatio)/100,0);//手续费\r\n");
      out.write("            var cautionMoneyRatio = getNumber(\"cautionMoneyRatio\");\r\n");
      out.write("            var cautionMoney = decimal((leaseMoney * cautionMoneyRatio)/100,0);//保证金\r\n");
      out.write("            \r\n");
      out.write("            if(equipAmt*1 >= 0 && leaseMoney*1 >= 0){\r\n");
      out.write("   \t\t\t\tjQuery('#leaseMoney').val(leaseMoney);\r\n");
      out.write("   \t\t\t\tjQuery('#firstPayment').val(firstPayment);\r\n");
      out.write("   \t\t\t\tjQuery('#handlingChargeMoney').val(handlingChargeMoney);\r\n");
      out.write("   \t\t\t\tjQuery('#cautionMoney').val(cautionMoney);\r\n");
      out.write("    \t\t\tfirstPaymentTotal();\r\n");
      out.write("            }\r\n");
      out.write("     \t}\r\n");
      out.write("       \t/*\r\n");
      out.write("       \t根据金额算比例\r\n");
      out.write("       \t*/\r\n");
      out.write("        function setRatio(obj,num){\r\n");
      out.write("        \tvar equip_amt=getNumber(\"equipAmt\");\r\n");
      out.write("        \tif(equip_amt==\"\"){equip_amt=0;}\r\n");
      out.write("        \tif(num*1>=0){\r\n");
      out.write("        \t\tjQuery('#'+obj+\"Ratio\").val(decimal(num/equip_amt*100,6));\r\n");
      out.write("        \t}\r\n");
      out.write("        }\r\n");
      out.write("\t\t/*\r\n");
      out.write("       \t根据比例算金额\r\n");
      out.write("       \t*/\r\n");
      out.write("        function setMoneyByRatio(obj,num){\r\n");
      out.write("        \tvar equip_amt=getNumber(\"equipAmt\");\r\n");
      out.write("        \tif(num*1>=0){\r\n");
      out.write("        \t\tjQuery('#'+obj).val(decimal(num*equip_amt/100,0));\r\n");
      out.write("        \t}\r\n");
      out.write("        }\r\n");
      out.write("        /*\r\n");
      out.write("       \t根据比例算金额\r\n");
      out.write("       \t*/\r\n");
      out.write("        function setMoneyByRatioNew(obj,num){\r\n");
      out.write("        \tvar leaseMoney=getNumber(\"leaseMoney\");\r\n");
      out.write("        \tif(num*1>=0){\r\n");
      out.write("        \t\tjQuery('#'+obj).val(decimal(num*leaseMoney/100,0));\r\n");
      out.write("        \t}\r\n");
      out.write("        }\r\n");
      out.write("        //获取对象的数值\r\n");
      out.write("        function getNumber(id){\r\n");
      out.write("            var obj=jQuery('#'+id).attr(\"value\");\r\n");
      out.write("            var va=0;\r\n");
      out.write("            try{\r\n");
      out.write("                if(obj==''){\r\n");
      out.write("                \tobj=0;\r\n");
      out.write("                }\r\n");
      out.write("            \tva=parseFloat(obj);\r\n");
      out.write("            }catch(e){\r\n");
      out.write("            \tva=0;\r\n");
      out.write("            }\r\n");
      out.write("            return va;\r\n");
      out.write("        }\r\n");
      out.write("        function OnchangeDate(){\r\n");
      out.write("\t\t\tvar starDate=jQuery('#startDate').val();\r\n");
      out.write("\t\t\t//按照付款间隔推算起租日\r\n");
      out.write("\t\t\tvar income_number_year=getTracywindyObject(\"id_combo_id_income_number_year\").getValue();\r\n");
      out.write("\t\t\tvar period_type=getTracywindyObject(\"id_combo_id_period_type\").getValue();\r\n");
      out.write("\t\t\tif(income_number_year==\"income_1\") {income_number_year=\"1\";}\r\n");
      out.write("\t\t\tif(income_number_year==\"income_2\") {income_number_year=\"2\";}\r\n");
      out.write("\t\t\tif(income_number_year==\"income_3\") {income_number_year=\"3\";}\r\n");
      out.write("\t\t\tif(income_number_year==\"income_6\") {income_number_year=\"6\";}\r\n");
      out.write("\t\t\tif(income_number_year==\"income_12\"){income_number_year=\"12\";}\r\n");
      out.write("\t\t\tif(period_type==\"period_type_0\") {period_type=\"0\";}\r\n");
      out.write("\t\t\tif(period_type==\"period_type_1\") {period_type=\"1\";}\r\n");
      out.write("\t\t\tif(income_number_year==\"\"||period_type==\"\"||starDate==\"\"){\r\n");
      out.write("\t\t\t\treturn;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tvar firstPlanDate=\"\";\r\n");
      out.write("\t\t\tif(income_number_year!=\"\"&&period_type!=\"\"){\r\n");
      out.write("\t\t\t\tfirstPlanDate=calculateDate(5,income_number_year*period_type,starDate);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t//当月6日至当月15日起租的项目，次月15日还第一期租金；\r\n");
      out.write("\t\t\t//当月16日至当月25日起租的项目，次月25日还第一期租金；\r\n");
      out.write("\t\t\t//当月26日至次月5日起租的项目，次次月5日还第一期租金。\r\n");
      out.write("\t\t\tvar day=starDate.split(\"-\")[2];\r\n");
      out.write("\t\t\tif(day<6){\r\n");
      out.write("\t\t\t\tfirstPlanDate=firstPlanDate.substring(0,7)+\"-05\";\r\n");
      out.write("\t\t\t}else\tif(day>=6&&day<=15){\r\n");
      out.write("\t\t\t\tfirstPlanDate=firstPlanDate.substring(0,7)+\"-15\";\r\n");
      out.write("\t\t\t}else if(day>=16&&day<=25){\r\n");
      out.write("\t\t\t\tfirstPlanDate=firstPlanDate.substring(0,7)+\"-25\";\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tfirstPlanDate=firstPlanDate.substring(0,7)+\"-05\";\r\n");
      out.write("\t\t\t\tfirstPlanDate=calculateDate(5,1,firstPlanDate);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tjQuery(\"#firstPlanDate\").val(firstPlanDate);\r\n");
      out.write("\t\t\tjQuery(\"#leaseAmtDate\").val(starDate);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//计算  期初付款总计 和 净融资额 ：\r\n");
      out.write("     \tfunction firstPaymentTotal(){\r\n");
      out.write("        \t\tvar clean_lease_money = decimal(getNumber(\"equipAmt\"), 0);\r\n");
      out.write("        \t\tvar first_payment_total = 0;\r\n");
      out.write("        \t\tfirst_payment_total += decimal(getNumber(\"firstPayment\"), 0);\r\n");
      out.write("        \t\tfirst_payment_total += decimal(getNumber(\"cautionMoney\"), 0);\r\n");
      out.write("        \t\tfirst_payment_total += decimal(getNumber(\"handlingChargeMoney\"), 0);\r\n");
      out.write("        \t\tfirst_payment_total += decimal(getNumber(\"otherIncome\"), 0);\r\n");
      out.write("        \t\tfirst_payment_total += decimal(getNumber(\"insureMoney\"), 0);\r\n");
      out.write("        \t\tfirst_payment_total += decimal(getNumber(\"gpsMoney\"), 0);\r\n");
      out.write("        \t\tfirst_payment_total += decimal(getNumber(\"nominalPrice\"), 0);\r\n");
      out.write("        \t\tclean_lease_money -= first_payment_total;\r\n");
      out.write("        \t\tjQuery('#firstPaymentTotal').val(decimal(first_payment_total, 0));\r\n");
      out.write("        \t\tjQuery('#cleanLeaseMoney').val(decimal(clean_lease_money, 0));\r\n");
      out.write("        \t\tchenckCondiotn = false;\r\n");
      out.write("        }\r\n");
      out.write("     \tfunction incomeNumber(){//计算期数\r\n");
      out.write("   \t\t\tvar income_number=getNumber(\"incomeNumber\");\r\n");
      out.write("   \t\t\tvar income_number_year=getTracywindyObject(\"id_combo_id_income_number_year\").getValue();\r\n");
      out.write("   \t\t\t/*\r\n");
      out.write("   \t\t\t月  付 income_1 \r\n");
      out.write("   \t\t\t双月付 income_2\r\n");
      out.write("   \t\t\t季  付 income_3 \r\n");
      out.write("   \t\t\t半年付 income_6 \r\n");
      out.write("   \t\t\t年  付 income_12 \r\n");
      out.write("   \t\t\t*/\r\n");
      out.write("   \t\t\tif(income_number_year==\"income_1\") {income_number_year=\"1\";}\r\n");
      out.write("   \t\t\tif(income_number_year==\"income_2\") {income_number_year=\"2\";}\r\n");
      out.write("   \t\t\tif(income_number_year==\"income_3\") {income_number_year=\"3\";}\r\n");
      out.write("   \t\t\tif(income_number_year==\"income_6\") {income_number_year=\"6\";}\r\n");
      out.write("   \t\t\tif(income_number_year==\"income_12\"){income_number_year=\"12\";}\r\n");
      out.write("   \t\t\tif(income_number*1>0&&income_number_year*1>0){\r\n");
      out.write("   \t\t\t\tjQuery('#leaseTerm').val((income_number*1)*income_number_year);\r\n");
      out.write("   \t\t\t}\r\n");
      out.write("   \t\t\tOnchangeDate();\r\n");
      out.write("   \t\t\tchenckCondiotn=false;\r\n");
      out.write("     \t}\r\n");
      out.write("     \tfunction checkSubmit(){\r\n");
      out.write("     \t\treturn true;\t\r\n");
      out.write("     \t}\r\n");
      out.write("\r\n");
      out.write("    function rentCalculateSubmit(todoAction)\r\n");
      out.write("    {\r\n");
      out.write("        //条件通过提交表单\r\n");
      out.write("        jQuery(\"#id_workflowAdviseContainer\").css(\"overflow\",\"hidden\");\r\n");
      out.write("        jQuery(\"#id_workflowFormContainer\").css(\"overflow\",\"hidden\");\r\n");
      out.write("        if(!loadMask)\r\n");
      out.write("        {\r\n");
      out.write("        \tloadMask = new tracywindyLoadMask(document.body,\"数据处理中，请稍等...\");\r\n");
      out.write("        }\r\n");
      out.write("        loadMask.show();\r\n");
      out.write("        window.top.document.body.style.overflow=\"hidden\";\r\n");
      out.write("        var $submitConditionForm = $(\"#id_submitFrameworkConditionForm\");\r\n");
      out.write("        var url = todoAction;\r\n");
      out.write("        var params = $submitConditionForm.tracywindySerializeFormToJsonObject(true,true);\r\n");
      out.write("        ajaxRequest({\r\n");
      out.write("        \t method:'POST',\r\n");
      out.write("             url:url,\r\n");
      out.write("             params:params,\r\n");
      out.write("             failure:function(res){\r\n");
      out.write("        \t\tjQuery(\"#id_workflowAdviseContainer\").css(\"overflow\",\"auto\");\r\n");
      out.write("           \t\tjQuery(\"#id_workflowFormContainer\").css(\"overflow\",\"auto\");\r\n");
      out.write("       \t \t\tloadMask.hide();\r\n");
      out.write("            \talert(\"访问服务器进行测算失败[服务器正忙,或者无法连通,或者服务器出现异常]!\");\r\n");
      out.write("             },\r\n");
      out.write("             success:function(res){\r\n");
      out.write("            \tchenckCondiotn=true;\r\n");
      out.write("     \t   \t\tres=res.responseText;\r\n");
      out.write("     \t   \t\tres=res.replace(/(^\\s+)|(\\s+$)/g, \"\"); \r\n");
      out.write("\t     \t    if(res!=''){\r\n");
      out.write("\t     \t    \tajaxRentCalculateCallBack(res);\r\n");
      out.write("\t     \t    }else{\r\n");
      out.write("\t     \t    \tjQuery(\"#id_workflowAdviseContainer\").css(\"overflow\",\"auto\");\r\n");
      out.write("\t           \t\tjQuery(\"#id_workflowFormContainer\").css(\"overflow\",\"auto\");\r\n");
      out.write("\t       \t \t\tloadMask.hide();\r\n");
      out.write("\t     \t    \talert(\"请求测算成功,但无结果返回,请重新尝试!\");\r\n");
      out.write("\t     \t    }\r\n");
      out.write("             }\r\n");
      out.write("        });\r\n");
      out.write("    \treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("    function ajaxRentCalculateCallBack(returnResult){\r\n");
      out.write("         jQuery(\"#id_workflowAdviseContainer\").css(\"overflow\",\"auto\");\r\n");
      out.write("         jQuery(\"#id_workflowFormContainer\").css(\"overflow\",\"auto\");\r\n");
      out.write("    \t loadMask.hide();\r\n");
      out.write("    \t var rs=JsonUtil.decode(returnResult);\r\n");
      out.write("    \t if(rs['rentcalculaters']==\"yes\"){\r\n");
      out.write("\t    \t var fundRentPlan = getTracywindyObject('table_id_table_leasing_rent_plan_container');\r\n");
      out.write("\t    \t fundRentPlan.tableData = rs['fundrentplan'];\r\n");
      out.write("\t    \t var fundCashDetail = getTracywindyObject('table_id_table_leasing_fund_cash_flow_container');\r\n");
      out.write("\t    \t fundCashDetail.tableData = rs['fundcashdetail'];\r\n");
      out.write("\t    \t jQuery('#irr').val(decimal((rs['irr']),6)) ;\r\n");
      out.write("\t    \t jQuery('#enddate').val(rs['enddate']);\r\n");
      out.write("\t    \t jQuery('#rentTotalMoney').val(rs['renttotalmoney']);\r\n");
      out.write("     \t\t//保存多行控件的值\r\n");
      out.write("\t    \t jQuery('#id_json_fund_cash_flow_str').val(JsonUtil.encode(fundCashDetail.getRowsJsonData())) ;\r\n");
      out.write("     \t\t jQuery('#id_json_fund_rent_plan_str').val(JsonUtil.encode(fundRentPlan.getRowsJsonData())) ;\r\n");
      out.write("     \t\t fundRentPlan.reload();\r\n");
      out.write("\t    \t fundCashDetail.reload();\r\n");
      out.write("\t    \t //判断是否有资金计划的表单在\r\n");
      out.write("\t    \t var fundChargePlan = getTracywindyObject('table_id_table_leasing_fund_fund_charge_container');\r\n");
      out.write("\t    \t if(typeof(fundChargePlan)=='object'){\r\n");
      out.write("\t\t    \t //alert(\"有资金计划控件\");\r\n");
      out.write("\t    \t\t if(JsonUtil.decode(returnResult)['fundchargeplanmsg']==\"yes\"){\r\n");
      out.write("\t    \t\t\t createFundChargePlan(returnResult);\r\n");
      out.write("\t    \t\t }\r\n");
      out.write("\t    \t }\r\n");
      out.write("\t    \t var contractStarDate=jQuery('#contract_info.startdate');\r\n");
      out.write("\t    \t if(typeof(contractStarDate)=='object'){\r\n");
      out.write("\t    \t\t contractStarDate.val(jQuery('#framework_condition.startdate'));\r\n");
      out.write("\t    \t }\r\n");
      out.write("\t    \t var contractEndDate=jQuery('#contract_info.enddate');\r\n");
      out.write("\t    \t if(typeof(contractEndDate)=='object'){\r\n");
      out.write("\t    \t\t contractEndDate.val(jQuery('#framework_condition.enddate'));\r\n");
      out.write("\t    \t }\r\n");
      out.write("\t    \t var projStarDate=jQuery('#proj_info.startdate');\r\n");
      out.write("\t    \t if(typeof(projStarDate)=='object'){\r\n");
      out.write("\t    \t\t projStarDate.val(jQuery('#framework_condition.startdate'));\r\n");
      out.write("\t    \t }\r\n");
      out.write("\t    \t var projEndDate=jQuery('#proj_info.enddate');\r\n");
      out.write("\t    \t if(typeof(projEndDate)=='object'){\r\n");
      out.write("\t    \t\t projEndDate.val(jQuery('#framework_condition.enddate'));\r\n");
      out.write("\t    \t }\r\n");
      out.write("\t    \t alert(\"租金测算成功\");     \t\t \r\n");
      out.write("    \t }\r\n");
      out.write("         //根据测算方式控制是否显示多行控件操作条\r\n");
      out.write("         var settle_method=jQuery(\"#settleMethod\").val();\r\n");
      out.write("         reckonMultiTable(settle_method);\r\n");
      out.write("    \t saveReckonJsonValue();\r\n");
      out.write("    }\r\n");
      out.write("    /*\r\n");
      out.write("    * 页面加载时根据租金测算方式显示控件是否可用\r\n");
      out.write("      1.没有选择租金测算方式时 所有控件禁用\r\n");
      out.write("      2.选择为 不规则 时  增删改 和 租金测算 可用 其他不可用\r\n");
      out.write("            增删改 功能中 租金调整值不能填写,其他必填,本金+利息=租金 校验\r\n");
      out.write("            增删改 动作完成 把JS变量 chenckCondiotn 赋值为false\r\n");
      out.write("      3.选择不为 不规则 时 修改 和 租金调整 可用 其他不可用\r\n");
      out.write("            修改功能只能输入 租金调整值 其他值不可输入\r\n");
      out.write("            修改 动作完成 把JS变量 chenckCondiotn 赋值为false\r\n");
      out.write("      4.测算类型为合同层时 资金计划修改能用,项目层时不可用\r\n");
      out.write("    */\r\n");
      out.write("    function reckonMultiTable(settleMethod){\r\n");
      out.write("    \trentPlanMultiTable(settleMethod);\r\n");
      out.write("    \tfundPlanMultiTable();\r\n");
      out.write("    }\r\n");
      out.write("\t//设置资金计划表的控制    \r\n");
      out.write("    function fundPlanMultiTable(settleMethod){\r\n");
      out.write("    \tif(!settleMethod){\r\n");
      out.write("        \tsettleMethod='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${requestScope[\"framework_condition.process\"]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("';\r\n");
      out.write("        }\r\n");
      out.write("    \tvar fundPlan=getTracywindyObject('table_id_table_leasing_fund_fund_charge_container');\r\n");
      out.write("    \tif(fundPlan){\r\n");
      out.write("\t    \tif(settleMethod.indexOf(\"con\")<0){\r\n");
      out.write("\t        \t//fundPlan.disabledToolsByText(\"修改\");\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\t//fundPlan.enabledToolsByText(\"修改\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("    \t}\r\n");
      out.write("    }\r\n");
      out.write("    //设置租金计划表中的控制\r\n");
      out.write("    function rentPlanMultiTable(settleMethod){\r\n");
      out.write("    \tif(!settleMethod){\r\n");
      out.write("    \t\tvar settle_method=jQuery(\"#settleMethod\").val();\r\n");
      out.write("        \tsettleMethod=settle_method?settle_method:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty requestScope['framework_condition.settlemethod']?'even_rent':requestScope['framework_condition.settlemethod'] }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\";\r\n");
      out.write("        }\r\n");
      out.write("        var rentPlan=getTracywindyObject('table_id_table_leasing_rent_plan_container');\r\n");
      out.write("        if(settleMethod==''){\r\n");
      out.write("        \trentPlan.disabledToolsByText(\"新增,修改,删除,租金测算,租金调整\");\r\n");
      out.write("        \trentPlan=getTracywindyObject('multiTable_id_table_leasing_rent_plan_container');\r\n");
      out.write("        \trentPlan.setReadOnly(true,\"rentlist\");\r\n");
      out.write("        \trentPlan.setReadOnly(true,\"plandate\");\r\n");
      out.write("        \trentPlan.setReadOnly(true,\"rent\");\r\n");
      out.write("        \trentPlan.setReadOnly(true,\"corpus\");\r\n");
      out.write("        \trentPlan.setReadOnly(true,\"interest\");\r\n");
      out.write("        \trentPlan.setReadOnly(true,\"corpusbusiness\");\r\n");
      out.write("        \trentPlan.setReadOnly(true,\"interestbusiness\");\r\n");
      out.write("        \trentPlan.setReadOnly(true,\"rentadjust\");\r\n");
      out.write("        }else if('irregular_rent'!= settleMethod){\r\n");
      out.write("        \trentPlan.disabledToolsByText(\"新增,删除,租金测算\");\r\n");
      out.write("        \trentPlan.enabledToolsByText(\"修改,租金调整\");\r\n");
      out.write("        \trentPlan=getTracywindyObject('multiTable_id_table_leasing_rent_plan_container');\r\n");
      out.write("        \trentPlan.setReadOnly(true,\"rentlist\");\r\n");
      out.write("        \trentPlan.setReadOnly(true,\"plandate\");\r\n");
      out.write("        \trentPlan.setReadOnly(true,\"rent\");\r\n");
      out.write("        \trentPlan.setReadOnly(true,\"corpus\");\r\n");
      out.write("        \trentPlan.setReadOnly(true,\"interest\");\r\n");
      out.write("        \trentPlan.setReadOnly(true,\"corpusbusiness\");\r\n");
      out.write("        \trentPlan.setReadOnly(true,\"interestbusiness\");\r\n");
      out.write("        \trentPlan.setReadOnly(false,\"rentadjust\");\r\n");
      out.write(" \t\t }else{//不规则可写\r\n");
      out.write("        \trentPlan.disabledToolsByText(\"租金调整\");\r\n");
      out.write("        \trentPlan.enabledToolsByText(\"新增,修改,删除,租金测算\");\r\n");
      out.write("        \trentPlan=getTracywindyObject('multiTable_id_table_leasing_rent_plan_container');\r\n");
      out.write("        \trentPlan.setReadOnly(false,\"rentlist\");\r\n");
      out.write("        \trentPlan.setReadOnly(false,\"plandate\");\r\n");
      out.write("        \trentPlan.setReadOnly(false,\"rent\");\r\n");
      out.write("        \trentPlan.setReadOnly(false,\"corpus\");\r\n");
      out.write("        \trentPlan.setReadOnly(false,\"interest\");\r\n");
      out.write("        \trentPlan.setReadOnly(false,\"corpusbusiness\");\r\n");
      out.write("        \trentPlan.setReadOnly(false,\"interestbusiness\");\r\n");
      out.write("        \trentPlan.setReadOnly(true,\"rentadjust\");\r\n");
      out.write(" \t\t }\r\n");
      out.write("    }\r\n");
      out.write("\t//租金测算\r\n");
      out.write("    function conditionReckon(){\r\n");
      out.write("    \tjQuery('#reckonType').val(\"condition\");\r\n");
      out.write("    \tvar submitConditionForm =document.getElementById(\"id_submitFrameworkConditionForm\");\r\n");
      out.write("\t\tvar isPassed = Validator.Validate(submitConditionForm,1,false);\r\n");
      out.write("\t\tif(isPassed){\r\n");
      out.write("\t\t\tif(!checkSubmit()){return false;};\r\n");
      out.write("\t\t    \trentCalculateSubmit('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/leasing/rentCalculateOld.action');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t//合同审批判断死否做过租金测算\r\n");
      out.write("\t\tcontract_approval=true;\r\n");
      out.write("    }\r\n");
      out.write("    //不规则租金计划修改\r\n");
      out.write("    function rentPlanReckon(){\r\n");
      out.write("    \tvar fundRentPlan = getTracywindyObject('table_id_table_leasing_rent_plan_container');\r\n");
      out.write("    \tjQuery('#id_json_fund_rent_plan_str').val(JsonUtil.encode(fundRentPlan.getRowsJsonData())) ;\r\n");
      out.write("    \tjQuery('#reckonType').val(\"plan\");\r\n");
      out.write("    \trentCalculateSubmit(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/leasing/rentCalculateOld.action\");\r\n");
      out.write("    }\r\n");
      out.write("    //租金计划调整\r\n");
      out.write("    function rentPlanAdjust(){\r\n");
      out.write("        var fundRentPlan = getTracywindyObject('table_id_table_leasing_rent_plan_container');\r\n");
      out.write("    \tjQuery('#id_json_fund_rent_plan_str').val(JsonUtil.encode(fundRentPlan.getRowsJsonData())) ;\r\n");
      out.write("    \tjQuery('#reckonType').val(\"adjust\");\r\n");
      out.write("    \trentCalculateSubmit(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/leasing/rentCalculateOld.action\");\r\n");
      out.write("    }\r\n");
      out.write("    //租金测算相关多行赋值\r\n");
      out.write("    function saveReckonJsonValue(){\r\n");
      out.write("        try{\r\n");
      out.write("\t    \t//商务条件数据\r\n");
      out.write("\t\t\tvar rentPlan = getTracywindyObject('table_id_table_leasing_rent_plan_container');//合同租金计划\r\n");
      out.write("\t\t\tjQuery('#id_json_fund_rent_plan_str').val(JsonUtil.encode(rentPlan.getRowsJsonData()));\r\n");
      out.write("\t\t\tvar fundCashFlow = getTracywindyObject('table_id_table_leasing_fund_cash_flow_container');//合同现金流\r\n");
      out.write("\t\t\tjQuery('#id_json_fund_cash_flow_str').val(JsonUtil.encode(fundCashFlow.getRowsJsonData()));\r\n");
      out.write("\t\t\tvar fundChargePlan = getTracywindyObject('table_id_table_leasing_fund_fund_charge_container');//合同资金计划\r\n");
      out.write("\t    \tif(typeof(fundChargePlan)=='object'){\r\n");
      out.write("\t\t\t\tjQuery('#id_json_fund_fund_charge_str').val(JsonUtil.encode(fundChargePlan.getRowsJsonData()));\r\n");
      out.write("\t    \t}\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("        }catch (e){\r\n");
      out.write("            alert('保存租金测算结果出错['+e+']!');\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    //德银不需要的内容隐藏\r\n");
      out.write("    jQuery('#deewinflspecial').hide();\r\n");
      out.write("    //只读页面不显示测算按钮\r\n");
      out.write("    if(isViewHistoryTask){\r\n");
      out.write("    \tjQuery('#btn_rent_cal').hide();\r\n");
      out.write("    }\r\n");
      out.write("  //起租是反转只读\r\n");
      out.write("    function conditionOnHire(){\r\n");
      out.write("    \tformJSPInputHideOrShow(\"onHireProcessDataTR\",\"framework_condition.yearrate\",1);\r\n");
      out.write("    \tjQuery('#btn_rent_cal').show();\r\n");
      out.write("    }\r\n");
      out.write("    function checkEquipMoney(){\r\n");
      out.write("    \t//计算租赁物的总交易价格\r\n");
      out.write("\t\tvar currentTable = getTracywindyObject('table_id_table_leasing_proj_equip_container');\r\n");
      out.write("\t\tvar data = currentTable.tableData;\r\n");
      out.write("\t\tvar totalPrice = 0;\r\n");
      out.write("\t\tfor(var i=0;i<data.length;i++){\r\n");
      out.write("\t\t\ttotalPrice += parseFloat(data[i]['nowtotal']);\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tvar equipAmt = parseFloat($(\"#equipAmt\").val());\r\n");
      out.write("\t\tif(totalPrice !=  equipAmt){//如果不相等，则跳出执行\r\n");
      out.write("\t\t\talert(\"【租赁物明细】标签的合计总价[\"+ totalPrice + \"]和【拟商务条件】标签中的设备款[\"+ equipAmt +\"]不相等,请检查.\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} else{\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}\r\n");
      out.write("    }\r\n");
      out.write("    </script>\r\n");
      if (_jspx_meth_permission_005faction_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_permission_005faction_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  permission:action
    com.kernal.tags.ActionPermissionTag _jspx_th_permission_005faction_005f0 = (com.kernal.tags.ActionPermissionTag) _005fjspx_005ftagPool_005fpermission_005faction_0026_005fcode.get(com.kernal.tags.ActionPermissionTag.class);
    _jspx_th_permission_005faction_005f0.setPageContext(_jspx_page_context);
    _jspx_th_permission_005faction_005f0.setParent(null);
    // /WEB-INF/jsps/solutions/workflow/forms/rent_reckon/rent_reckon/condition_frame.jsp(606,0) name = code type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_permission_005faction_005f0.setCode("irr_no_purview");
    int _jspx_eval_permission_005faction_005f0 = _jspx_th_permission_005faction_005f0.doStartTag();
    if (_jspx_eval_permission_005faction_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_permission_005faction_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_permission_005faction_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_permission_005faction_005f0.doInitBody();
      }
      do {
        out.write("\r\n");
        out.write("<script type=\"text/javascript\">\r\n");
        out.write("//jQuery('#irr_no_purview_irr').hide();//经销商不可见\r\n");
        out.write("jQuery('#irr_no_purview_irr').html('');//经销商不可见\r\n");
        out.write("jQuery('#irr_no_purview_irr_content').html('');//经销商不可见\r\n");
        out.write("</script >\r\n");
        int evalDoAfterBody = _jspx_th_permission_005faction_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_permission_005faction_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_permission_005faction_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fpermission_005faction_0026_005fcode.reuse(_jspx_th_permission_005faction_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fpermission_005faction_0026_005fcode.reuse(_jspx_th_permission_005faction_005f0);
    return false;
  }
}
