package org.apache.jsp.WEB_002dINF.jsps.solutions.workflow.forms.fund.fund_005fcollection;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kernal.utils.FileUtil;
import com.kernal.utils.WebUtil;

public final class flow_005fopenlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.List<java.lang.String> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.List<java.lang.String> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>收款</title>\r\n");
      out.write("    <!--css sheet-->\r\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/dtree/dtree.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/jquery-easyui/easyui.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/jquery-easyui/icon.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/tracywindy/tracywindy.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/tracywindy/button.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/tracywindy/workFlowUtil.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t<!--javascript libray-->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/workFlowUtil.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyUtils.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyJsonUtil.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyAjax.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery/jquery.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery/jquery.easyui.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyLoadMask.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyTable.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyComboBox.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindySerializeFormToJsonObject.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/my97DatePicker/WdatePicker.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/validator.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyOperationTable.js\"></script>\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t   html,body{\r\n");
      out.write("\t     overflow:hidden;\r\n");
      out.write("\t   }\r\n");
      out.write("\t</style>\r\n");
      out.write("<script type=\"text/javascript\"> \r\n");
      out.write("//var proj_id=\"");
      out.print( request.getParameter("id"));
      out.write("\";\r\n");
      out.write("var param={};\r\n");
      out.write("//if(proj_id!=\"null\" || proj_id==\"\"){param.proj_id=proj_id;}\r\n");
      out.write("\tvar pageWidth  = document.documentElement.clientWidth-2;\r\n");
      out.write("\tvar pageHeight = document.documentElement.clientHeight-2;\r\n");
      out.write("\t\r\n");
      out.write("\tvar attachmentParams;\r\n");
      out.write("\tjQuery(function(){\r\n");
      out.write("\t var table = new tracywindyOperationTable({\r\n");
      out.write("\t\t tableComment:'[合同收款信息]',\r\n");
      out.write("\t\t constantFlagTable:'ProjInfo',\r\n");
      out.write("\t\t windowTop:20,\r\n");
      out.write("\t     border:true,\r\n");
      out.write("      renderTo:'id_tableContainer',\r\n");
      out.write("      title:'合同收款信息',\r\n");
      out.write("      width:parseInt(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.tableWidth}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\")||pageWidth,\r\n");
      out.write("      height:parseInt(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.tableHeight}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\")||pageHeight,\r\n");
      out.write("      id:'id_table',\r\n");
      out.write("      xmlFileName:'\\\\eleasing\\\\workflow\\\\contract\\\\contract_flowopen_list.xml',\r\n");
      out.write("      loadMode:'ajax',\r\n");
      out.write("      params:{\r\n");
      out.write("\t\t CONTRACT_STATUS_LessThan : 100, \r\n");
      out.write("\t      \tCONTRACT_STATUS_GreaterThan : 15,\r\n");
      out.write("\t      \tuserId:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginUser.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("',\r\n");
      out.write("\t      \ttotal:'1'\r\n");
      out.write("\t\t\t},\r\n");
      out.write("      isPage:true,\r\n");
      out.write("      operButtons:' ',\r\n");
      out.write("      isFit:false,\r\n");
      out.write("      tools:[{\r\n");
      out.write("     \t html : '<font color=\"red\">收款</font>',\r\n");
      out.write("\t\t handler : function(table) {\r\n");
      out.write("\t\t\t\tvar projIDValue = table.getCheckedRowDatas();\r\n");
      out.write("\t\t\t\tif (0 == projIDValue.length) {\r\n");
      out.write("\t\t\t\t\talert(\"请选择需要启动的流程！\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tattachmentParams = \"cust_id=\"+projIDValue[0].custid+\"&contract_id=\" + projIDValue[0].id ;\r\n");
      out.write("\t\t\t\tvar custdealerid = projIDValue[0].custdealerid;\r\n");
      out.write("\t\t\t\tvar param_ = {};\r\n");
      out.write("\t\t\t\tparam_.hasMoney = '0';\r\n");
      out.write("\t\t\t\tif(custdealerid){\r\n");
      out.write("\t\t\t\t\tparam_.custid = custdealerid;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tvar table_ebank = getTracywindyObject('table_ebank');\r\n");
      out.write("\t\t\t\ttable_ebank.setParams(param_);\r\n");
      out.write("\t\t\t\ttable_ebank.reload();\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tjQuery(\"#ebank\").show();\r\n");
      out.write("\t\t\t\tjQuery(\"#ebank\").window({\r\n");
      out.write("\t\t\t\t\t   top:10\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\tjQuery(\"#ebank\").window(\"open\");\r\n");
      out.write("\t\t\t\t//startProcess(\"收款流程-4\",attachmentParams);\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\ticonCls :'icon-update'\r\n");
      out.write("          },\r\n");
      out.write("          {\r\n");
      out.write("          \t html : '<font color=\"red\">红冲</font>',\r\n");
      out.write("     \t\t handler : function(table) {\r\n");
      out.write("     \t\t\t\tvar projIDValue = table.getCheckedRowDatas();\r\n");
      out.write("     \t\t\t\tif (0 == projIDValue.length) {\r\n");
      out.write("     \t\t\t\t\talert(\"请选择需要启动的流程！\");\r\n");
      out.write("     \t\t\t\t\treturn false;\r\n");
      out.write("     \t\t\t\t}\r\n");
      out.write("     \t\t\t\tif (projIDValue[0].shebeimoney > 0){\r\n");
      out.write("     \t\t\t\t\talert(\"资金已投放不允许红冲!\");\r\n");
      out.write("     \t\t\t\t\treturn false;\r\n");
      out.write("     \t\t\t\t}else{\r\n");
      out.write("\t     \t\t\t\tattachmentParams = \"cust_id=\"+projIDValue[0].custid+\"&contract_id=\" + projIDValue[0].id+\"&feetype=red\";\r\n");
      out.write("\t     \t\t\t\tvar custdealerid = projIDValue[0].custdealerid;\r\n");
      out.write("\t     \t\t\t\tvar param_ = {};\r\n");
      out.write("\t     \t\t\t\tparam_.hasMoney = '0';\r\n");
      out.write("\t     \t\t\t\tif(custdealerid){\r\n");
      out.write("\t     \t\t\t\t\tparam_.custid = custdealerid;\r\n");
      out.write("\t     \t\t\t\t}\r\n");
      out.write("\t     \t\t\t\tstartProcess(\"收款流程-1\",attachmentParams);\r\n");
      out.write("     \t\t\t\t}\r\n");
      out.write("     \t\t\t},\r\n");
      out.write("     \t\t\ticonCls :'icon-update'\r\n");
      out.write("               },\r\n");
      out.write("          {\r\n");
      out.write("\t\t\t\tisHtml : true,\r\n");
      out.write("\t\t\t\thtml : '选择显示合同信息：'\r\n");
      out.write("\t\t  }, {\r\n");
      out.write("\t\t\t\tisHtml : true,\r\n");
      out.write("\t\t\t\thtml : '<div id=\"id_flow_name\" style=\"float:left;\"></div>'\r\n");
      out.write("\t\t\t}\r\n");
      out.write("          ],\r\n");
      out.write("      columns:[\r\n");
      out.write("\t\t            {header:'id',name:'id',hidden:true},\r\n");
      out.write("\t\t            {header:'proj_id',name:'proj_id',hidden:true},\r\n");
      out.write("\t\t            {header:'pid',name:'pid',hidden:true},\r\n");
      out.write("\t\t            {header:'custid',name:'custid',hidden:true},\r\n");
      out.write("\t\t            {header:'typecode',name:'typecode',hidden:true},\r\n");
      out.write("\t\t            {header:'业务类别',name:'businesstype'},\r\n");
      out.write("\t\t            {header:'客户名称',name:'custname',queryConfig:{}},\r\n");
      out.write("\t\t            {header:'经销商名称',name:'custdealer',queryConfig:{}},\r\n");
      out.write("\t\t            {header:'合同编号',name:'contractid',queryConfig:{}},\r\n");
      out.write("\t\t            {header:'业务合同号',name:'contractnumber'},\r\n");
      out.write("\t\t            {header:'设备款',name:'shebeimoney',hidden:true},\r\n");
      out.write("\t\t            {header:'项目名称',name:'projname',width:300,queryConfig:{isNewLine:true}},\r\n");
      out.write("\t\t            {header:'活动类型',name:'projtype'},\r\n");
      out.write("\t\t            {header:'项目来源',name:'projsource'},\r\n");
      out.write("\t\t            //{header:'项目规模',name:'projscale'},\r\n");
      out.write("\t\t            {header:'资产分类',name:'industrytype'},\r\n");
      out.write("\t\t            {header:'租赁形式',name:'leasform'},\r\n");
      out.write("\t\t            {header:'业务模式',name:'businessmode'},\r\n");
      out.write("\t\t            {header:'客户经理',name:'projmanage'}\r\n");
      out.write("      ]\r\n");
      out.write("\t });\r\n");
      out.write("\t var combo_type = new tracywindyComboBox({\r\n");
      out.write("\t\t\tid : 'id_combo_flow_name',\r\n");
      out.write("\t\t\twidth : 200,\r\n");
      out.write("\t\t\trenderTo : 'id_flow_name',\r\n");
      out.write("\t\t\tloadMode : 'local',\r\n");
      out.write("\t\t\treadOnly : false,\r\n");
      out.write("\t\t\tisAjaxLenovo : true,\r\n");
      out.write("\t\t\tisContainEmpty : false,\r\n");
      out.write("\t\t\tdropListHeight : 300,\r\n");
      out.write("\t\t\ttopAdd : 0,\r\n");
      out.write("\t\t\tleftAdd : 0,\r\n");
      out.write("\t\t\tpositionDropIconLeftAdd : -1,\r\n");
      out.write("\t\t\tvalue:'1',\r\n");
      out.write("\t\t\tname : 'flow_name',\r\n");
      out.write("\t\t\tdisplayField : 'name',\r\n");
      out.write("\t\t\tvalueField : 'value',\r\n");
      out.write("\t\t\tdatas : [ \r\n");
      out.write("\t\t\t    {\r\n");
      out.write("\t\t\t\tname : '未收完合同',\r\n");
      out.write("\t\t\t\tvalue : '1'\r\n");
      out.write("\t\t\t    },{\r\n");
      out.write("\t\t\t\t\tname : '全部合同',\r\n");
      out.write("\t\t\t\t\tvalue : ''\r\n");
      out.write("\t\t\t\t}],\r\n");
      out.write("\t\t\tonSelect : function(combo) {\r\n");
      out.write("\t\t\t\tvar table = getTracywindyObject('id_table');\r\n");
      out.write("\t\t\t\t//alert(table);\r\n");
      out.write("\t\t\t\t table.setParams({\r\n");
      out.write("\t                    total: combo.getValue()\r\n");
      out.write("\t                });\r\n");
      out.write("\t                table.reload();\r\n");
      out.write("\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("});\r\n");
      out.write("\tjQuery(function(){\r\n");
      out.write("\t   \t new tracywindyOperationTable({\r\n");
      out.write("\t   \t\t tableComment:'[网银信息]',\r\n");
      out.write("\t   \t\t constantFlagTable:'fundebank',\r\n");
      out.write("\t   \t\t windowTop:20,\r\n");
      out.write("\t   \t     border:true,\r\n");
      out.write("\t         renderTo:'id_ebank',\r\n");
      out.write("\t         title:'网银信息',\r\n");
      out.write("\t         width:(parseInt(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.tableWidth}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\")||pageWidth) - 300,\r\n");
      out.write("\t         height:(parseInt(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.tableHeight}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\")||pageHeight)-140,\r\n");
      out.write("\t         id:'table_ebank',\r\n");
      out.write("\t         //xmlFileName:'eleasing/jsp/fund_collection/fund_ebank_info_collection.xml',\r\n");
      out.write("\t         xmlFileName:'eleasing/jsp/fund_ebank/fund_ebank_info.xml',\r\n");
      out.write("\t         displayToggleContainer:\"ebank\",\r\n");
      out.write("\t         loadMode:'ajax',\r\n");
      out.write("\t         isPage:true,\r\n");
      out.write("\t         operButtons:' ',\r\n");
      out.write("\t         isFit:true,\r\n");
      out.write("\t         operButtons:' ',\r\n");
      out.write("\t         params:{\r\n");
      out.write("\t        \t enabled:0\r\n");
      out.write("\t\t\t },\r\n");
      out.write("\t         //params : param_,\r\n");
      out.write("\t         tools:[{\r\n");
      out.write("\t         \t html : '<font color=\"red\">收款</font>',\r\n");
      out.write("\t \t\t\thandler : function(table) {\r\n");
      out.write("\t \t\t\t\tvar projIDValue = table.getCheckedRowDatas();\r\n");
      out.write("\t \t\t\t\tif (0 == projIDValue.length) {\r\n");
      out.write("\t \t\t\t\t\talert(\"请选择需要的网银\");\r\n");
      out.write("\t \t\t\t\t\treturn false;\r\n");
      out.write("\t \t\t\t\t}\r\n");
      out.write("\t \t\t\t\t\r\n");
      out.write("\t \t\t\t\tattachmentParams = attachmentParams + \"&ebank_id=\" +projIDValue[0].id ;\r\n");
      out.write("\t\t \t\t\tstartProcess(\"收款流程-1\",attachmentParams);\r\n");
      out.write("\t \r\n");
      out.write("\t \t\t\t},\r\n");
      out.write("\t \t\t\ticonCls :'icon-update'\r\n");
      out.write("\t           }],\r\n");
      out.write("\t         isFit:false,\r\n");
      out.write("\t         columns:[\r\n");
      out.write("\t                    {header:'id',name:'id',hidden:true},\r\n");
      out.write("\t                    {header:'custdealerid',name:'custdealerid',hidden:true},\r\n");
      out.write("\t\t\t            {header:'网银编号',name:'ebdataid',queryConfig:{}},\r\n");
      out.write("\t\t\t            {header:'经销商',name:'custname'},\r\n");
      out.write("\t\t\t            {header:'付款人',name:'clientname',queryConfig:{}},\r\n");
      out.write("\t\t\t            {header:'本方银行',name:'ownbank',hidden:true},\r\n");
      out.write("\t\t\t            {header:'本方账户',name:'ownaccount',hidden:true},\r\n");
      out.write("\t\t\t            {header:'本方账号',name:'ownaccnumber',hidden:true},\r\n");
      out.write("\t\t\t            {header:'对方银行',name:'clientbank',hidden:true},\r\n");
      out.write("\t\t\t            {header:'对方账户',name:'clientaccount',hidden:true},\r\n");
      out.write("\t\t\t            {header:'对方账号',name:'clientaccnumber',hidden:true},\r\n");
      out.write("\t\t\t            {header:'到账金额类型',name:'moneytype',hidden:true},\r\n");
      out.write("\t\t\t            {header:'到账金额',name:'factmoney',queryConfig:{isNewLine:true}},\r\n");
      out.write("\t\t\t            //{header:'与系统无关金额',name:'nowithmoney'},\r\n");
      out.write("\t\t\t            {header:'已核销金额',name:'hiremoney'},\r\n");
      out.write("\t\t\t            {header:'可核销金额',name:'owmoney'},\r\n");
      out.write("\t\t\t            {header:'到账时间',name:'factdate'},\r\n");
      out.write("\t\t\t            {header:'流水号',name:'sn'},\r\n");
      out.write("\t\t\t            {header:'备注',name:'summary',queryConfig:{}},\r\n");
      out.write("\t\t\t            //{header:'登记人',name:'creator_name'},\r\n");
      out.write("\t\t\t            //{header:'登记时间',name:'create_date'}\r\n");
      out.write("\t\t        ]\r\n");
      out.write("\t   \t });\r\n");
      out.write("\t   });\r\n");
      out.write(" </script>\r\n");
      out.write(" \r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"id_tableContainer\"></div>\r\n");
      out.write("\t    <div id=\"ebank\" style=\"display: none;overflow:hidden;\" title=\"选择网银\">\r\n");
      out.write("\t    \t<div id=\"id_ebank\"></div>\r\n");
      out.write("    </div>\r\n");
      out.write("\t<script type='text/javascript'>\r\n");
      out.write("\t    var ebankDom =document.getElementById(\"ebank\");\r\n");
      out.write("\t    ebankDom.style.height= ((parseInt(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.tableHeight}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\")||pageHeight) - 100)+\"px\";\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
