package org.apache.jsp.WEB_002dINF.jsps.solutions.leasing.cust_005finfo.cust_005fdealer;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kernal.utils.FileUtil;
import com.kernal.utils.WebUtil;

public final class cust_005fdealer_005flist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.List<java.lang.String> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList<java.lang.String>(1);
    _jspx_dependants.add("/WEB-INF/tlds/permission.tld");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fpermission_005faction_0026_005fcode;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.List<java.lang.String> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fpermission_005faction_0026_005fcode = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    if (_005fjspx_005ftagPool_005fpermission_005faction_0026_005fcode != null) _005fjspx_005ftagPool_005fpermission_005faction_0026_005fcode.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>经销商 - 经销商管理</title>\r\n");
      out.write("    <!--css sheet-->\r\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/dtree/dtree.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/jquery-easyui/easyui.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/jquery-easyui/icon.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/tracywindy/tracywindy.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/tracywindy/button.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/tracywindy/workFlowUtil.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t<!--javascript libray-->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/workFlowUtil.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyUtils.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyJsonUtil.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyAjax.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery/jquery.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery/jquery.easyui.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyLoadMask.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyTable.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyComboBox.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindySerializeFormToJsonObject.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/my97DatePicker/WdatePicker.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/validator.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyOperationTable.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/MustFillIn.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/custType.js\"></script>\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t   html,body{\r\n");
      out.write("\t     overflow:hidden;\r\n");
      out.write("\t   }\r\n");
      out.write("\t   td.td-content{\r\n");
      out.write("\t     text-align:left;\r\n");
      out.write("\t   }\r\n");
      out.write("\t   td.td-content input{\r\n");
      out.write("\t      width:165px;\r\n");
      out.write("\t      float:left;\r\n");
      out.write("\t      border:1px solid #DDD;\r\n");
      out.write("\t   }\r\n");
      out.write("\t   td.td-content textarea{\r\n");
      out.write("\t      width:90%;\r\n");
      out.write("\t      overflow:auto;\r\n");
      out.write("\t      float:left;\r\n");
      out.write("\t      border:1px solid #DDD;\r\n");
      out.write("\t   }\r\n");
      out.write("\t</style>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("var isAdmin=false;\r\n");
      out.write("var operButtons='';\r\n");
      out.write("</script >\r\n");
      if (_jspx_meth_permission_005faction_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_permission_005faction_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar constantFlagTable = \"User\";\r\n");
      out.write("\tvar pageWidth  = document.documentElement.clientWidth-2;\r\n");
      out.write("\tvar pageHeight = document.documentElement.clientHeight-2;\r\n");
      out.write("\tjQuery(function(){\r\n");
      out.write("\r\n");
      out.write("\t\tdictOnSelect('ownerdistrictname','ownerdistrict','dealer_district',null,null,'require=\"true\" label=\"所属区域\"');\r\n");
      out.write("\t\tdictOnSelect('ownerofficename','owneroffice','owner_office',null,null,'label=\"办事处\"');\r\n");
      out.write("\t\tdictOnSelect('shoptypename','shoptype','dealer_shop_type',null,null,'label=\"店面类型\"');\t\t\r\n");
      out.write("\t\tdictOnSelect('cooperatestatusname','cooperatestatus','dealer_symbiosis',null,null,'require=\"true\" label=\"合作状态\"');\r\n");
      out.write("\t\tcommonSelectOverall('provincename',\"(select id,name from t_district where pid in('HB','DB','HD','HZ','XN','XB','HN','TQ')) rs\",'id',\"name\",'province','','','require=\"true\" label=\"省份\"', function(combo,data){ choseNext(combo,'id_combo_cityname','t_district');},true);//省份\r\n");
      out.write("\t\tcommonSelectOverall('cityname',\"(select id,name from t_district where 1=2) rs\",'id',\"name\",'city','','','require=\"true\" label=\"城市\"', function(combo,data){ choseNext(combo,'id_combo_countyname','t_district');},true);//城市\r\n");
      out.write("\t\tcommonSelectOverall('countyname',\"(select id,name from t_district where 1=2) rs\",'id',\"name\",'county','','','require=\"true\" label=\"区县\"',null,true);//地区\r\n");
      out.write("\t\tdictOnSelect('ownershipname','ownership','ownership',null,null,'label=\"企业性质\"');//企业性质\r\n");
      out.write("\t\tdictOnSelect('taxlevelname','taxlevel','tax_level_name',null,null,'label=\"纳税人类别\"');//纳税人\r\n");
      out.write("\t\tdictYesOrNoByCode('isassociatedname','isassociated',null,null,true,'label=\"是否与本企业关联\"');//是否与本企业关联\r\n");
      out.write("\t\tdictYesOrNoByCode('draftname','draft',null,null,null,'label=\"是否草稿\"');//是否草稿\r\n");
      out.write("\t\tdictYesOrNoByCode('is4sname','is4s',null,null,null,'require=\"true\" label=\"是否4S\"');//是否4S\r\n");
      out.write("\t\tdictOnSelect('custscalename','custscale','cust_scale',null,null,'label=\"客户规模\"');//客户规模\r\n");
      out.write("\t\tdictOnSelect('reditorrightname','reditorright','reditor_right',null,null,'label=\"债权性质\"');//债权性质\r\n");
      out.write("\t\tdictOnSelect('assurorrightname','assurorright','assuror_right',null,null,'label=\"担保性质\"');//担保性质\r\n");
      out.write("\t\tcommonSelect('creatordeptname','t_depts','id_','name_','creatordept','");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope[\"loginUserDeptObj\"].id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("',null, 'require=\"true\" label=\"登记人部门\"',false);\r\n");
      out.write("\t\tdictYesOrNoByCode('twolevelstatusname','twolevelstatus',null,null,true,'label=\"是否是二级经销商\"');//是否是二级经销商\r\n");
      out.write("\t\tnew tracywindyComboBox({\r\n");
      out.write("\t\t\tid : 'id_combo_id_onelevelname',\r\n");
      out.write("\t\t\twidth : 167,\r\n");
      out.write("\t\t\trenderTo : 'onelevelname',\r\n");
      out.write("\t\t\txmlFileName : '\\\\eleasing\\\\workflow\\\\public\\\\SimpleCustSelect.xml',\r\n");
      out.write("\t\t\tloadMode : 'ajax',\r\n");
      out.write("\t\t\treadOnly : false,\r\n");
      out.write("\t\t\tisAjaxLenovo : true,\r\n");
      out.write("\t\t\totherAttributes:'label=\"所属一级经销商\"',\r\n");
      out.write("\t\t\ttopAdd : 0,\r\n");
      out.write("\t\t\tleftAdd : 0,\r\n");
      out.write("\t\t\tpositionDropIconLeftAdd : -1,\r\n");
      out.write("\t\t\tname : 'onelevel',\r\n");
      out.write("\t\t\tdisplayField : 'name',\r\n");
      out.write("\t\t\tvalueField : 'id',\r\n");
      out.write("\t\t\tvalue:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope['currentDealerCustInfoId']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\",\r\n");
      out.write("\t\t\trawValue:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope['currentDealerCustInfoName']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\",\r\n");
      out.write("\t\t\tparams : {\r\n");
      out.write("\t\t\t\tcust_class:'CUST_INFO_DEALER',\r\n");
      out.write("\t\t\t\tcooperate_status:'dealer_symbiosis1',\r\n");
      out.write("\t\t\t\tdealer_id:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope['currentDealerCustInfoId']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t//加载页面列表\r\n");
      out.write("\t   \t var table = new tracywindyOperationTable({\r\n");
      out.write("   \t\t resetFormCallback:function(table,$form,operFlag){\r\n");
      out.write("\t\t\tif(\"add\" == operFlag){\r\n");
      out.write("\t\t\t\tgetTracywindyObject(\"id_combo_draftname\").readOnlyData = false;\r\n");
      out.write("   \t   \t  \t\tgetTracywindyObject(\"id_combo_draftname\").reload();\r\n");
      out.write("\t\t\t\tgetTracywindyObject(\"id_combo_draftname\").setRawValue(\"否\");\r\n");
      out.write("\t\t\t\tgetTracywindyObject(\"id_combo_draftname\").setValue(\"1\");\r\n");
      out.write("\t\t\t\tjQuery(\"#invalidname\").val(\"否\");\r\n");
      out.write("\t\t\t\tjQuery(\"#invalid\").val(\"1\");\r\n");
      out.write("\t\t\t\tjQuery(\"#creatorname\").val('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.loginUser.realname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("');\r\n");
      out.write("\t \t\t\tMustFillIn.setRequire([\"custname\",\"orgcode\",\"rawValue_province\",\"rawValue_creatordept\",\"regdate\",\"regcapital\",\"rawValue_is4s\",\"incomeassets\",\"cooperationdate\",\"rawValue_city\",\"rawValue_county\",\"postcode\",\"netassets\",\"ownershipstructure\",\"ownervehicle\",\"ownerestate\",\"ownerland\",\"ownershiptotal\"]);\r\n");
      out.write("\t\t\t\tMustFillIn.GoCheck(document.getElementById(\"id_detailInfoForm\"));\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t   \t   \t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t//if(\"update\" == operFlag){\r\n");
      out.write("\t\t\t\t//MustFillIn.setRequire([\"orgcode\",\"rawValue_province\",\"rawValue_city\",\"rawValue_county\",\"postcode\",\"mobilenumber\",\"phone\"]);//默认承租人\r\n");
      out.write("\t\t\t\t//MustFillIn.GoCheck(document.getElementById(\"id_detailInfoForm\"));\r\n");
      out.write("\t\t\t\t//}\r\n");
      out.write("   \t     },\r\n");
      out.write("   \t\t loadFormDataCallBack:function(table,$form,rowIndex){\r\n");
      out.write("   \t\t\tvar twolevelstatusname=getTracywindyObject(\"id_combo_twolevelstatusname\").getValue();\r\n");
      out.write("   \t\t\tif(twolevelstatusname==\"0\"){\r\n");
      out.write("   \t\t\t\tgetTracywindyObject(\"id_combo_twolevelstatusname\").setRawValue(\"是\");\r\n");
      out.write("   \t\t\t}else{\r\n");
      out.write("   \t\t\t\tgetTracywindyObject(\"id_combo_twolevelstatusname\").setRawValue(\"否\");\r\n");
      out.write("   \t\t\t}\r\n");
      out.write("\t\t\tvar rowData = table.getRowDataAt(rowIndex);\r\n");
      out.write("   \t\t\tgetTracywindyObject(\"id_combo_id_onelevelname\").setRawValue(rowData['onelevelname']);\r\n");
      out.write("\t\t\t \t\t\tvar objMappingArr = [\r\n");
      out.write("  \t\t\t                    {comboId:'provincename',rowDataMapping:'province'},\r\n");
      out.write(" \t\t\t                    {comboId:'cityname',rowDataMapping:'city',parentRowDataMapping:'province',tableName:'t_district'},\r\n");
      out.write(" \t\t\t                    {comboId:'countyname',rowDataMapping:'county',parentRowDataMapping:'city',tableName:'t_district'},\r\n");
      out.write(" \t\t\t                    {comboId:'ownershipname',rowDataMapping:'ownership'},\r\n");
      out.write(" \t\t\t                    {comboId:'taxlevelname',rowDataMapping:'taxlevel'},\r\n");
      out.write(" \t\t\t                    {comboId:'isassociatedname',rowDataMapping:'isassociated'},\r\n");
      out.write(" \t\t\t                    {comboId:'draftname',rowDataMapping:'draft'},\r\n");
      out.write(" \t\t\t                    {comboId:'reditorrightname',rowDataMapping:'reditorright'},\r\n");
      out.write(" \t\t\t                    {comboId:'assurorrightname',rowDataMapping:'assurorright'},\r\n");
      out.write(" \t\t\t                    {comboId:'creatordept',rowDataMapping:'creatordept'},\r\n");
      out.write(" \t\t\t                  \t{comboId:'cooperatestatusname',rowDataMapping:'cooperatestatus'},\r\n");
      out.write(" \t\t\t                  \t{comboId:'ownerdistrictname',rowDataMapping:'ownerdistrict'},\r\n");
      out.write(" \t\t\t                  \t{comboId:'ownerofficename',rowDataMapping:'owneroffice'},\r\n");
      out.write(" \t\t\t                  \t{comboId:'shoptypename',rowDataMapping:'shoptype'},\r\n");
      out.write(" \t\t\t                  \t{comboId:'custscalename',rowDataMapping:'custscale'},\r\n");
      out.write(" \t\t\t                  \t{comboId:'is4sname',rowDataMapping:'is4s'}\t\t\t                  \t\r\n");
      out.write(" \t\t\t                   \r\n");
      out.write(" \t\t\t                  ];\r\n");
      out.write("\t\t\t \t\t\tMustFillIn.setRequire([\"custname\",\"orgcode\",\"rawValue_province\",\"rawValue_creatordept\",\"regdate\",\"regcapital\",\"is4s\",\"incomeassets\",\"cooperationdate\",\"rawValue_city\",\"rawValue_county\",\"postcode\",\"netassets\",\"ownershipstructure\",\"ownervehicle\",\"ownerestate\",\"ownerland\",\"ownershiptotal\"]);//默认承租人\r\n");
      out.write("\t\t\t\t\t\tMustFillIn.GoCheck(document.getElementById(\"id_detailInfoForm\"));\r\n");
      out.write("\t\t\t\t\t\tfor(var j=0;j<objMappingArr.length;j++){\r\n");
      out.write("\t\t\t \t\t\t     var objMapping = objMappingArr[j];\r\n");
      out.write("\t\t\t \t\t\t     var parentRowDataMapping = objMapping['parentRowDataMapping'];\r\n");
      out.write("\t\t\t \t\t\t     var rowDataValue         = rowData[objMapping['rowDataMapping']];\r\n");
      out.write("\t\t\t \t\t\t     var comboId   =  (\"id_combo_\"+objMapping['comboId']);\r\n");
      out.write("\t\t\t \t\t\t     var currentCombo = getTracywindyObject(comboId);\r\n");
      out.write("\t\t\t \t\t\t     if(parentRowDataMapping){\r\n");
      out.write("\t\t\t \t\t\t\t     var parentRowDataMappingValue = rowData[parentRowDataMapping];\r\n");
      out.write("\t\t\t \t\t\t\t     var tableName = objMapping['tableName'];\r\n");
      out.write("\t\t\t \t\t\t\t     currentCombo.setParams({tableName:\"(select id,name from \"+tableName+\" where pid='\"+parentRowDataMappingValue+\"') rs \"}) ;\r\n");
      out.write("\t\t\t \t\t\t\t\t var loadCompleteFunc = (function(combo,rowDataValue){\r\n");
      out.write("\t\t\t \t\t\t\t\t\t       return function(combo){\r\n");
      out.write("\t\t\t \t\t\t\t\t\t    \t   combo.setValue(rowDataValue);\r\n");
      out.write("\t\t\t \t\t\t\t\t\t\t  };\r\n");
      out.write("\t\t\t \t\t\t\t\t })(currentCombo,rowDataValue);\r\n");
      out.write("\t\t\t \t\t\t\t\t currentCombo.loadComplete = loadCompleteFunc;\r\n");
      out.write("\t\t\t \t\t\t\t}else{\r\n");
      out.write("\t\t\t \t\t\t    \t\tcurrentCombo.setValue(rowDataValue);\r\n");
      out.write("\t\t\t \t\t\t   }\r\n");
      out.write("\t\t\t \t\t\t    currentCombo.reload();\r\n");
      out.write("\t\t\t \t\t\t }\r\n");
      out.write("\t\t\tif(getTracywindyObject(\"id_combo_draftname\").getValue()=='1'){//不是草稿的时候不能修改\r\n");
      out.write("   \t   \t  \t\t//getTracywindyObject(\"id_combo_draftname\").readOnlyData = true;\r\n");
      out.write("   \t   \t  \t\t//getTracywindyObject(\"id_combo_draftname\").reload();\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t\t\tgetTracywindyObject(\"id_combo_draftname\").readOnlyData = false;\r\n");
      out.write("   \t   \t  \t\tgetTracywindyObject(\"id_combo_draftname\").reload();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("    \t },\r\n");
      out.write("   \t\t tableComment:'[经销商管理]',\r\n");
      out.write("   \t\t constantFlagTable:'Distributor',\r\n");
      out.write("   \t\t windowTop:20,\r\n");
      out.write("   \t     border:true,\r\n");
      out.write("         renderTo:'id_tableContainer',\r\n");
      out.write("         title:'经销商管理',\r\n");
      out.write("         width:parseInt(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.tableWidth}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\")||pageWidth,\r\n");
      out.write("         height:parseInt(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.tableHeight}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\")||pageHeight,\r\n");
      out.write("         id:'id_table',\r\n");
      out.write("         xmlFileName:'/eleasing/jsp/dealer_manage/dealer_info.xml',\r\n");
      out.write("         loadMode:'ajax',\r\n");
      out.write("         isPage:true,\r\n");
      out.write("         isFit:false,\r\n");
      out.write("         operButtons:operButtons,\r\n");
      out.write("         enabledPromit:'有效',\r\n");
      out.write("         disabledPromit:'无效',\r\n");
      out.write("         enabledDefaultValue:'1',\r\n");
      out.write("         isNeedEnabled:isAdmin,\r\n");
      out.write("         isNeedEnabled:true,\r\n");
      out.write("         isAutoBreakContent:true,\r\n");
      out.write("         isExcel : true,\r\n");
      out.write("         lockedNames:['custname'],\r\n");
      out.write("         columns:[\r\n");
      out.write("\t\t\t\t\t{header:'经销商名称',name:'custname',renderer:showCustName, queryConfig:{}},\r\n");
      out.write("\t\t            {header:'id',name:'id',hidden:true},\r\n");
      out.write("\t\t            {header:'rawValue_onelevel',name:'rawValue_onelevel',hidden:true},\r\n");
      out.write("\t\t\t\t\t{header:'合作经销商编号',name:'contractnum'},\r\n");
      out.write("\t\t\t\t\t{header:'是否二级经销商',name:'twolevelstatusname',type:'combobox',\r\n");
      out.write("\t\t\t            queryConfig:{\r\n");
      out.write("\t\t\t\t\t\t\tloadMode:'local',\r\n");
      out.write("\t\t\t\t\t\t\tdatas:[{title:'否',name:'1'},{title:'是',name:'0'}],\r\n");
      out.write("\t\t\t\t            displayField:'title',\r\n");
      out.write("\t\t\t\t            valueField:'name',\r\n");
      out.write("\t\t\t\t            defaultValue:1\r\n");
      out.write("\t\t\t\t            }},\r\n");
      out.write("\t\t\t\t\t{header:'所属一级经销商',name:'onelevelname',queryConfig:{isNewLine:true}},\r\n");
      out.write("\t\t\t\t\t{header:'合作状态',name:'cooperatestatusname'},\r\n");
      out.write("\t\t\t\t\t{header:'组织机构代码',name:'orgcode'},\r\n");
      out.write("\t\t\t\t\t{header:'纳税人类别',name:'taxlevelname'},\r\n");
      out.write("\t\t\t\t\t{header:'客户规模',name:'custscalename'},\r\n");
      out.write("\t\t\t\t\t{header:'纳税人识别号/国税登记号',name:'taxregcode',width:140},\r\n");
      out.write("\t\t\t\t\t{header:'电话',name:'taxphone'},\r\n");
      out.write("\t\t\t\t\t{header:'开户行',name:'taxbank',width:140},\r\n");
      out.write("\t\t\t\t\t{header:'开户账号',name:'taxacc',width:140},\r\n");
      out.write("\t\t\t\t\t{header:'贷款卡号',name:'creditcard',width:140},\r\n");
      out.write("\t\t\t\t\t{header:'省份',name:'provincename'},\r\n");
      out.write("\t\t\t\t\t{header:'省份',name:'province',hidden:true},\r\n");
      out.write("\t\t\t\t\t{header:'城市',name:'cityname'},\r\n");
      out.write("\t\t\t\t\t{header:'城市',name:'city',hidden:true},\r\n");
      out.write("\t\t\t\t\t{header:'区县',name:'countyname'},\r\n");
      out.write("\t\t\t\t\t{header:'区县',name:'county',hidden:true},\r\n");
      out.write("\t\t\t\t\t{header:'企业性质',name:'ownershipname'},\r\n");
      out.write("\t\t\t\t\t{header:'法人代表',name:'legalrepresentative'},\r\n");
      out.write("\t\t\t\t\t{header:'法人代表身份证',name:'idcardno',width:140},\r\n");
      out.write("\t\t\t\t\t{header:'手机',name:'mobilenumber'},\r\n");
      out.write("\t\t\t\t\t{header:'电话',name:'phone'},\r\n");
      out.write("\t\t\t\t\t{header:'公司邮寄地址',name:'mailadd',width:150},\r\n");
      out.write("\t\t\t\t\t{header:'邮编',name:'postcode'},\r\n");
      out.write("\t\t\t\t\t{header:'公司网址',name:'website',width:140},\r\n");
      out.write("\t\t\t\t\t{header:'公司地址',name:'postaddr'},\r\n");
      out.write("\t\t\t\t\t{header:'传真',name:'faxnumber'},\r\n");
      out.write("\t\t\t\t\t{header:'登记注册号（营业执照号）',name:'regnumber',width:140},\r\n");
      out.write("\t\t\t\t\t{header:'注册时间',name:'regdate'},\r\n");
      out.write("\t\t\t\t\t{header:'注册资本',name:'regcapital'},\r\n");
      out.write("\t\t\t\t\t{header:'所属区域',name:'ownerdistrictname'},\r\n");
      out.write("\t\t\t\t\t{header:'办事处',name:'ownerofficename'},\r\n");
      out.write("\t\t\t\t\t{header:'办事处',name:'owneroffice',hidden:true},\r\n");
      out.write("\t\t\t\t\t{header:'店面类型',name:'shoptypename'},\r\n");
      out.write("\t\t\t\t\t{header:'是否作废',name:'invalidname'},\r\n");
      out.write("\t\t            {header:'是否草稿',name:'draftname',type:'combobox',\r\n");
      out.write("\t\t\t            queryConfig:{\r\n");
      out.write("\t\t\t\t\t\t//isNewLine:true,\r\n");
      out.write("\t\t\t\t\t\t//colSpan:3,\r\n");
      out.write("\t\t\t\t\t\tloadMode:'local',\r\n");
      out.write("\t\t\t\t\t\tdatas:[{title:'否',name:'1'},{title:'是',name:'0'}],\r\n");
      out.write("\t\t\t            displayField:'title',\r\n");
      out.write("\t\t\t            valueField:'name',\r\n");
      out.write("\t\t\t            defaultValue:1\r\n");
      out.write("\t\t\t            }},\r\n");
      out.write("\t\t\t            {header:'操作',name:'enabled',hidden:!isAdmin,renderer:resetCust}\r\n");
      out.write("\t        ],\r\n");
      out.write("\t        params:{\r\n");
      out.write("\t        \t\tloginuser:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope['login_userid']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\",\r\n");
      out.write("\t\t     \t\tenabled:\"1\"    \r\n");
      out.write("\t\t\t   }\r\n");
      out.write("   \t });\r\n");
      out.write("   });\r\n");
      out.write("\r\n");
      out.write("\tfunction resetCust(value,tableObj,columnName,columnIndex,rowData){\r\n");
      out.write("    \tvar field=\"-\";\r\n");
      out.write("        var invalid=rowData.invalidname;\r\n");
      out.write("        if(invalid==\"是\"){\r\n");
      out.write("\t    \tvar base = \"<a href='#' onclick='doResetCust(\\\"\"+rowData.custid+\"\\\",\\\"\"+rowData.custname+\"\\\")'>{1}</a>\";\r\n");
      out.write("\t        var updateFlag=\"撤销删除\";\r\n");
      out.write("\t        field=base.replace(\"{1}\",updateFlag);\r\n");
      out.write("        }\r\n");
      out.write("        return field;\r\n");
      out.write("    }\r\n");
      out.write("    var currentLoadMask;\r\n");
      out.write("    function doResetCust(custId,name){\r\n");
      out.write("    \tif(confirm(\"是否撤销删除[\"+name+\"]经销商?\")){\r\n");
      out.write("    \t\tvar loadMaskMsg = (\"正在撤销删除[\"+name+\"]经销商,请稍后... \");\r\n");
      out.write("            if(null == currentLoadMask){\r\n");
      out.write("            \tcurrentLoadMask = new tracywindyLoadMask(document.body,loadMaskMsg);\r\n");
      out.write("\t        }\r\n");
      out.write("            currentLoadMask.show();\r\n");
      out.write("            ajaxRequest({\r\n");
      out.write("                url:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/leasing/acl/resetCustEwlp.acl\",\r\n");
      out.write("                params:{\"id\":custId},\r\n");
      out.write("                timeout:30*1000,\r\n");
      out.write("                success:function(res){\r\n");
      out.write("        \t   \t\tres=res.responseText;\r\n");
      out.write("        \t   \t\tres=res.replace(/(^\\s+)|(\\s+$)/g, \"\"); \r\n");
      out.write("\t\t     \t    if(res!=''){\r\n");
      out.write("\t\t\t    \t \talert(res);\r\n");
      out.write("\t\t     \t    }else{\r\n");
      out.write("\t\t     \t    \talert(\"撤销成功[\"+name+\"]!\");\r\n");
      out.write("\t\t     \t    \tgetTracywindyObject(\"id_table\").reload();\r\n");
      out.write("\t\t     \t    }\r\n");
      out.write("                    currentLoadMask.hide();\r\n");
      out.write("                },\r\n");
      out.write("                failure:function(res){\r\n");
      out.write("                    alert(\"服务器通信失败!\");\r\n");
      out.write("                    currentLoadMask.hide();\r\n");
      out.write("                }\r\n");
      out.write("           });\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\tfunction showCustName(value,tableObj,columnName,columnIndex,rowData){\r\n");
      out.write("        var base = \"<a href='javascript:void(0);' onclick='showDealerCustInfo(\\\"\"+rowData.custid+\"\\\")'>{1}</a>{2}\";\r\n");
      out.write("        var separator = \"&nbsp;&nbsp;\";\r\n");
      out.write("        var updateFlag=value;\r\n");
      out.write("        var updateClickFunc=\"other\";\r\n");
      out.write("        var field=base.replace(\"{1}\",updateFlag).replace(\"{2}\",separator);\r\n");
      out.write("        return field;\r\n");
      out.write("      }\r\n");
      out.write("\t function showDealerCustInfo(cust_id){\r\n");
      out.write("\t    \tvar URL = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/leasing/cust_info/cust_info.bi\";\r\n");
      out.write("\t    \tvar params = {cust_id:cust_id,read_only:true};\r\n");
      out.write("\t\t    openFullScreenWindow(URL,params);\r\n");
      out.write("\t    }\r\n");
      out.write("//combox的相关onselect函数\r\n");
      out.write("function choseNext(parentCombo,childComboId,table){//多级联动函数\r\n");
      out.write("\t var parentValue = parentCombo.getValue();\r\n");
      out.write("\t var childCombo  = getTracywindyObject(childComboId);\r\n");
      out.write("\t childCombo.params['tableName'] =\"(select id,name from \"+table+\" where pid='\"+parentValue+\"') rs\" ;\r\n");
      out.write("\t childCombo.reload();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function checkDraft(){//确认是否草稿\r\n");
      out.write("\tif(getTracywindyObject(\"id_combo_draftname\").getValue()=='0'){\r\n");
      out.write("\t\tif(confirm(\"您确认存为草稿吗?\")){\r\n");
      out.write("\t\t\tMustFillIn.cancelRequireAll(document.getElementById(\"id_detailInfoForm\"));//清除所有必填\r\n");
      out.write("\t\t\tMustFillIn.setRequire([\"custname\",\"rawValue_creatordept\"]);\r\n");
      out.write("\t\t\tMustFillIn.GoCheck(document.getElementById(\"id_detailInfoForm\"));\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("function submitCust(){//提交表单\r\n");
      out.write("\tif(check){\r\n");
      out.write("\t\tif(checkDraft()){return false;}\r\n");
      out.write("\t\tif(getTracywindyObject(\"id_combo_draftname\").getValue()=='1'){\r\n");
      out.write("\t\t\tvar phone=jQuery(\"#id_phone\").val();\r\n");
      out.write("\t\t\tvar mobilenumber=jQuery(\"#id_mobilenumber\").val();\r\n");
      out.write("\t\t\tif(mobilenumber==\"\"&&phone==\"\"){\r\n");
      out.write("\t\t\t\tjQuery(\"#id_mobilenumber\").focus();\r\n");
      out.write("\t\t\t\talert(\"手机电话必须填写其中任意一个!\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tgetTracywindyObject(\"id_table\").operationTable();\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\talert(\"请输入正确的组织机构代码!\");\r\n");
      out.write("\t\treturn false;\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("function checkORG(obj){\r\n");
      out.write("\tif(checkORGRight(obj)){\r\n");
      out.write("\t\tif(checkORGPrmary()){\r\n");
      out.write("\t\t\treturn true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\treturn false;\r\n");
      out.write("}\r\n");
      out.write("function checkORGRight(obj){//校验组织机构代码\r\n");
      out.write("\t  var financecode=obj.value;\r\n");
      out.write("\t   var fir_value, sec_value;\r\n");
      out.write("\t   var w_i = new Array(8);\r\n");
      out.write("\t   var c_i = new Array(8);\r\n");
      out.write("\t   var j, s = 0;\r\n");
      out.write("\t   var c, i;\r\n");
      out.write("\r\n");
      out.write("\t   var code = financecode;\r\n");
      out.write("\r\n");
      out.write("\t   if (code.length<1) {\r\n");
      out.write("\t     //alert(\"请输入组织机构代码!\");\r\n");
      out.write("\t     //obj.select();\r\n");
      out.write("\t       return false;\r\n");
      out.write("\t   }\r\n");
      out.write("\r\n");
      out.write("\t   if (code == \"00000000-0\") {\r\n");
      out.write("\t     alert(\"组织机构代码错误!\");\r\n");
      out.write("\t     //obj.select();\r\n");
      out.write("\t       return false;\r\n");
      out.write("\t   }\r\n");
      out.write("\r\n");
      out.write("\t   re = /[A-Z0-9]{8}-[A-Z0-9]/;    \r\n");
      out.write("\t   r = code.match(re);   \r\n");
      out.write("\t   if (r == null) {\r\n");
      out.write("\t\t alert(\"组织机构代码错误!\");\r\n");
      out.write("\t     //obj.select();\r\n");
      out.write("\t     return false;\r\n");
      out.write("\t   }        \r\n");
      out.write("\r\n");
      out.write("\t\t   w_i[0] = 3;\r\n");
      out.write("\t\t   w_i[1] = 7;\r\n");
      out.write("\t\t   w_i[2] = 9;\r\n");
      out.write("\t\t   w_i[3] = 10;\r\n");
      out.write("\t\t   w_i[4] = 5;\r\n");
      out.write("\t\t   w_i[5] = 8;\r\n");
      out.write("\t\t   w_i[6] = 4;\r\n");
      out.write("\t\t   w_i[7] = 2;\r\n");
      out.write("\r\n");
      out.write("\t\t   if (financecode.charAt(8) != '-') {\r\n");
      out.write("\t\t   alert(\"组织机构代码错误!\");\r\n");
      out.write("\t\t\t //obj.select();\r\n");
      out.write("\t\t\t   return false;\r\n");
      out.write("\t\t   }\r\n");
      out.write("\r\n");
      out.write("\t\t   for (i = 0; i < 10; i++) {\r\n");
      out.write("\t\t\t   c = financecode.charAt(i);\r\n");
      out.write("\t\t\t   if ((c <= 'z') && (c >= 'a')) \r\n");
      out.write("\t\t\t  {\r\n");
      out.write("\t\t\t   alert(\"组织机构代码错误!\");\r\n");
      out.write("\t\t\t //obj.select();\r\n");
      out.write("\t\t\t\t   return false;\r\n");
      out.write("\t\t\t   }\r\n");
      out.write("\t\t   }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t   fir_value = financecode.charCodeAt(0);\r\n");
      out.write("\t\t   sec_value = financecode.charCodeAt(1);\r\n");
      out.write("\r\n");
      out.write("\t\t   if (fir_value >= 'A'.charCodeAt(0) && fir_value <= 'Z'.charCodeAt(0)) {\r\n");
      out.write("\t\t\t   c_i[0] = fir_value + 32 - 87;\r\n");
      out.write("\t\t   } else {\r\n");
      out.write("\t\t\t\tif (fir_value >= '0'.charCodeAt(0) && fir_value <= '9'.charCodeAt(0)) {\r\n");
      out.write("\t\t\t\tc_i[0] = fir_value - '0'.charCodeAt(0);\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\talert(\"组织机构代码错误!\");\r\n");
      out.write("\t\t\t //obj.select();\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t   }\r\n");
      out.write("\r\n");
      out.write("\t\t   s = s + w_i[0] * c_i[0];\r\n");
      out.write("\r\n");
      out.write("\t\t   if (sec_value >= 'A'.charCodeAt(0) && sec_value <= 'Z'.charCodeAt(0)) {\r\n");
      out.write("\t\t\t   c_i[1] = sec_value + 32 - 87;\r\n");
      out.write("\t\t   } else if (sec_value >= '0'.charCodeAt(0) && sec_value <= '9'.charCodeAt(0)) {\r\n");
      out.write("\t\t\t   c_i[1] = sec_value - '0'.charCodeAt(0);\r\n");
      out.write("\t\t   } else {\r\n");
      out.write("\t\t   alert(\"组织机构代码错误!\");\r\n");
      out.write("\t\t\t //obj.select();\r\n");
      out.write("\t\t\t   return false;\r\n");
      out.write("\t\t   }\r\n");
      out.write("\r\n");
      out.write("\t\t   s = s + w_i[1] * c_i[1];\r\n");
      out.write("\t\t   for (j = 2; j < 8; j++) {\r\n");
      out.write("\t\t\t   if (financecode.charAt(j) < '0' || financecode.charAt(j) > '9') {\r\n");
      out.write("\t\t\t   alert(\"组织机构代码错误!\");\r\n");
      out.write("\t\t\t //obj.select();\r\n");
      out.write("\t\t\t\t   return false;\r\n");
      out.write("\t\t\t   }\r\n");
      out.write("\t\t\t   c_i[j] = financecode.charCodeAt(j) - '0'.charCodeAt(0);\r\n");
      out.write("\t\t\t   s = s + w_i[j] * c_i[j];\r\n");
      out.write("\t\t   }\r\n");
      out.write("\r\n");
      out.write("\t\t   c = 11 - (s % 11);\r\n");
      out.write("\r\n");
      out.write("\t\t   if (!((financecode.charAt(9) == 'X' && c == 10) ||\r\n");
      out.write("\t\t\t\t (c == 11 && financecode.charAt(9) == '0') || (c == financecode.charCodeAt(9) - '0'.charCodeAt(0)))) {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t  alert(\"组织机构代码错误!\");\r\n");
      out.write("\t\t\t\t  // obj.select();\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t   }\r\n");
      out.write("\t   return true;\r\n");
      out.write("}\r\n");
      out.write("var check=true;\r\n");
      out.write("function checkORGPrmary(){//校验组织结构代码唯一\r\n");
      out.write("\tvar custid=jQuery(\"#custid\").val();\r\n");
      out.write("\tvar orgcode=jQuery(\"#orgcode\").val();\r\n");
      out.write("\tif(orgcode!=\"\"){\r\n");
      out.write("\t\tvar url = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/acl/checkCustdealer.acl';\r\n");
      out.write("\t\tvar param={};\r\n");
      out.write("\t\tparam.custid=custid;\r\n");
      out.write("\t\tparam.orgcode=orgcode;\r\n");
      out.write("        ajaxRequest({\r\n");
      out.write("             url:url,\r\n");
      out.write("             params:param,\r\n");
      out.write("\t\t     success:function(res){\r\n");
      out.write("\t\t\t     \tif(res!=''){\r\n");
      out.write("\t\t\t     \t\tvar svote=res.responseText;\r\n");
      out.write("\t\t\t     \t    svote=svote.replace(/(^\\s+)|(\\s+$)/g, \"\"); \r\n");
      out.write("\t\t\t     \t    if(svote!=''){\r\n");
      out.write("\t\t\t\t    \t \talert(svote);\r\n");
      out.write("\t\t\t\t     \t\tcheck=false;\r\n");
      out.write("\t\t\t     \t    }else{\r\n");
      out.write("\t\t\t     \t    \tcheck=true;\r\n");
      out.write("\t\t\t     \t    }\r\n");
      out.write("\t\t\t     \t}\r\n");
      out.write("\t\t\t     },\r\n");
      out.write("\t\t     failure:function(res){alert(\"校验组织机构代码唯一失败!\");}\r\n");
      out.write("        });\r\n");
      out.write("\t}else{\r\n");
      out.write("\t\tcheck=true;\r\n");
      out.write("\t}\r\n");
      out.write("\treturn check;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div id=\"id_tableContainer\"></div>\r\n");
      out.write("\t<div id=\"id_detailInfoWindowContainer\"  buttons=\"#id-dlg-buttons\" closed=\"true\" modal=\"true\" title=\"经销商管理\" style=\"display:none;width:800px;\">\r\n");
      out.write("\t        <center>\r\n");
      out.write("\t\t       <form id=\"id_detailInfoForm\">\r\n");
      out.write("\t\t\t        <table style=\"width:95%\" class=\"fillTable\">\r\n");
      out.write("\t\t\t            <tr style=\"display:none\"><td><input name=\"id\"  type=\"hidden\" value=\"\"/><input name=\"custid\" id=\"custid\" type=\"hidden\" value=\"\"/></td></tr>\r\n");
      out.write("\t\t\t            <tr  class=\"tr-even\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">经销商名称:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\" colspan=\"3\">\r\n");
      out.write("\t\t\t            \t\t<input name=\"custname\" id=\"custname\"  style=\"width:92%\"  label=\"经销商名称\" maxB=\"255\" maxlength=\"255\" class=\"td-content\"   type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            \t\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t            \r\n");
      out.write("\t\t\t               <tr  class=\"tr-odd\">\r\n");
      out.write("\t\t\t            \t<!--  <td class=\"td-content-title\">经销商编号:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<input name=\"contractNum\"  readonly=\"readonly\" id=\"custnumber\" maxB=\"50\"   label=\"经销商编号\"  class=\"td-content-input td-content-readonly\"    type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>-->\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">组织机构代码:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<input name=\"orgcode\" id=\"orgcode\"  label=\"组织结构代码\" maxB=\"50\" maxlength=\"20\" onblur=\"checkORG(this)\" class=\"td-content\"   type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">合作状态:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<div style=\"float:left\" class=\"leftComboContainer\" id=\"cooperatestatusname\"></div>\r\n");
      out.write("\t\t\t            \t</td>    \r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\"></td> \r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\"></td>  \t\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t            <tr  class=\"tr-even\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">是否二级经销商:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<div style=\"float:left\" class=\"leftComboContainer\" id=\"twolevelstatusname\"></div>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">所属一级经销商:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<div style=\"float:left\" class=\"leftComboContainer\" id=\"onelevelname\"></div>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t            <tr  class=\"tr-even\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">纳税人类别:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<div style=\"float:left\" class=\"leftComboContainer\" id=\"taxlevelname\"></div>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">客户规模:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<div style=\"float:left\" class=\"leftComboContainer\" id=\"custscalename\"></div>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t            <tr  class=\"tr-odd\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">纳税人识别号/国税登记号:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<input name=\"taxregcode\" label=\"纳税人识别号/国税登记号\" maxB=\"100\" maxlength=\"100\"  type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">电话:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<input name=\"taxphone\"  label=\"电话\" maxB=\"100\"   type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t            <tr  class=\"tr-even\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">开户行:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<input name=\"taxbank\"  label=\"开户行\"  maxB=\"100\" maxlength=\"100\"  type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">开户账号:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<input name=\"taxacc\"  label=\"开户账号\"  maxB=\"50\"  maxlength=\"50\" type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t            <tr  class=\"tr-odd\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">货款卡号:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<input name=\"creditcard\"  label=\"货款卡号\"  maxB=\"50\" maxlength=\"50\"  type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">企业性质:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<div style=\"float:left\" class=\"leftComboContainer\" id=\"ownershipname\"></div>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t             <tr class=\"tr-even\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">省份:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<div style=\"float:left\" class=\"leftComboContainer\" id=\"provincename\"></div>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">城市:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<div style=\"float:left\" class=\"leftComboContainer\" id=\"cityname\"></div>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t            <tr  class=\"tr-odd\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">区县:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<div style=\"float:left\" class=\"leftComboContainer\" id=\"countyname\"></div>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            \t\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">是否4S: </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<div style=\"float:left\" class=\"leftComboContainer\" id=\"is4sname\"></div>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t            \r\n");
      out.write("\t\t\t             <tr  class=\"tr-even\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">法人代表:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<input name=\"legalrepresentative\"  label=\"法人代表\"  maxB=\"150\" maxlength=\"150\" type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">法人代表身份证:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<input name=\"idcardno\"  label=\"法人代表身份证号\" dataType=\"IdCard\"  maxB=\"20\" maxlength=\"18\" type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t             <tr  class=\"tr-odd\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">手机:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<input id=\"id_mobilenumber\" name=\"mobilenumber\"  label=\"手机\" dataType=\"Mobile\" maxB=\"20\" maxlength=\"11\" type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">电话:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<input id=\"id_phone\"  name=\"phone\"  label=\"电话\"   maxB=\"100\"  type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t             <tr  class=\"tr-even\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">公司邮寄地址:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\" colspan=\"3\">\r\n");
      out.write("\t\t\t            \t\t<textarea name=\"mailAdd\"  label=\"公司邮寄地址\" maxB=\"255\" maxlength=\"255\" style=\"width:92%\" type=\"text\" ></textarea>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t            <tr   class=\"tr-odd\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">邮编:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<input name=\"postcode\"  label=\"邮编\"  dataType=\"Zip\" maxB=\"20\" maxlength=\"6\"  type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">公司网址:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<input name=\"website\"  label=\"公司网址\" dataType=\"Url\" maxB=\"100\" maxlength=\"100\" type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t            <tr  class=\"tr-even\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">公司地址: </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\" colspan=\"3\">\r\n");
      out.write("\t\t\t            \t\t<textarea name=\"postaddr\"  label=\"公司地址\" maxB=\"255\"  maxlength=\"255\" style=\"width:92%\"  type=\"text\" ></textarea>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t            <tr  class=\"tr-odd\">\r\n");
      out.write("\t\t\t            <td class=\"td-content-title\">传真:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<input name=\"faxnumber\"  label=\"传真\"   maxB=\"100\"  type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">登记注册号（营业执照号）: </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<textarea name=\"regnumber\"  label=\"登记注册号（营业执照号）\" maxB=\"50\" maxlength=\"50\" style=\"width:77%\"   type=\"text\" ></textarea>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t            <tr  class=\"tr-even\">\r\n");
      out.write("\t\t\t            <td class=\"td-content-title\">注册时间 :  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t<input name=\"regdate\" id=\"regdate\"  label=\"注册时间\"  class=\"Wdate td-content-input td-content-readonly\"  onClick=\"WdatePicker(this,{readOnly:true})\" readOnly   type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">注册资本 :  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<input name=\"regcapital\" id=\"regcapital\" label=\"注册资本 \" dataType=\"PMoney\" maxB=\"255\" maxlength=\"255\"  type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t             <tr  class=\"tr-odd\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">注册地址 : </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<input name=\"regaddr\"  label=\"注册地址 : \"  maxB=\"255\" maxlength=\"255\"  type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">实收资本: </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<input name=\"incomeassets\" id=\"incomeassets\" label=\"实收资本\"  maxB=\"255\"  maxlength=\"255\" type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t            <tr  class=\"tr-even\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">经营范围（主营） : </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\" colspan=\"3\">\r\n");
      out.write("\t\t\t            \t\t<textarea name=\"bizscopeprimary\"  label=\"经营范围（主营） \" style=\"width:92%\" maxB=\"255\"  type=\"text\" ></textarea>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t            <tr  class=\"tr-odd\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">经营范围（兼营） : </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\" colspan=\"3\">\r\n");
      out.write("\t\t\t            \t\t<textarea name=\"bizscopesecondary\"  label=\"经营范围（兼营） : \" style=\"width:92%\"  maxB=\"255\" type=\"text\" ></textarea>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t            <tr  class=\"tr-even\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">所属区域:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<div style=\"float:left\" class=\"leftComboContainer\" id=\"ownerdistrictname\"></div>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">办事处:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<div style=\"float:left\" class=\"leftComboContainer\" id=\"ownerofficename\"></div>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t            <tr  class=\"tr-odd\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">近三年销量 : </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\" colspan=\"3\">\r\n");
      out.write("\t\t\t            \t\t<textarea name=\"threeyearsales\"  label=\"近三年销量 : \" style=\"width:92%\"  type=\"text\" ></textarea>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t            <tr class=\"tr-even\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">店面类型:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<div style=\"float:left\" class=\"leftComboContainer\" id=\"shoptypename\"></div>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">与陕汽合作开始时间:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<input name=\"cooperationdate\" id=\"cooperationdate\"  label=\"与陕汽合作开始时间\"  class=\"Wdate td-content-input td-content-readonly\"  onClick=\"WdatePicker(this,{readOnly:true})\" readOnly   type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t            <tr  class=\"tr-odd\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\"> 目标销量: </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\" colspan=\"3\">\r\n");
      out.write("\t\t\t            \t\t<textarea name=\"purposesales\"  label=\"目标销量 \" style=\"width:92%\" maxB=\"255\" type=\"text\" ></textarea>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t            <!--  <tr  class=\"tr-even\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\"> 常住地址: </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\" colspan=\"3\">\r\n");
      out.write("\t\t\t            \t\t<textarea name=\"oftenaddr\"  label=\"常住地址 \" maxB=\"255\" style=\"width:92%\" type=\"text\" ></textarea>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr> -->\r\n");
      out.write("\t\t\t             <tr  class=\"tr-odd\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\"> 净资产: </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\" colspan=\"3\">\r\n");
      out.write("\t\t\t            \t\t<textarea name=\"netassets\"  label=\"净资产 \" maxB=\"255\" style=\"width:92%\" type=\"text\" ></textarea>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t            <tr  class=\"tr-even\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\"> 股权结构: </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\" colspan=\"3\">\r\n");
      out.write("\t\t\t            \t\t<textarea name=\"ownershipstructure\" maxB=\"255\" label=\"股权结构 \" style=\"width:92%\"  type=\"text\" ></textarea>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t            <tr  class=\"tr-odd\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">自有车辆:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\" colspan=\"3\">\r\n");
      out.write("\t\t\t            \t\t<textarea name=\"ownervehicle\"  label=\"自有车辆\" style=\"width:92%\" maxB=\"1000\" type=\"text\" ></textarea>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t             <tr   class=\"tr-even\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">房产:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\" colspan=\"3\">\r\n");
      out.write("\t\t\t            \t\t<textarea name=\"ownerestate\"  label=\"房产\" maxB=\"1000\" style=\"width:92%\" type=\"text\" ></textarea>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t             <tr   class=\"tr-odd\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">土地:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\" colspan=\"3\">\r\n");
      out.write("\t\t\t            \t\t<textarea name=\"ownerland\"  label=\"土地\"  maxB=\"255\" style=\"width:92%\" type=\"text\" ></textarea>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t             <tr   class=\"tr-even\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">其他:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\" colspan=\"3\">\r\n");
      out.write("\t\t\t            \t\t<textarea name=\"ownerother\"  label=\"其他\"  maxB=\"255\" style=\"width:92%\" type=\"text\" ></textarea>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t             <tr   class=\"tr-odd\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">资产估价（总）:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\" colspan=\"3\">\r\n");
      out.write("\t\t\t            \t\t<textarea name=\"ownershiptotal\"  maxB=\"255\" label=\"资产估价（总）\"  style=\"width:92%\" type=\"text\" ></textarea>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t             <tr   class=\"tr-even\">\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">备注:  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\" colspan=\"3\">\r\n");
      out.write("\t\t\t            \t\t<textarea name=\"ownermemo\"  label=\"备注\"  maxB=\"255\" style=\"width:92%\" type=\"text\" ></textarea>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t            <tr  class=\"tr-odd\">\r\n");
      out.write("\t\t\t            <td class=\"td-content-title\">是否草稿: </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<div style=\"float:left\" class=\"leftComboContainer\" id=\"draftname\"></div>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            \t<td class=\"td-content-title\">登记人 :  </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<input name=\"creatorname\" id=\"creatorname\" label=\"登记人 \" class=\"td-content-readonly\" readonly=\"readonly\" type=\"text\" />\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t            <tr  class=\"tr-even\">\r\n");
      out.write("\t\t\t            <td class=\"td-content-title\">登记人部门:</td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<div style=\"float:left\" class=\"leftComboContainer\" id=\"creatordeptname\"></div>\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t           \t <td class=\"td-content-title\">登记时间: </td>  \r\n");
      out.write("\t\t\t            \t<td class=\"td-content\">\r\n");
      out.write("\t\t\t            \t\t<input name=\"createdate\" id=\"createdate\" isDefaultDate=\"true\"  label=\"登记时间\"   readOnly   type=\"text\" />\r\n");
      out.write("\t\t\t            \t\t<input name=\"invalid\" id=\"invalid\"  label=\"是否作废 \" class=\"td-content-readonly\" readonly=\"readonly\"  type=\"hidden\" />\r\n");
      out.write("\t\t\t            \t\t<input id=\"draftname\" type=\"hidden\" />\r\n");
      out.write("\t\t\t            \t\t<input id=\"industryname\" type=\"hidden\" />\r\n");
      out.write("\t\t\t            \t\t<input id=\"taxlevelname\" type=\"hidden\" />\r\n");
      out.write("\t\t\t            \t\t<input id=\"industrylevelbigname\" type=\"hidden\" />\r\n");
      out.write("\t\t\t            \t\t<input id=\"industrylevelmiddlename\" type=\"hidden\" />\r\n");
      out.write("\t\t\t            \t\t<input id=\"industrylevelsmallname\" type=\"hidden\" />\r\n");
      out.write("\t\t\t            \t\t<input id=\"onelevelname\" type=\"hidden\" />\r\n");
      out.write("\t\t\t            \t\t<input id=\"twolevelstatusname\" type=\"hidden\" />\r\n");
      out.write("\t\t\t            \t\t<span id=\"custtype\" style=\"display:none\"></span>\r\n");
      out.write("\t\t\t            \t\t<span id=\"isassociatedname\" style=\"display:none\"></span>\r\n");
      out.write("\t\t\t            \t\t<span id=\"reditorrightname\" style=\"display:none\"></span>\r\n");
      out.write("\t\t\t            \t\t<span id=\"assurorrightname\" style=\"display:none\"></span>\r\n");
      out.write("\t\t\t            \t\t\r\n");
      out.write("\t\t\t            \t</td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("\t\t\t         \r\n");
      out.write("\t\t\t        </table>\r\n");
      out.write("\t\t        </form>\r\n");
      out.write("\t        </center>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\t<div style=\"text-align:center;width:800px;display:none;height:40px;line-height:40px;\" id=\"id-dlg-buttons\">\r\n");
      out.write("\t\t  <a  style=\"margin-left:20px;\" href=\"javascript:void(0);\" class=\"btn btn-primary\" onclick='submitCust();'><span>确定</span></a>\r\n");
      out.write("\t\t  <a  style=\"margin-left:20px;\" href=\"javascript:void(0);\" class=\"btn btn-primary\" onclick='jQuery(\"#id_detailInfoWindowContainer\").window(\"close\");'><span>取消</span></a>\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_permission_005faction_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  permission:action
    com.kernal.tags.ActionPermissionTag _jspx_th_permission_005faction_005f0 = (com.kernal.tags.ActionPermissionTag) _005fjspx_005ftagPool_005fpermission_005faction_0026_005fcode.get(com.kernal.tags.ActionPermissionTag.class);
    _jspx_th_permission_005faction_005f0.setPageContext(_jspx_page_context);
    _jspx_th_permission_005faction_005f0.setParent(null);
    // /WEB-INF/jsps/solutions/leasing/cust_info/cust_dealer/cust_dealer_list.jsp(57,0) name = code type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_permission_005faction_005f0.setCode("dealer_manage");
    int _jspx_eval_permission_005faction_005f0 = _jspx_th_permission_005faction_005f0.doStartTag();
    if (_jspx_eval_permission_005faction_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_permission_005faction_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_permission_005faction_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_permission_005faction_005f0.doInitBody();
      }
      do {
        out.write("\r\n");
        out.write("<script type=\"text/javascript\">\r\n");
        out.write("isAdmin=true;\r\n");
        out.write("operButtons='新增|修改';\r\n");
        out.write("</script >\r\n");
        int evalDoAfterBody = _jspx_th_permission_005faction_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_permission_005faction_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_permission_005faction_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fpermission_005faction_0026_005fcode.reuse(_jspx_th_permission_005faction_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fpermission_005faction_0026_005fcode.reuse(_jspx_th_permission_005faction_005f0);
    return false;
  }

  private boolean _jspx_meth_permission_005faction_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  permission:action
    com.kernal.tags.ActionPermissionTag _jspx_th_permission_005faction_005f1 = (com.kernal.tags.ActionPermissionTag) _005fjspx_005ftagPool_005fpermission_005faction_0026_005fcode.get(com.kernal.tags.ActionPermissionTag.class);
    _jspx_th_permission_005faction_005f1.setPageContext(_jspx_page_context);
    _jspx_th_permission_005faction_005f1.setParent(null);
    // /WEB-INF/jsps/solutions/leasing/cust_info/cust_dealer/cust_dealer_list.jsp(63,0) name = code type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_permission_005faction_005f1.setCode("admin_action");
    int _jspx_eval_permission_005faction_005f1 = _jspx_th_permission_005faction_005f1.doStartTag();
    if (_jspx_eval_permission_005faction_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_permission_005faction_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_permission_005faction_005f1.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_permission_005faction_005f1.doInitBody();
      }
      do {
        out.write("\r\n");
        out.write("<script type=\"text/javascript\">\r\n");
        out.write("isAdmin=true;\r\n");
        out.write("operButtons='新增|修改|删除|状态';\r\n");
        out.write("</script >\r\n");
        int evalDoAfterBody = _jspx_th_permission_005faction_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_permission_005faction_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_permission_005faction_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fpermission_005faction_0026_005fcode.reuse(_jspx_th_permission_005faction_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fpermission_005faction_0026_005fcode.reuse(_jspx_th_permission_005faction_005f1);
    return false;
  }
}
