document.write('<!-- 用来产生编辑状态的ActiveX控件的JS脚本-->   ');
document.write('<!-- 因为微软的ActiveX新机制，需要一个外部引入的js-->   ');
document.write('<object id="TANGER_OCX" classid="clsid:C9BC4DFF-4248-4a3c-8A49-63A7D317F404"    ');
document.write("codebase='"+getRootPath()+"/ntko/officecontrol/OfficeControl.cab#version=5,0,1,1' width='100%' height='100%'>   ");
document.write('<param name="IsUseUTF8URL" value="-1">   ');
document.write('<param name="IsUseUTF8Data" value="-1">   ');
document.write('<param name="BorderStyle" value="1">   ');
document.write('<param name="BorderColor" value="14402205">   ');
document.write('<param name="TitlebarColor" value="15658734">   ');
document.write('<param name="TitlebarTextColor" value="0">   ');
document.write('<param name="MenubarColor" value="14402205">   ');
document.write('<param name="MenuButtonColor" VALUE="16180947">   ');
document.write('<param name="MenuBarStyle" value="3">   ');
document.write('<param name="MenuButtonStyle" value="7">   ');
document.write('<param name="MakerCaption" value="上海智联腾华软件技术有限公司">   ');
document.write('<param name="MakerKey" value="19F681B29A5F838EB9F95F444A6DB205A7F7F69B">   ');
document.write('<param name="ProductCaption" value="上海智联腾华软件技术有限公司某某测试用户">   ');
document.write('<param name="ProductKey" value="01FBC582CEDE4F80984F56153AD4EB4486B6EBB8">   ');

document.write('<SPAN STYLE="color:red">不能装载文档控件。请在检查浏览器的选项中检查浏览器的安全设置。</SPAN>   ');
document.write('</object>');