package com.tenwa.leasing.bean;

import java.math.BigDecimal;

import com.business.entity.User;

/**
 * FundRentAdjust generated by MyEclipse Persistence Tools
 */

public class AdjustBean {

	// Fields
	
	private Integer	id;
	private String	measureId;
	private	String	onHireId;
	private String	contractId;
	private Integer	startList;
	private String	paydayAdjust;
	private String	incomeNumberYear;
	private Double	handlingCharge;
	private Integer	adjustList;
	private Double	yearRate;
	private Double	interestHandlingCharge;
	private Double	corpusOverage;
	private String	creator;
	private String	createDate;
	private String	modificator;
	private String	modifyDate;
	private Double	dunRent;
	private Double	dunPenalty;
	private Double	agreedPenalty;
	private Double	agreed_interest;
	private Double	otherOut;
	private Double	otherIn;
	private String	assetOwnership;
	private Double	contractTotal;
	private String	adjustType;
	private String	table_name="fund_rent_adjust_temp";//表名
	private String	pk_clum1="contract_Id";//主键名1
	private String	pk_clum2="doc_id";//主键名2
	private String	pk_clum_v1;//主键值1
	private String	pk_clum_v2;//主键值2
	
	private BigDecimal advance_rate = new BigDecimal("0.00");//提前结清比例(百分比)%
	// Constructors

	/** default constructor */
	public AdjustBean() {
	}


	/** minimal constructor */
	public AdjustBean(String measureId) {
		this.measureId = measureId;
	}



	@Override
	public String toString() {
		String toStr="AdjustBean的值为:";
		toStr+="\ntable:"+this.getTable_name();
		toStr+="\nPk_clum1:"+this.getPk_clum1();
		toStr+="\nPk_clum2:"+this.getPk_clum2();
		toStr+="\nPk_clum_v1:"+this.getPk_clum_v1();
		toStr+="\nPk_clum_v2:"+this.getPk_clum_v2();
		toStr+="\nid:"+this.getId();
		toStr+="\nmeasureId:"+this.getMeasureId();
		toStr+="\nonHireId:"+this.getOnHireId();
		toStr+="\ncontractId:"+this.getContractId();
		toStr+="\nadjustType:"+this.getAdjustType();
		toStr+="\nstartList:"+this.getStartList();
		toStr+="\npaydayAdjust:"+this.getPaydayAdjust();
		toStr+="\nhandlingCharge:"+this.getHandlingCharge();
		toStr+="\nadjustList:"+this.getAdjustList();
		toStr+="\nyearRate:"+this.getYearRate();
		toStr+="\ninterestHandlingCharge:"+this.getInterestHandlingCharge();
		toStr+="\ncorpusOverage:"+this.getCorpusOverage();		
		toStr+="\ndunRent:"+this.getDunRent();
		toStr+="\ndunPenalty:"+this.getDunPenalty();
		toStr+="\nagreedPenalty:"+this.getAgreedPenalty();
		toStr+="\notherOut:"+this.getOtherOut();
		toStr+="\notherIn:"+this.getOtherIn();
		toStr+="\nassetOwnership:"+this.getAssetOwnership();
		toStr+="\ncontractTotal:"+this.getContractTotal();
		toStr+="\ncreateDate:"+this.getCreateDate();
		toStr+="\nmodificator:"+this.getModificator();
		toStr+="\nmodifyDate:"+this.getModifyDate();
		toStr+="\nadvance_rate:"+this.getAdvance_rate();
		return toStr;
	}


	public Integer getId() {
		return this.id;
	}


	public void setId(Integer id) {
		this.id = id;
	}


	public String getMeasureId() {
		return this.measureId;
	}


	public void setMeasureId(String measureId) {
		this.measureId = measureId;
	}


	public String getContractId() {
		return this.contractId;
	}


	public void setContractId(String contractId) {
		this.contractId = contractId;
	}


	public Integer getStartList() {
		return this.startList;
	}


	public void setStartList(Integer startList) {
		this.startList = startList;
	}


	public String getPaydayAdjust() {
		return this.paydayAdjust;
	}


	public void setPaydayAdjust(String paydayAdjust) {
		this.paydayAdjust = paydayAdjust;
	}


	public Double getHandlingCharge() {
		return this.handlingCharge;
	}


	public void setHandlingCharge(Double handlingCharge) {
		this.handlingCharge = handlingCharge;
	}


	public Integer getAdjustList() {
		return this.adjustList;
	}


	public void setAdjustList(Integer adjustList) {
		this.adjustList = adjustList;
	}


	public Double getYearRate() {
		return this.yearRate;
	}


	public void setYearRate(Double yearRate) {
		this.yearRate = yearRate;
	}


	public Double getInterestHandlingCharge() {
		return this.interestHandlingCharge;
	}


	public void setInterestHandlingCharge(Double interestHandlingCharge) {
		this.interestHandlingCharge = interestHandlingCharge;
	}


	public Double getCorpusOverage() {
		return this.corpusOverage;
	}


	public void setCorpusOverage(Double corpusOverage) {
		this.corpusOverage = corpusOverage;
	}


	public String getTable_name() {
		return table_name;
	}


	public void setTable_name(String table_name) {
		this.table_name = table_name;
	}


	public String getPk_clum1() {
		return pk_clum1;
	}


	public void setPk_clum1(String pk_clum1) {
		this.pk_clum1 = pk_clum1;
	}


	public String getPk_clum2() {
		return pk_clum2;
	}


	public void setPk_clum2(String pk_clum2) {
		this.pk_clum2 = pk_clum2;
	}


	public String getPk_clum_v1() {
		if(pk_clum_v1==null||pk_clum_v1.equals("")){
			return contractId;
		}
		return pk_clum_v1;
	}


	public void setPk_clum_v1(String pk_clum_v1) {
		this.pk_clum_v1 = pk_clum_v1;
	}


	public String getPk_clum_v2() {
		if(pk_clum_v2==null||pk_clum_v2.equals("")){
			return measureId;
		}
		return pk_clum_v2;
	}


	public void setPk_clum_v2(String pk_clum_v2) {
		this.pk_clum_v2 = pk_clum_v2;
	}


	public String getIncomeNumberYear() {
		return incomeNumberYear;
	}


	public void setIncomeNumberYear(String incomeNumberYear) {
		this.incomeNumberYear = incomeNumberYear;
	}


	public Double getDunRent() {
		return dunRent;
	}


	public void setDunRent(Double dunRent) {
		this.dunRent = dunRent;
	}


	public Double getDunPenalty() {
		return dunPenalty;
	}


	public void setDunPenalty(Double dunPenalty) {
		this.dunPenalty = dunPenalty;
	}


	public Double getAgreedPenalty() {
		return agreedPenalty;
	}


	public void setAgreedPenalty(Double agreedPenalty) {
		this.agreedPenalty = agreedPenalty;
	}


	public Double getOtherOut() {
		return otherOut;
	}


	public void setOtherOut(Double otherOut) {
		this.otherOut = otherOut;
	}


	public Double getOtherIn() {
		return otherIn;
	}


	public void setOtherIn(Double otherIn) {
		this.otherIn = otherIn;
	}


	public String getAssetOwnership() {
		return assetOwnership;
	}


	public void setAssetOwnership(String assetOwnership) {
		this.assetOwnership = assetOwnership;
	}


	public Double getContractTotal() {
		return contractTotal;
	}


	public void setContractTotal(Double contractTotal) {
		this.contractTotal = contractTotal;
	}


	public String getAdjustType() {
		return adjustType;
	}


	public void setAdjustType(String adjustType) {
		this.adjustType = adjustType;
	}


	public Double getAgreedInterest() {
		return agreed_interest;
	}


	public void setAgreedInterest(Double agreed_interest) {
		this.agreed_interest = agreed_interest;
	}


	public String getOnHireId() {
		return onHireId;
	}


	public void setOnHireId(String onHireId) {
		this.onHireId = onHireId;
	}
	
	public void setCreator(User user){
		creator=user.getId();
	}

	public String getCreateDate() {
		return createDate;
	}

	public void setCreateDate(String create_date) {
		this.createDate = create_date;
	}

	public String getCreator() {
		return creator;
	}
	
	public void setCreator(String creator) {
		this.creator = creator;
	}
	public void setModificator(User user){
		modificator=user.getId();
	}
	public String getModificator() {
		return modificator;
	}

	public void setModificator(String modificator) {
		this.modificator = modificator;
	}

	public String getModifyDate() {
		return modifyDate;
	}

	public void setModifyDate(String modify_date) {
		this.modifyDate = modify_date;
	}


	public Double getAgreed_interest() {
		return agreed_interest;
	}


	public void setAgreed_interest(Double agreedInterest) {
		agreed_interest = agreedInterest;
	}

	/**
	 * <p>GET提前结清比例(百分比)%。</p>
	 * @author sea
	 * @return
	 */
	public BigDecimal getAdvance_rate() {
		return advance_rate;
	}


	/**
	 * <p>GET提前结清比例(百分比)%。</p>
	 * @author sea
	 * @return
	 */
	public void setAdvance_rate(BigDecimal advanceRate) {
		advance_rate = advanceRate;
	}
	
	
}
