package org.apache.jsp.WEB_002dINF.jsps.solutions.acl;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.List<java.lang.String> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.List<java.lang.String> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("\t<title>用户主页</title>\r\n");
      out.write("\t\t<!--css sheet-->\r\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/dtree/dtree.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/jquery-easyui/easyui.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/jquery-easyui/icon.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/tracywindy/tracywindy.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/tracywindy/main.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t<link href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/css/tracywindy/button.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t<!--javascript libray-->\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery/jquery.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery/jquery.easyui.min.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/jquery/easyui-lang-zh_CN.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyUtils.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyJsonUtil.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyAjax.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyLoadMask.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/charts/js/FusionCharts.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/charts/js/FusionChartsExportComponent.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/js/tracywindy/tracywindyChart.js\"></script>\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("\t\r\n");
      out.write("\t.redlink  { \r\n");
      out.write("\tcolor:#000000 ; \r\n");
      out.write("\ttext-decoration:none; \r\n");
      out.write("\t} \r\n");
      out.write("\t</style>\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("       var loadMask = null;\r\n");
      out.write("       var pendingLoaded   = false;\r\n");
      out.write("       var noticeLoaded    = false;\r\n");
      out.write("       var quickMenuLoaded = false;\r\n");
      out.write("       \r\n");
      out.write("       var currentDate = getCurDate(); \r\n");
      out.write("       function showLoadMask(){\r\n");
      out.write("    \t   if(!loadMask){\r\n");
      out.write("    \t\t   loadMask = new tracywindyLoadMask(document.body,\"数据加载中  请稍后...\");\r\n");
      out.write("    \t   }\r\n");
      out.write("    \t   loadMask.show();\r\n");
      out.write("       }\r\n");
      out.write("       function hideLoadMask(){\r\n");
      out.write("    \t   loadMask.hide();\r\n");
      out.write("       }\r\n");
      out.write("       function loadPendingInfo(){\r\n");
      out.write("    \t  pendingLoaded = false;\r\n");
      out.write("    \t  showLoadMask();\r\n");
      out.write("          //待办事宜\r\n");
      out.write("\t      ajaxRequest({\r\n");
      out.write("\t\t        url:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/table/getTableData.action\",\r\n");
      out.write("\t\t        async:true,\r\n");
      out.write("\t\t        success:function(response)\r\n");
      out.write("\t\t        {    \r\n");
      out.write("\t\t        \tvar rt = (response.responseText);\r\n");
      out.write("\t\t        \tvar jsonData = JsonUtil.decode(rt);\r\n");
      out.write("\t\t        \tvar $topLeftContentDiv = jQuery(\"#id_top_left_content_div\");\r\n");
      out.write("\t\t        \t$topLeftContentDiv.html(\"\");\r\n");
      out.write("\t\t            if((typeof(jsonData.norecord)!='undefined')&&(jsonData.norecord=='true'))\r\n");
      out.write("\t\t    \t    {\r\n");
      out.write("\t\t            \t$topLeftContentDiv.html(\"暂无需要处理的待办任务!\");\r\n");
      out.write("\t\t    \t    }\r\n");
      out.write("\t\t            else\r\n");
      out.write("\t\t            {\r\n");
      out.write("\t\t\t            var datas = jsonData.datas;\r\n");
      out.write("\t\t\t            var pendingTable = document.createElement(\"table\");\r\n");
      out.write("\t\t\t            var $pendingTable = jQuery(pendingTable);\r\n");
      out.write("\t\t\t            $pendingTable.css({width:'100%'});\r\n");
      out.write("\t\t\t            $topLeftContentDiv[0].appendChild(pendingTable);\r\n");
      out.write("\t\t\t            var pendingTbody = document.createElement(\"tbody\");\r\n");
      out.write("\t\t\t            pendingTable.appendChild(pendingTbody);\r\n");
      out.write("\t\t\t            var idx=0;\r\n");
      out.write("\t\t\t            for(var i=0;i<datas.length;i++){\r\n");
      out.write("\t\t\t               var pendingTr          =  document.createElement(\"tr\");\r\n");
      out.write("\t\t\t\t  \t\t   var bgClass =\"x-panel-table-data-row-\";\r\n");
      out.write("\t\t\t\t  \t\t \t if((i+1)%2==0)\r\n");
      out.write("\t\t\t\t  \t\t \t {\r\n");
      out.write("\t\t\t\t  \t\t \t\tbgClass+=\"even\";\r\n");
      out.write("\t\t\t\t  \t\t \t }\r\n");
      out.write("\t\t\t\t  \t\t \t else\r\n");
      out.write("\t\t\t\t  \t\t \t {\r\n");
      out.write("\t\t\t\t  \t\t \t\tbgClass+=\"odd\";\r\n");
      out.write("\t\t\t\t  \t\t \t }\r\n");
      out.write("\t\t\t\t  \t\t \tpendingTr.className = bgClass;\r\n");
      out.write("\t\t                    pendingTbody.appendChild(pendingTr);\r\n");
      out.write("\t                       var data             = datas[i];\r\n");
      out.write("\t                       var projectname      = data[\"projectname\"]||\"\";\r\n");
      out.write("\t                       var workflowname     = data[\"workflowname\"];\r\n");
      out.write("\t                       var taskname         = data[\"taskname\"];\r\n");
      out.write("\t                       var taskstart        = data[\"taskstart\"];\r\n");
      out.write("\t                       var tasktype         = data[\"tasktype\"];\r\n");
      out.write("\t                       var taskid           = data[\"taskid\"];\r\n");
      out.write("\t                       var actorid          = data[\"actorid\"];\r\n");
      out.write("\t                       var taskTypeChineseName = getTaskTypeChineseName(tasktype);\r\n");
      out.write("\t                       var content          = \"[ \"+taskTypeChineseName+\" ( \"+taskstart+\" ) \"+\"]&nbsp;\";\r\n");
      out.write("\t                       content+=workflowname+\" -> \"+taskname+\" -> \"+projectname ;\r\n");
      out.write("\t                       if (data[\"sourcetype\"] ==\"退回\")\r\n");
      out.write("\t                       {\r\n");
      out.write("\t                    \t   var    tempHtml = '<a   href=\"javascript:void(0);\"  style=\"color:red\"  onclick=\"toProcessForm('+taskid+',\\''+actorid+'\\',\\''+tasktype+'\\')\">'+content+'-@^_^@被退回</a>';\r\n");
      out.write("\t                       }\r\n");
      out.write("\t                       else\r\n");
      out.write("\t                    \t{\r\n");
      out.write("\t                   \t          tempHtml = '<a href=\"javascript:void(0);\"    onclick=\"toProcessForm('+taskid+',\\''+actorid+'\\',\\''+tasktype+'\\')\">'+content+'</a>';\r\n");
      out.write("\t                    \t }\r\n");
      out.write("\t                   \t   var pendingTd          =  document.createElement(\"td\");\r\n");
      out.write("\t                   \t   pendingTd.innerHTML    = tempHtml;\r\n");
      out.write("\t                   \t   pendingTr.appendChild(pendingTd);\r\n");
      out.write("\t\t                 }\r\n");
      out.write("\t\t            }\r\n");
      out.write("    \t            pendingLoaded   = true;\r\n");
      out.write("    \t            if(noticeLoaded && quickMenuLoaded){\r\n");
      out.write("    \t            \thideLoadMask();\r\n");
      out.write("    \t            }\r\n");
      out.write("\t\t        },\r\n");
      out.write("\t\t        failure:function(response){ },\r\n");
      out.write("\t\t        params:{\r\n");
      out.write("\t\t        \txmlFileName:'/jbpm/queryPendingTasks.xml',\r\n");
      out.write("\t\t      \t\tUSERID:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope['login_userid']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\",\r\n");
      out.write("\t\t      \t\tNOTPROCESSINSTANCESTATE:'Draft',\r\n");
      out.write("\t\t      \t\tqueryText:jQuery(\"#id_queryPendingsTableInput\").val(),\r\n");
      out.write("\t\t      \t\tPENDING:true\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t     });\r\n");
      out.write("            }\r\n");
      out.write("\t        function toProcessForm(currentTaskId,planActorId,tasktype)\r\n");
      out.write("\t        {\r\n");
      out.write("\t        \tvar url = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/jbpm/requestProcessTaskForm.action?currentTaskId=\"+currentTaskId+\"&jbpmWorkflowHistoryInfoUserId=\"+planActorId+\"&currentRequestTaskType=\"+tasktype;\r\n");
      out.write("\t        \topenFullScreenWindow(url);\r\n");
      out.write("\t        }\r\n");
      out.write("\t    var newsNoticeContentPrefix = \"id_newsNoticeContent_\";\r\n");
      out.write("\t    function loadNoticeInfo(){\r\n");
      out.write("\t    \tnoticeLoaded = false;\r\n");
      out.write("\t    \tshowLoadMask();\r\n");
      out.write("\t        //公告通知\r\n");
      out.write("\t\t      ajaxRequest({\r\n");
      out.write("\t\t        url:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/table/getTableData.action\",\r\n");
      out.write("\t\t        async:true,\r\n");
      out.write("\t\t        success:function(response)\r\n");
      out.write("\t\t        {    \r\n");
      out.write("\t\t        \tvar rt = (response.responseText);\r\n");
      out.write("\t\t        \tvar jsonData = JsonUtil.decode(rt);\r\n");
      out.write("\t\t        \tvar $topMiddleContentDiv = jQuery(\"#id_top_middle_content_div\");\r\n");
      out.write("\t\t            if((typeof(jsonData.norecord)!='undefined')&&(jsonData.norecord=='true'))\r\n");
      out.write("\t\t    \t    {\r\n");
      out.write("\t\t            \t$topMiddleContentDiv.html(\"暂未发布新公告!\");\r\n");
      out.write("\t\t    \t    }\r\n");
      out.write("\t\t            else\r\n");
      out.write("\t\t            {\r\n");
      out.write("\t\t\t            var datas = jsonData.datas;\r\n");
      out.write("\t\t\t            var noticeTable = document.createElement(\"table\");\r\n");
      out.write("\t\t\t            var $noticeTable = jQuery(noticeTable);\r\n");
      out.write("\t\t\t            $noticeTable.css({width:'100%'});\r\n");
      out.write("\t\t\t            $topMiddleContentDiv[0].appendChild(noticeTable);\r\n");
      out.write("\t\t\t            var noticeTbody = document.createElement(\"tbody\");\r\n");
      out.write("\t\t\t            noticeTable.appendChild(noticeTbody);\r\n");
      out.write("\t\t\t            for(var i=0;i<datas.length;i++){\r\n");
      out.write("\t\t\t               var noticeTr          =  document.createElement(\"tr\");\r\n");
      out.write("\t\t\t\t  \t\t   var bgClass =\"x-panel-table-data-row-\";\r\n");
      out.write("\t\t\t\t  \t\t \t if((i+1)%2==0)\r\n");
      out.write("\t\t\t\t  \t\t \t {\r\n");
      out.write("\t\t\t\t  \t\t \t\tbgClass+=\"even\";\r\n");
      out.write("\t\t\t\t  \t\t \t }\r\n");
      out.write("\t\t\t\t  \t\t \t else\r\n");
      out.write("\t\t\t\t  \t\t \t {\r\n");
      out.write("\t\t\t\t  \t\t \t\tbgClass+=\"odd\";\r\n");
      out.write("\t\t\t\t  \t\t \t }\r\n");
      out.write("\t\t\t\t  \t\t   noticeTr.className = bgClass;\r\n");
      out.write("\t\t                   noticeTbody.appendChild(noticeTr);\r\n");
      out.write("\t                       var data        = datas[i];\r\n");
      out.write("\t                       var title       = data[\"title\"]||\"\";\r\n");
      out.write("\t                       var content     = data[\"content\"];\r\n");
      out.write("\t                       var publishDate = data[\"publishdate\"];\r\n");
      out.write("\t                       var noticeTitleTd          =  document.createElement(\"td\");\r\n");
      out.write("\t                       /*content = content.replace(/(\\r|\\n)/gim,\"\");\r\n");
      out.write("\t                       content = content.replace(/\\\"/gim,'&quot;');\r\n");
      out.write("\t                       content = content.replace(/\\'/gim,\"&acute\");*/\r\n");
      out.write("\t                       var tempHtml    = \"<a title='查看详细内容' href='javascript:void(0);' onclick=\\\"preview(\"+i+\")\\\">\"+title+\"</a>\";\r\n");
      out.write("\t\t\t\t\t\t   if( currentDate == publishDate.substring(0,10))\r\n");
      out.write("\t\t\t\t\t\t   {\r\n");
      out.write("\t\t\t\t\t\t\t   tempHtml+=\"&nbsp;<span class='newsNotice'></span>\";\r\n");
      out.write("\t\t\t\t\t\t   }\r\n");
      out.write("\t                       noticeTitleTd.innerHTML    = tempHtml;\r\n");
      out.write("\t                       var newsNoticeContent= document.createElement(\"div\");\r\n");
      out.write("\t                       with(newsNoticeContent){\r\n");
      out.write("\t                    \t   id=newsNoticeContentPrefix+i;\r\n");
      out.write("\t                    \t   innerHTML = content;\r\n");
      out.write("\t                    \t   style.display=\"none\";\r\n");
      out.write("\t                       }\r\n");
      out.write("\t                       noticeTitleTd.appendChild(newsNoticeContent);\r\n");
      out.write("\t                       noticeTr.appendChild(noticeTitleTd);\r\n");
      out.write("\t                       var noticePublishDateTd          =  document.createElement(\"td\");\r\n");
      out.write("\t                       noticePublishDateTd.style.textAlign=\"right\";\r\n");
      out.write("\t                       noticePublishDateTd.innerHTML    = publishDate;\r\n");
      out.write("\t                       noticeTr.appendChild(noticePublishDateTd);\r\n");
      out.write("\t\t\t\t\t    }\r\n");
      out.write("\t\t            }\r\n");
      out.write("    \t            noticeLoaded    = true;\r\n");
      out.write("    \t            if(pendingLoaded && quickMenuLoaded){\r\n");
      out.write("    \t            \thideLoadMask();\r\n");
      out.write("    \t            }\r\n");
      out.write("\t\t        },\r\n");
      out.write("\t\t        failure:function(response){ },\r\n");
      out.write("\t\t        params:{\r\n");
      out.write("\t\t        \txmlFileName:'/acl/queryAllNotice.xml',\r\n");
      out.write("\t\t        \tdeadline:true\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t     });\r\n");
      out.write("\t    }\r\n");
      out.write("        function preview(rowIndex){\r\n");
      out.write("           var content = jQuery(\"#\"+newsNoticeContentPrefix+rowIndex).html();\r\n");
      out.write("     \t   var $previewDetailInfoWindowContainer = jQuery(\"#id_previewDetailInfoWindowContainer\");\r\n");
      out.write("     \t   $previewDetailInfoWindowContainer.show();\r\n");
      out.write("     \t   var $previewDetailInfo = jQuery(\"#id_previewDetailInfo\");\r\n");
      out.write("     \t   $previewDetailInfo.html(content);\r\n");
      out.write("     \t   addNoticeAttachmentDownloadFunction();\r\n");
      out.write("     \t   $previewDetailInfoWindowContainer.window({top:20,draggable:false});\r\n");
      out.write("     \t   $previewDetailInfoWindowContainer.window('open');\r\n");
      out.write("        }\r\n");
      out.write("        //快捷操作\r\n");
      out.write("        function recursionFindFirstLevelIndex(menuJson,newDataArr,compareDataArr){\r\n");
      out.write("            var children = menuJson.children;\r\n");
      out.write("            var childrenLen = children.length;\r\n");
      out.write("            if(0 < childrenLen){\r\n");
      out.write("                for(var i=0;i<childrenLen;i++){\r\n");
      out.write("                \trecursionFindFirstLevelIndex(children[i],newDataArr,compareDataArr);\r\n");
      out.write("                }\r\n");
      out.write("            }else{\r\n");
      out.write("                var checked = menuJson.checked;\r\n");
      out.write("                var currentId = menuJson.id;\r\n");
      out.write("                if(\"true\" == (checked+\"\")){\r\n");
      out.write("                    for(var ii=0;ii<compareDataArr.length;ii++){\r\n");
      out.write("                        var compareData = compareDataArr[ii];\r\n");
      out.write("                        var compareId   = compareData.id_;\r\n");
      out.write("                        if(currentId == compareId){\r\n");
      out.write("                            var newObj = {\r\n");
      out.write("                                    id_  :compareData.id_,\r\n");
      out.write("                                    name_:compareData.name_,\r\n");
      out.write("                                    icon_:compareData.icon_,\r\n");
      out.write("                                    firstLevelMenuId:menuJson.firstLevelMenuId\r\n");
      out.write("                            };\r\n");
      out.write("                            newDataArr.push(newObj);\r\n");
      out.write("                            break;\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("       function loadQuickMenuInfo(){\r\n");
      out.write("    \t   quickMenuLoaded = false;\r\n");
      out.write("\t    \tshowLoadMask();\r\n");
      out.write("\t    \t\r\n");
      out.write("             ajaxRequest({\r\n");
      out.write("            \turl:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/table/getTableData.action\",\r\n");
      out.write("       \t        async:true,\r\n");
      out.write("       \t        success:function(response){\r\n");
      out.write("    \t        \tvar rt = (response.responseText);\r\n");
      out.write("    \t        \tif(!rt)$topRightContentDiv.html(\"您的用户信息发生变动，请联系管理员同步用户权限!\");\r\n");
      out.write("    \t        \tvar jsonData = JsonUtil.decode(rt);\r\n");
      out.write("    \t        \tvar $topRightContentDiv = jQuery(\"#id_top_right_content_div\");\r\n");
      out.write("    \t            if((typeof(jsonData.norecord)!='undefined')&&(jsonData.norecord=='true'))\r\n");
      out.write("    \t    \t    {\r\n");
      out.write("    \t            \t$topRightContentDiv.html(\"暂未定义快捷操作!\");\r\n");
      out.write("    \t    \t    }\r\n");
      out.write("    \t            else\r\n");
      out.write("    \t            {\r\n");
      out.write("    \t            \tvar compareDataArr = jsonData.datas;\r\n");
      out.write("    \t            \tvar newDataArr          = [];\r\n");
      out.write("    \t\t            ajaxRequest({\r\n");
      out.write("    \t\t            \turl:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/acl/getUserQuickMenuTreeData.acl',\r\n");
      out.write("                            success:function(res){\r\n");
      out.write("                                  var jsonChildren = JsonUtil.decode(res.responseText);\r\n");
      out.write("                                  for(var k = 0;k < jsonChildren.length;k++){\r\n");
      out.write("                                        recursionFindFirstLevelIndex(jsonChildren[k],newDataArr,compareDataArr);\r\n");
      out.write("                                  }\r\n");
      out.write("\t\t    \t\t          \t  for(var i=0;i<newDataArr.length;i++)\r\n");
      out.write("\t\t\t    \t\t          {\r\n");
      out.write("\t\t    \t    \t               \t var data             = newDataArr[i];\r\n");
      out.write("\t\t    \t    \t               \t var menuId\t\t      = data[\"id_\"];\r\n");
      out.write("\t\t    \t    \t               \t var text             = data[\"name_\"];\r\n");
      out.write("\t\t    \t    \t               \t var icon \t\t      = data[\"icon_\"];\r\n");
      out.write("\t\t    \t    \t               \t var firstLevelMenuId = data[\"firstLevelMenuId\"];\r\n");
      out.write("\t\t    \t    \t               \t \r\n");
      out.write("\t\t    \t    \t               \t var $divContainer = $(\"<div></div>\");\r\n");
      out.write("\t\t    \t    \t       \t         $topRightContentDiv.append($divContainer);\r\n");
      out.write("\t\t    \t    \t       \t         $divContainer.css(\"border-bottom\",\"1px solid #DDD\");\r\n");
      out.write("\t\t    \t    \t       \t         $divContainer.css(\"cursor\",\"pointer\");\r\n");
      out.write("\t\t    \t    \t       \t         $divContainer.css(\"padding\",\"2px\");\r\n");
      out.write("\t\t    \t    \t       \t         $divContainer.css(\"textIndent\",\"10px\");\r\n");
      out.write("\t\t    \t    \t       \t         $divContainer.css(\"marginBottom\",\"5px\");\r\n");
      out.write("\t\t    \t    \t       \t         $divContainer.css(\"background\",\"#D4E1F2\");\r\n");
      out.write("\t\t    \t    \t       \t         $divContainer.css(\"line-height\",\"26px\");\r\n");
      out.write("\t\t    \t    \t       \t\t     var clickFunc = (function(firstLevelMenuId,menuId){return function(e){\r\n");
      out.write("\t\t    \t    \t       \t\t        \twindow.top.doCheckTreeByMenuId(firstLevelMenuId,menuId);\r\n");
      out.write("\t\t    \t    \t       \t\t\t     };})(firstLevelMenuId,menuId);\r\n");
      out.write("\t\t    \t    \t       \t\t     $divContainer.click(clickFunc);\r\n");
      out.write("\t\t    \t    \t       \t         var $img = $(\"<img src='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/menuIcons/\"+icon+\"'/>\");\r\n");
      out.write("\t\t    \t    \t       \t         $img.css(\"verticalAlign\",\"middle\");\r\n");
      out.write("\t\t    \t    \t       \t         $divContainer.append($img);\r\n");
      out.write("\t\t    \t    \t       \t         $divContainer.append(\"<font>&nbsp;</font>\");\r\n");
      out.write("\t\t    \t    \t       \t         var $text = $(\"<a name='\"+menuId+\"'>\"+text+\"</a>\");\r\n");
      out.write("\t\t    \t    \t       \t         $divContainer.append($text);\r\n");
      out.write("\t\t    \t    \t         }\r\n");
      out.write("                            }\r\n");
      out.write("    \t\t\t        });\r\n");
      out.write("        \t        }\r\n");
      out.write("    \t            quickMenuLoaded = true;\r\n");
      out.write("    \t            if(pendingLoaded && noticeLoaded){\r\n");
      out.write("    \t            \thideLoadMask();\r\n");
      out.write("    \t            }\r\n");
      out.write("           \t    },\r\n");
      out.write("       \t        params:{\r\n");
      out.write("           \t        userId:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope['login_userid']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\",\r\n");
      out.write("           \t        xmlFileName:'acl/queryUserQuickMenu.xml'\r\n");
      out.write("           \t    }\r\n");
      out.write("             });\r\n");
      out.write("       }\r\n");
      out.write("        /*\r\n");
      out.write("        //个人消息通知\r\n");
      out.write("        jQuery(function(){\r\n");
      out.write("        \t var $bottomLeftContentDiv = jQuery(\"#id_bottom_left_content_div\");\r\n");
      out.write("        \t $bottomLeftContentDiv.css({\r\n");
      out.write("                 lineHeight:bottomHeight+\"px\",\r\n");
      out.write("                 textAlign:\"center\"\r\n");
      out.write("             });\r\n");
      out.write("        \t $bottomLeftContentDiv.html(\"暂无个人消息通知!\");\r\n");
      out.write("        });\r\n");
      out.write("        //图表信息\r\n");
      out.write("        jQuery(function(){\r\n");
      out.write("              new tracywindyChart({\r\n");
      out.write("                    width: bottomRightWidth+10,\r\n");
      out.write("                    height:bottomHeight+10,\r\n");
      out.write("                    //title:'图表标题',\r\n");
      out.write("                    border:false,\r\n");
      out.write("                    renderTo:\"id_bottom_right_content_div\",\r\n");
      out.write("                    id:'id_chartTest',\r\n");
      out.write("                    swf:'MSCombiDY2D.swf',\r\n");
      out.write("                    xmlFileName:'template.xml'\r\n");
      out.write("              });\r\n");
      out.write("        });*/\r\n");
      out.write("        jQuery(function(){\r\n");
      out.write("        \tloadPendingInfo();\r\n");
      out.write("        \tloadNoticeInfo();\r\n");
      out.write("        \tloadQuickMenuInfo();\r\n");
      out.write("\t       \t document.getElementById(\"id_queryPendingsTableInput\").onkeypress = function(evt){\r\n");
      out.write("\t    \t\t var e  = getEvent(evt);\r\n");
      out.write("\t    \t     var code = e.keyCode||e.charCode;\r\n");
      out.write("\t    \t     if(13 == code){\r\n");
      out.write("\t    \t    \t loadPendingInfo();\r\n");
      out.write("\t    \t     }\r\n");
      out.write("\t    \t };\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<div id='id_top_left' style=\"float:left;overflow:hidden;border:0px solid #DDD;padding:5px;\">\r\n");
      out.write("\t   <div class=\"panel-title\">待办事宜\r\n");
      out.write("\t     <SPAN>搜索：<INPUT style=\"BORDER-BOTTOM: #ddd 1px solid; BORDER-LEFT: #ddd 1px solid; WIDTH: 150px; BORDER-TOP: #ddd 1px solid; MARGIN-RIGHT: 4px; BORDER-RIGHT: #ddd 1px solid\" id=id_queryPendingsTableInput type=\"text\" jQuery18205254865307538132=\"34\"></SPAN>\r\n");
      out.write("\t   </div>\r\n");
      out.write("       <div id=\"id_top_left_content_div\" style=\"border:1px solid #DDD;border-top:0px;overflow:auto;padding:5px;\" ></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id='id_top_middle' style=\"overflow:hidden;float:left;border-bottom:0px solid #DDD;padding:5px;\">\r\n");
      out.write("\t   <div class=\"panel-title\" ><font color=\"red\" class=\"flagUserSelectContainer\"></font>公告通知</div>\r\n");
      out.write("\t   <div id='id_top_middle_content_div' style=\"border:1px solid #DDD;border-top:0px;overflow:auto;padding:5px;\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id='id_top_right' style=\"overflow:hidden;float:left;border:0px solid #DDD;border-left:0px;border-top:0px;padding:5px;\">\r\n");
      out.write("\t   <div class=\"panel-title\" ><font color=\"red\" class=\"flagUserSelectContainer\"></font>快捷操作</div>\r\n");
      out.write("\t   <div id='id_top_right_content_div' style=\"border:1px solid #DDD;border-top:0px;overflow:auto;padding:5px;\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<!-- \r\n");
      out.write("\t<div id='id_bottom_left' style=\"overflow:hidden;float:left;border:0px solid #DDD;border-left:0px;border-top:0px;padding:5px;\">\r\n");
      out.write("\t   <div class=\"panel-title\" ><font color=\"red\" class=\"flagUserSelectContainer\"></font>个人消息通知</div>\r\n");
      out.write("\t   <div id='id_bottom_left_content_div' style=\"border:1px solid #DDD;border-top:0px;overflow:auto;padding:5px;\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id='id_bottom_right' style=\"overflow:hidden;float:left;border:0px solid #DDD;border-left:0px;border-top:0px;padding:5px;\">\r\n");
      out.write("\t   <div class=\"panel-title\" ><font color=\"red\" class=\"flagUserSelectContainer\"></font>图表信息</div>\r\n");
      out.write("\t   <div id='id_bottom_right_content_div' style=\"border:1px solid #DDD;border-top:0px;overflow:hidden;padding:0px;\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t-->\r\n");
      out.write("\t<script type='text/javascript'>\r\n");
      out.write("\t\tvar pageWidth  = document.documentElement.clientWidth;\r\n");
      out.write("\t\tvar pageHeight = document.documentElement.clientHeight-10;\r\n");
      out.write("        var topLeftWidth   = 600;\r\n");
      out.write("        var topMiddleWidth = (pageWidth - topLeftWidth - 66 )/1.5; \r\n");
      out.write("        var topRightWidth  = (pageWidth - topLeftWidth - 66 ) - topMiddleWidth; \r\n");
      out.write("        \r\n");
      out.write("\t    var topHeight     =  pageHeight-40;//pageHeight/2;\r\n");
      out.write("\t    var bottomHeight  =  pageHeight - topHeight - 100;\r\n");
      out.write("\r\n");
      out.write("        var bottomLeftWidth  = topLeftWidth  ;\r\n");
      out.write("        var bottomRightWidth = pageWidth - bottomLeftWidth - 45 ;\r\n");
      out.write("\t    \r\n");
      out.write("\t\tjQuery(\"#id_top_left_content_div\").css(\"height\",topHeight+\"px\");\r\n");
      out.write("\t\tjQuery(\"#id_top_middle_content_div\").css(\"height\",topHeight+\"px\");\r\n");
      out.write("\t\tjQuery(\"#id_top_right_content_div\").css(\"height\",topHeight+\"px\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tjQuery(\"#id_top_left_content_div\").css(\"width\",topLeftWidth+\"px\");\r\n");
      out.write("\t\tjQuery(\"#id_top_left>div.panel-title\").css(\"width\",(topLeftWidth+10)+\"px\");\r\n");
      out.write("\t\tjQuery(\"#id_top_middle_content_div\").css(\"width\",topMiddleWidth+\"px\");\r\n");
      out.write("\t\tjQuery(\"#id_top_middle>div.panel-title\").css(\"width\",(topMiddleWidth+10)+\"px\");\r\n");
      out.write("\t\tjQuery(\"#id_top_right_content_div\").css(\"width\",topRightWidth+\"px\");\r\n");
      out.write("\t\tjQuery(\"#id_top_right>div.panel-title\").css(\"width\",(topRightWidth+10)+\"px\");\r\n");
      out.write("\t\tjQuery(\"#id_bottom_left_content_div\").css(\"height\",bottomHeight+\"px\");\r\n");
      out.write("\t\tjQuery(\"#id_bottom_right_content_div\").css(\"height\",bottomHeight+\"px\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tjQuery(\"#id_bottom_left_content_div\").css(\"width\",bottomLeftWidth+\"px\");\r\n");
      out.write("\t\tjQuery(\"#id_bottom_left>div.panel-title\").css(\"width\",(bottomLeftWidth+10)+\"px\");\r\n");
      out.write("\t\tjQuery(\"#id_bottom_right_content_div\").css(\"width\",bottomRightWidth+\"px\");\r\n");
      out.write("\t\tjQuery(\"#id_bottom_right>div.panel-title\").css(\"width\",(bottomRightWidth+10)+\"px\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("\t<div id=\"id_previewDetailInfoWindowContainer\"  closable=\"true\" closed=\"true\" modal=\"true\" title=\"公告内容\" style=\"display:none;\">\r\n");
      out.write("\t     <div id=\"id_previewDetailInfo\" style=\"text-align:left;padding:5px\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<form method=\"post\" target=\"fileDownloadIframe\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/acl/downloadNoticeUploadFile.acl\" id=\"id_nameForm\">\r\n");
      out.write("\t  <input name=\"type\" type=\"hidden\" value=\"file\" />\r\n");
      out.write("\t  <input name=\"uuid\"  type=\"hidden\" value=\"\"/>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t<iframe name=\"fileDownloadIframe\" style=\"display:none;\"></iframe>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t   \tjQuery(\"#id_previewDetailInfoWindowContainer\").css(\"height\",(pageHeight-40)+\"px\");\r\n");
      out.write("\t   \tjQuery(\"#id_previewDetailInfoWindowContainer\").css(\"width\",(pageWidth-20)+\"px\");\r\n");
      out.write("\t    function addNoticeAttachmentDownloadFunction()\r\n");
      out.write("\t    {\r\n");
      out.write("\t \t   jQuery(\"#id_previewDetailInfo a.tracywindyFileDownLoadSpan\").each(function(i){\r\n");
      out.write("\t \t\t   this.style.cursor = \"pointer\";\r\n");
      out.write("\t \t\t   this.title = \"点击下载文件\";\r\n");
      out.write("\t \t\t   this.style.color = \"blue\";\r\n");
      out.write("\t \t\t   this.href=\"javascript:void(0)\";\r\n");
      out.write("\t \t\t   this.style.fontWeight = \"BOLD\";\r\n");
      out.write("\t \t\t   var oldClassStr = (this.className||\"\").replace(/\\s{1,}/gm,\" \");\r\n");
      out.write("\t \t\t   var oldClassArr = oldClassStr.split(\" \");\r\n");
      out.write("\t \t\t   for(var i=0;i<oldClassArr.length;i++){\r\n");
      out.write("\t \t\t\t   var className = oldClassArr[i]||\"\";\r\n");
      out.write("\t \t\t\t   if(0 == className.indexOf(\"uuid-\")){\r\n");
      out.write("\t \t\t\t\t   var uuid = className.substring(\"uuid-\".length,className.length);\r\n");
      out.write("\t \t\t\t\t   var clickFunc = (function(uuid){\r\n");
      out.write("\t \t\t\t\t\t   return function(e){\r\n");
      out.write("\t \t\t\t\t\t\t   jQuery(\"#id_nameForm input[name='uuid']\").val(uuid);\r\n");
      out.write("\t \t\t\t\t\t\t   jQuery(\"#id_nameForm\")[0].submit();\r\n");
      out.write("\t \t\t\t\t\t\t   return false;\r\n");
      out.write("\t \t\t\t\t\t   };\r\n");
      out.write("\t \t\t\t\t   })(uuid);\r\n");
      out.write("\t \t\t\t\t   this.onclick = clickFunc;\r\n");
      out.write("\t \t\t\t   }\r\n");
      out.write("\t \t\t   }\r\n");
      out.write("\t \t   });\r\n");
      out.write("\t   }\r\n");
      out.write("\t</script>\r\n");
      out.write("\t\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
