package org.apache.jsp.WEB_002dINF.jsps.solutions.workflow.forms.project.proj_005fapproval;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class proj_005fequip_005fdetail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.List<java.lang.String> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.List<java.lang.String> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction validataTotalMoney() {//验证金额，add by Jason ###蔡雅超8-15改\r\n");
      out.write("\t\tif (chenckCondiotn) {\r\n");
      out.write("\t\t\t//计算租赁物的总交易价格\r\n");
      out.write("\t\t\tvar currentTable1 = getTracywindyObject('table_id_table_leasing_proj_equip_container');\r\n");
      out.write("\t\t\tvar data = currentTable1.tableData;\r\n");
      out.write("\t\t\tvar totalPrice = 0;\r\n");
      out.write("\t\t\tfor ( var i = 0; i < data.length; i++) {\r\n");
      out.write("\t\t\t\ttotalPrice += parseFloat(data[i]['nowtotal']);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t//计算商务条件的设备款\r\n");
      out.write("\t\t\tvar equipAmt = parseFloat($(\"#equipAmt\").val());\r\n");
      out.write("\t\t\tif (totalPrice != equipAmt) {//如果不相等，则跳出执行\r\n");
      out.write("\t\t\t\talert(\"【租赁物明细】标签的合计总价[\" + totalPrice + \"]和【拟商务条件】标签中的设备款[\" + equipAmt + \"]不相等,请检查.\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t} else {\r\n");
      out.write("\t\t\t\treturn true;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t} else {\r\n");
      out.write("\t\t\talert(\"您修改过商务条件中的值且未进行过测算!\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("function AdjustMoney(){//算出差额\r\n");
      out.write("\tvar differential_swap=$(\"#id_differential_swap\");\r\n");
      out.write("\tvar purchaseprice=$(\"#id_purchaseprice\").val();\r\n");
      out.write("\tvar saleprice=$(\"#id_saleprice\").val();\r\n");
      out.write("\tpurchaseprice=purchaseprice||0;\r\n");
      out.write("\tsaleprice=saleprice||0;\r\n");
      out.write("\tvar temp=parseFloat(saleprice)-parseFloat(purchaseprice);\r\n");
      out.write("\t$(\"#id_differential_swap\").val(temp.toFixed(2));\r\n");
      out.write("}\r\n");
      out.write("function AdjustTotal(){//算出总价---总计[销售价+购置税+保费+其他融资额]\r\n");
      out.write("\tvar differential_swap=$(\"#id_nowtotal\");\r\n");
      out.write("\tvar equipnum=$(\"#id_equipnum\").val();\r\n");
      out.write("\tvar saleprice=$(\"#id_saleprice\").val();\r\n");
      out.write("\tvar purchasetax=$(\"#id_purchasetax\").val();\r\n");
      out.write("\tvar insuremoney=$(\"#id_insuremoney\").val();\r\n");
      out.write("\tvar leasingmoney=$(\"#id_leasingmoney\").val();\r\n");
      out.write("\tequipnum=equipnum||0;\r\n");
      out.write("\tsaleprice=saleprice||0;\r\n");
      out.write("\tpurchasetax=purchasetax||0;\r\n");
      out.write("\tinsuremoney=insuremoney||0;\r\n");
      out.write("\tleasingmoney=leasingmoney||0;\r\n");
      out.write("\t//Edit by Jason 2013-11-23 为temp添加var 变成局部变量\r\n");
      out.write("\tvar temp=parseFloat(saleprice)*parseFloat(equipnum)+parseFloat(purchasetax)+parseFloat(insuremoney)+parseFloat(leasingmoney);\r\n");
      out.write("\t$(\"#id_nowtotal\").val(temp.toFixed(2));\r\n");
      out.write("}\r\n");
      out.write("var nominalPrice = $(\"#nominalPrice\");\r\n");
      out.write("var liugoujiasum = 0;\r\n");
      out.write("jQuery(function(){\r\n");
      out.write("\t    var currentIsNeedTools = true;\r\n");
      out.write("\t    var equipclassname=\"\";\r\n");
      out.write("\t    var equiptypename =\"\";\r\n");
      out.write("\t    var modelname     = \"\";\r\n");
      out.write("\t    new tracywindyMultiTable({\r\n");
      out.write("\t    renderTo:'id_table_leasing_proj_equip_container',\r\n");
      out.write("\t    width:formWidth,\r\n");
      out.write("\t    isAutoHeight:true,\r\n");
      out.write("\t    isShowCopyCount:true,\r\n");
      out.write("\t    isNeedTools:currentIsNeedTools,\r\n");
      out.write("\t    isFit:false,\r\n");
      out.write("\t    tools:'新增|复制|修改|删除',\r\n");
      out.write("\t    copyOperChangeDataCallBack:function($me,currentTable,newRowData){//复制回调函数\r\n");
      out.write("\t    \tnewRowData['chassisnum'] = '';\r\n");
      out.write("\t    },\r\n");
      out.write("\t    updateFromOperCallBack:function(operType,thisForm,me,rowData){\r\n");
      out.write("\t    \t//console.info(operType);\r\n");
      out.write("\t    \t if(operType==\"update\"){\r\n");
      out.write("\t    \t\t temp_chassisnum = rowData['chassisnum'];\r\n");
      out.write("\t\t\t\t  for(var i=0;i<me.comboboxs.length;i++){\r\n");
      out.write("\t\t\t    \t   var combo =me.comboboxs[i];\r\n");
      out.write("\t\t\t    \t   if(combo.otherConfig.name==\"equipclassname\"){\r\n");
      out.write("\t\t\t    \t\t   equipclassname=rowData[\"equipclass\"];//combo.getValue();\r\n");
      out.write("\t\t\t\t       }\r\n");
      out.write("\t\t\t    \t   if(combo.otherConfig.name==\"equiptypename\"){\r\n");
      out.write("\t\t\t    \t\t   equiptypename = rowData[\"equiptype\"];\r\n");
      out.write("\t\t\t    \t\t   combo.setParams({equipclass:equipclassname});\r\n");
      out.write("\t\t\t    \t\t   combo.value=equiptypename;\r\n");
      out.write("\t\t\t\t    \t   combo.reload();\r\n");
      out.write("\t\t\t\t       }\r\n");
      out.write("\t\t\t    \t   if(combo.otherConfig.name==\"modelname\"){\r\n");
      out.write("\t\t\t    \t\t   modelname = rowData[\"model\"];\r\n");
      out.write("\t\t\t    \t\t   combo.setParams({equipclass:equipclassname,equiptype:equiptypename});\r\n");
      out.write("\t\t\t    \t\t   combo.value=modelname;\r\n");
      out.write("\t\t\t\t    \t   combo.reload();\r\n");
      out.write("\t\t\t\t       }\r\n");
      out.write("\t\t\t\t\t    if(combo.otherConfig.name==\"isaffiliated\"){\r\n");
      out.write("\t\t\t\t\t   \t\tisaffiliated = rowData[\"isaffiliatedname\"];\r\n");
      out.write("\t\t\t\t\t\t\tvar affiliatedinfo = $(\"#id_affiliatedinfo\");\r\n");
      out.write("\t\t\t\t\t\t\tif(isaffiliated == \"是\"){\r\n");
      out.write("\t\t\t\t\t\t\t\taffiliatedinfo.attr(\"require\",\"true\").attr(\"label\",\"挂靠信息\");\r\n");
      out.write("\t\t\t\t\t\t\t\taffiliatedinfo.show();\r\n");
      out.write("\t\t\t\t\t\t        affiliatedinfo.parent().parent().show();\r\n");
      out.write("\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\taffiliatedinfo.hide();\r\n");
      out.write("\t\t\t\t\t\t\t\taffiliatedinfo.parent().parent().hide();\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t   }\r\n");
      out.write("\t\t\t\t   \r\n");
      out.write("\t\t\t\t   }\r\n");
      out.write("\t\t\t  }\r\n");
      out.write("\t\t\t  \t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t    },\r\n");
      out.write("\t\tresetFromOperCallBack:function(operType,thisForm,me){\r\n");
      out.write("\t\t\tif(operType==\"add\"){\r\n");
      out.write("\t\t  \tvar affiliatedinfo = $(\"#id_affiliatedinfo\");\r\n");
      out.write("\t\t\t  for(var i=0;i<me.comboboxs.length;i++){\r\n");
      out.write("\t\t    \t   var combo =me.comboboxs[i];\r\n");
      out.write("\t\t    \t    if(combo.otherConfig.name==\"isaffiliated\"){\r\n");
      out.write("\t\t\t\t\t\tif (combo.value == \"1\") {\r\n");
      out.write("\t\t\t\t\t\t\taffiliatedinfo.hide();\r\n");
      out.write("\t\t\t\t\t\t\taffiliatedinfo.parent().parent().hide();\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t   }\r\n");
      out.write("\t\t\t   }\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t  }\r\n");
      out.write("          return true;  \r\n");
      out.write("\t\t},\r\n");
      out.write("\t\toperValidate:function(operType,rowDatas,thisForm,me){\r\n");
      out.write("\t\t\t  if(operType==\"add\"){\r\n");
      out.write("\t\t\t  \tvar affiliatedinfo = $(\"#id_affiliatedinfo\");\r\n");
      out.write("\t\t\t\t  for(var i=0;i<me.comboboxs.length;i++){\r\n");
      out.write("\t\t\t    \t   var combo =me.comboboxs[i];\r\n");
      out.write("\t\t\t    \t   if(combo.otherConfig.name==\"equiptypename\"){\r\n");
      out.write("\t\t\t\t    \t   combo.setParams({equipclass:'1'});\r\n");
      out.write("\t\t\t\t    \t   combo.reload();\r\n");
      out.write("\t\t\t\t       }\r\n");
      out.write("\t\t\t    \t   if(combo.otherConfig.name==\"modelname\"){\r\n");
      out.write("\t\t\t    \t\t   combo.setParams({equipclass:'1',equiptype:'1'});\r\n");
      out.write("\t\t\t\t    \t   combo.reload();\r\n");
      out.write("\t\t\t\t       }\r\n");
      out.write("\t\t\t\t   }\r\n");
      out.write("\t\t\t//删除操作的时候 ：留购价款=100元*车头数，车头数即非挂车数量\r\n");
      out.write("\t\t\t  }else if(operType==\"remove\"){\r\n");
      out.write("\t\t\t\t\tif (rowDatas[0].equipclass != \"equip_class_2\") {\r\n");
      out.write("\t\t\t\t\t\t if (nominalPrice != \"\" && nominalPrice != null) {\r\n");
      out.write("\t\t\t\t\t\t\tvar tabledata = getTracywindyObject('table_id_table_leasing_proj_equip_container').getCheckedRowDatas();\r\n");
      out.write("\t\t\t\t\t\t\tvar numsx =0;\r\n");
      out.write("\t\t\t\t\t\t\tfor (var inc = 0; inc<tabledata.length; inc++)\r\n");
      out.write("\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\tif (tabledata[inc].equipclass != \"equip_class_2\")\r\n");
      out.write("\t\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\t\tnumsx ++;\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\tvar nums =  parseFloat(nominalPrice.val()) - parseFloat(numsx *100);\r\n");
      out.write("\t\t \t\t\t\t\tnominalPrice.val(nums);\r\n");
      out.write("\t\t \t\t\t\t\t//ie以外的浏览器需要不支持js改变值的事件，需重新计算商务条件\r\n");
      out.write("\t\t \t\t\t\t\tequipAmt();\r\n");
      out.write("\t\t \t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t  }\r\n");
      out.write("\t          return true;  \r\n");
      out.write("\t\t    },\r\n");
      out.write("\t\t  //新增修改操作的时候：留购价款=100元*车头数，车头数即非挂车数量\r\n");
      out.write("\t\t\tvalidateForm:function($me,currentTable){\r\n");
      out.write("\t\t\t\t/*\r\n");
      out.write("\t\t    \tif(Validator.Validate(jQuery(\"#\"+$me.windowId+\" form\")[0],1,false)){\r\n");
      out.write("\t\t\t\t\t for (var i = 0; i < $me.comboboxs.length; i++) {\r\n");
      out.write("\t\t\t\t\t \tvar combo = $me.comboboxs[i];\r\n");
      out.write("\t\t\t\t\t\tif (combo.otherConfig.name == \"equipclassname\") {\r\n");
      out.write("\t\t\t\t\t\t\tif (combo.valueHidden.value != \"equip_class_2\") {\r\n");
      out.write("\t\t\t\t\t\t\t\tliugoujiasum++;\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t }\r\n");
      out.write("\t\t\t\t\t$(\"#nominalPrice\").val(100*liugoujiasum);\r\n");
      out.write("\t\t\t\t\t//ie以外的浏览器需要不支持js改变值的事件，需重新计算商务条件\r\n");
      out.write("\t\t\t\t\tequipAmt();\r\n");
      out.write("\t\t\t\t\treturn true;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t*/\r\n");
      out.write("\t\t\t\tif(Validator.Validate(jQuery(\"#\"+$me.windowId+\" form\")[0],1,false)){\r\n");
      out.write("\t\t\t\t\t//modify by caiyc 2014-6-16\r\n");
      out.write("\t\t\t\t\tvar tableRowData = getTracywindyObject('table_id_table_leasing_proj_equip_container')\r\n");
      out.write("\t\t\t\t\t                   .getRowsData();\r\n");
      out.write("\t\t\t\t\tvar much = 0;\r\n");
      out.write("\t\t\t\t\tif ($me.flag != \"update\")  //修改按钮不改变留购价\r\n");
      out.write("\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\tfor (var incx = 0; incx < tableRowData.length; incx++)\r\n");
      out.write("\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\tif (tableRowData[incx].equipclass == \"equip_class_2\" && tableRowData[incx].equipclassname == \"挂车\")\r\n");
      out.write("\t\t\t\t\t\t\t{}\r\n");
      out.write("\t\t\t\t\t\t\telse\r\n");
      out.write("\t\t\t\t\t\t\t{\r\n");
      out.write("\t\t\t\t\t\t\t\tmuch ++; //算出现租赁物非挂车数量\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t for (var i = 0; i < $me.comboboxs.length; i++) {\r\n");
      out.write("\t\t\t\t\t\t \tvar combo = $me.comboboxs[i];\r\n");
      out.write("\t\t\t\t\t\t\tif (combo.otherConfig.name == \"equipclassname\") {\r\n");
      out.write("\t\t\t\t\t\t\t\tif (combo.valueHidden.value == \"equip_class_2\") {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvar nop = parseFloat(100*much) + parseFloat(100);\r\n");
      out.write("\t\t\t\t\t\t\t\t\t$(\"#nominalPrice\").val(nop);\r\n");
      out.write("\t\t\t\t\t\t\t\t    }\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tequipAmt();\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\treturn true;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t    datas:JsonUtil.decode('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty json_proj_equip_str ? \"[]\" : json_proj_equip_str }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("'),\r\n");
      out.write("\t    columns:[\r\n");
      out.write("\t       {name:'id', header:'id',hidden:true},\r\n");
      out.write("\t       {name:'projid', header:'projid',hidden:true},\r\n");
      out.write("\t       {name:'equipclassname', header:'车辆分类',type:'combobox',nullable:false,hiddenName:'equipclass',\r\n");
      out.write("\t\t\t    config:{\r\n");
      out.write("\t\t\t    \t   //id:'id_combobox_equipclassname',\r\n");
      out.write("\t\t\t\t       width:165,\r\n");
      out.write("\t\t\t\t       xmlFileName:'\\\\eleasing\\\\workflow\\\\proj_approval\\\\equipClassSelect.xml',\r\n");
      out.write("\t\t\t\t       loadMode:'ajax',\r\n");
      out.write("\t\t\t\t       readOnly:false,\r\n");
      out.write("\t\t\t\t       isAjaxLenovo:true,\r\n");
      out.write("\t\t\t\t       displayField:'name',\r\n");
      out.write("\t\t\t\t       valueField:'code',\r\n");
      out.write("\t\t\t\t       isForceModify:true,\r\n");
      out.write("\t\t\t\t       otherConfig:{\r\n");
      out.write("\t\t\t\t\t\t\t  name:'equipclassname',\r\n");
      out.write("\t\t\t\t\t\t\t  hiddenName:'equipclass'\r\n");
      out.write("\t\t   \t\t\t   },\r\n");
      out.write("\t\t\t\t       onSelected:function(combo,rowData,me,columnConfig){\r\n");
      out.write("\t    \t   \t\t\t   var equipclassValue  = combo.getValue();\r\n");
      out.write("\t\t\t\t    \t   for(var i=0;i<me.comboboxs.length;i++){\r\n");
      out.write("\t\t\t\t\t    \t   var combo =me.comboboxs[i];\r\n");
      out.write("\t\t\t\t/* \t    \t   if(combo.otherConfig.name==\"equiptypename\"){\r\n");
      out.write("\t\t\t\t\t\t    \t   combo.setParams({equipclass:equipclassValue});\r\n");
      out.write("\t\t\t\t\t\t    \t   combo.reload();\r\n");
      out.write("\t\t\t\t\t\t       }\r\n");
      out.write("\t\t\t\t\t    \t   if(combo.otherConfig.name==\"modelname\"){\r\n");
      out.write("\t\t\t\t\t    \t\t   combo.setParams({equipclass:'1',equiptype:'1'});\r\n");
      out.write("\t\t\t\t\t\t    \t   combo.reload();\r\n");
      out.write("\t\t\t\t\t\t       }\r\n");
      out.write("\t\t\t\t\t    \t    */\r\n");
      out.write("\t\t\t\t\t    \t   if(combo.otherConfig.name==\"modelname\"){\r\n");
      out.write("\t\t\t\t\t    \t\t   //增加租赁物明细中如果车辆分类选择挂车规格型号不需要校验\r\n");
      out.write("\t\t\t\t\t\t    \t   if(equipclassValue==\"equip_class_2\"){\r\n");
      out.write("\t\t\t\t\t\t    \t\t   combo.otherAttributes=\"\";\r\n");
      out.write("\t\t\t\t\t    \t\t       combo.setParams({equipclass:equipclassValue});\r\n");
      out.write("\t\t\t\t\t\t    \t       combo.reload();\r\n");
      out.write("\t\t\t\t\t\t    \t   }else{\r\n");
      out.write("\t\t\t\t\t\t    \t\t   combo.setParams({equipclass:equipclassValue});\r\n");
      out.write("\t\t\t\t\t\t    \t\t   combo.otherAttributes='require=\"true\" label=\"规格型号\"';\r\n");
      out.write("\t\t\t\t\t\t\t    \t   combo.reload(\"\");\r\n");
      out.write("\t\t\t\t\t\t    \t   }\r\n");
      out.write("\t\t\t\t\t\t    \t   break;\r\n");
      out.write("\t\t\t\t\t\t    \t}\r\n");
      out.write("\t\t\t\t\t\t    \t//项目立项是不需要验证 车架号‘和’合同小号\r\n");
      out.write("\t\t\t\t\t\t\t\t//2013-11-29 14:44 当车辆类型为挂车时 ’车架号‘和’合同小号‘ 不验证  equip_class_2（挂车）\r\n");
      out.write("\t\t\t\t\t\t\t\t/*if(equipclassValue==\"equip_class_2\"){\r\n");
      out.write("\t\t\t\t\t\t\t\t\t $(\"#id_equipcontractnum\").attr(\"require\",\"false\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t $(\"#id_chassisnum\").attr(\"require\",\"false\");\r\n");
      out.write("\t\t\t\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t\t\t     $(\"#id_equipcontractnum\").attr(\"require\",\"true\").attr(\"label\",\"车辆合同小号\");\r\n");
      out.write("\t\t\t\t\t\t\t\t\t $(\"#id_chassisnum\").attr(\"require\",\"true\").attr(\"label\",\"车架号\");\r\n");
      out.write("\t\t\t\t\t\t\t\t}*/\r\n");
      out.write("\t\t\t\t\t\t   }\r\n");
      out.write("\t       \t\t\t   }\r\n");
      out.write("\t\t   }},\r\n");
      out.write("\t\t   {name:'equipclass', header:'车辆分类id',hidden:true},\r\n");
      out.write("\t\t   //Edit by jason 2013-11-25,应甲方要求将车辆类型及型号改成二级分类\r\n");
      out.write("/* \t\t   {name:'equiptypename', header:'车辆类别',type:'combobox',nullable:false,hiddenName:'equiptype',\r\n");
      out.write("\t\t\t    config:{\r\n");
      out.write("\t\t\t    \t   //id:'id_combobox_equiptypename',\r\n");
      out.write("\t\t\t\t       width:165,\r\n");
      out.write("\t\t\t\t       xmlFileName:'\\\\eleasing\\\\workflow\\\\proj_approval\\\\equipTypeSelect.xml',\r\n");
      out.write("\t\t\t\t       loadMode:'ajax',\r\n");
      out.write("\t\t\t\t       readOnly:false,\r\n");
      out.write("\t\t\t\t       isAjaxLenovo:true,\r\n");
      out.write("\t\t\t\t       displayField:'name',\r\n");
      out.write("\t\t\t\t       valueField:'code',\r\n");
      out.write("\t\t\t\t       isForceModify:true,\r\n");
      out.write("\t\t\t\t       params:{\r\n");
      out.write("\t\t\t   \t\t\t\t//equipclass:'1'\r\n");
      out.write("\t\t   \t\t\t   },\r\n");
      out.write("\t\t   \t\t\t   otherConfig:{\r\n");
      out.write("\t\t\t\t\t\t\t  name:'equiptypename',\r\n");
      out.write("\t\t\t\t\t\t\t  hiddenName:'equiptype'\r\n");
      out.write("\t\t   \t\t\t   },\r\n");
      out.write("\t\t   \t\t\t   onSelected:function(combo,rowData,me,columnConfig){\r\n");
      out.write("\t    \t   \t\t\t   var equipclassValue;\r\n");
      out.write("\t    \t   \t\t\t   var equiptypeValue  = combo.getValue();\r\n");
      out.write("\t\t\t\t    \t   for(var i=0;i<me.comboboxs.length;i++){\r\n");
      out.write("\t\t\t\t\t    \t   var combo =me.comboboxs[i];\r\n");
      out.write("\t\t\t\t\t    \t   if(combo.otherConfig.name==\"equipclassname\"){\r\n");
      out.write("\t\t\t\t\t    \t\t   equipclassValue=combo.getValue();\r\n");
      out.write("\t\t\t\t\t\t    \t   break;\r\n");
      out.write("\t\t\t\t\t\t    \t}\r\n");
      out.write("\t\t\t\t\t\t   }\r\n");
      out.write("\t\t\t\t\t\t   if(equipclassValue==\"\"){\r\n");
      out.write("\t\t\t\t\t\t\t   alert(\"请先选择车辆分类\");\r\n");
      out.write("\t\t\t\t\t\t   }\r\n");
      out.write("\t\t\t\t\t\t   if(equiptypeValue==\"\"){\r\n");
      out.write("\t\t\t\t\t\t\t   alert(\"请先选择车辆类别\");\r\n");
      out.write("\t\t\t\t\t\t   }\r\n");
      out.write("\t\t\t\t\t\t   for(var i=0;i<me.comboboxs.length;i++){\r\n");
      out.write("\t\t\t\t\t    \t   var combo =me.comboboxs[i];\r\n");
      out.write("\t\t\t\t\t    \t   if(combo.otherConfig.name==\"modelname\"){\r\n");
      out.write("\t\t\t\t\t    \t\t   combo.setParams({equipclass:equipclassValue,equiptype:equiptypeValue});\r\n");
      out.write("\t\t\t\t\t\t    \t   combo.reload();\r\n");
      out.write("\t\t\t\t\t\t    \t   break;\r\n");
      out.write("\t\t\t\t\t\t    \t}\r\n");
      out.write("\t\t\t\t\t\t   }\r\n");
      out.write("\t       \t\t\t   }\r\n");
      out.write("\t\t   }},\r\n");
      out.write("\t\t   {name:'equiptype', header:'车辆型号id',hidden:true}, */\r\n");
      out.write("\t\t   {name:'modelname', header:'规格型号',type:'combobox',nullable:true,hiddenName:'model',\r\n");
      out.write("\t\t\t    config:{\r\n");
      out.write("\t\t\t\t       width:165,\r\n");
      out.write("\t\t\t\t       xmlFileName:'\\\\eleasing\\\\workflow\\\\proj_approval\\\\equipModelSelect.xml',\r\n");
      out.write("\t\t\t\t       loadMode:'ajax',\r\n");
      out.write("\t\t\t\t       readOnly:false,\r\n");
      out.write("\t\t\t\t       isAjaxLenovo:true,\r\n");
      out.write("\t\t\t\t       displayField:'name',\r\n");
      out.write("\t\t\t\t       valueField:'code',\r\n");
      out.write("\t\t\t\t       isForceModify:true,\r\n");
      out.write("\t\t\t\t       otherConfig:{\r\n");
      out.write("\t\t\t\t\t\t\t  name:'modelname',\r\n");
      out.write("\t\t\t\t\t\t\t  hiddenName:'model'\r\n");
      out.write("\t\t   \t\t\t   },\r\n");
      out.write("\t\t\t\t       params:{\r\n");
      out.write("\t\t\t   \t\t\t\t//equipclass:'1',\r\n");
      out.write("\t\t\t   \t\t\t\t//equiptype:'1'\r\n");
      out.write("\t\t   \t\t\t   }\r\n");
      out.write("\t\t   }},\r\n");
      out.write("\t\t   {name:'model',  header:'规格型号',hidden:true},\r\n");
      out.write("\t\t   {name:'equipcontractnum',  header:'车辆合同小号',otherAttributes:'maxB=\"100\" id=\"id_equipcontractnum\"'},\r\n");
      out.write("\t\t   {name:'chassisnum',  header:'车架号',otherAttributes:'maxB=\"100\" id=\"id_chassisnum\"'},\r\n");
      out.write("\t\t   {name:'garagedate',  header:'入库时间',type:'date'},\r\n");
      out.write("\t\t   {name:'saledate',  header:'已售时间',type:'date'},\r\n");
      out.write("\t\t   {name:'equipnum',  header:'数量',type:'number',hidden:true,defaultValue:1,otherAttributes:'id=\"id_equipnum\" onkeyup=\"AdjustTotal()\"'},\r\n");
      out.write("\t\t   {name:'saleprice',  header:'销售价',type:'double',nullable:false,otherAttributes:'id=\"id_saleprice\" onkeyup=\"AdjustTotal()\" onkeyup=\"AdjustMoney()\"'},\r\n");
      out.write("\t\t   {name:'purchaseprice',  header:'采购价',type:'double',nullable:false,otherAttributes:'id=\"id_purchaseprice\" onkeyup=\"AdjustMoney()\"'}, \r\n");
      out.write("\t\t   {name:'differential_swap',  header:'差额[销售价-采购价]',type:'double',nullable:false,otherAttributes:'id=\"id_differential_swap\"',readOnly:true,width:160},\r\n");
      out.write("\t\t   {name:'purchasetax',  header:'购置税',type:'double',hidden:true,defaultValue:'0',otherAttributes:'id=\"id_purchasetax\" onkeyup=\"AdjustTotal()\"'},\r\n");
      out.write("\t\t   {name:'insuremoney',  header:'保费',type:'double',hidden:true,defaultValue:'0',otherAttributes:'id=\"id_insuremoney\" onkeyup=\"AdjustTotal()\"'},\r\n");
      out.write("\t\t   {name:'leasingmoney',  header:'其他融资额',type:'double',hidden:true,defaultValue:'0',otherAttributes:'id=\"id_leasingmoney\" onkeyup=\"AdjustTotal()\"'},\r\n");
      out.write("\t       {name:'devicetypename',  header:'设备类型',type:'combobox',defaultRawValue:'',nullable:false,hiddenName:'devicetype',\r\n");
      out.write("\t\t\t    config:{\r\n");
      out.write("\t\t\t       width:165,\r\n");
      out.write("\t\t\t       xmlFileName:'\\\\combos\\\\comboDict.xml',\r\n");
      out.write("\t\t\t       loadMode:'ajax',\r\n");
      out.write("\t\t\t       readOnly:true,\r\n");
      out.write("\t\t\t       displayField:'name',\r\n");
      out.write("\t\t\t       valueField:'code',\r\n");
      out.write("\t\t\t       params:{\r\n");
      out.write("\t\t\t          pid:'device_type'\r\n");
      out.write("\t\t\t       } \r\n");
      out.write("\t\t\t}},\r\n");
      out.write("\t\t   {name:'devicetype', header:'设备类型id',hidden:true},\r\n");
      out.write("\t       {name:'nowtotal',  header:'总计',nullable:false,otherAttributes:'id=\"id_nowtotal\"',readOnly:true,width:130,type:'double'},\r\n");
      out.write("\t       {name:'manufacturername',  header:'制造商',type:'combobox',nullable:false,hiddenName:'manufacturer',\r\n");
      out.write("\t\t\t    config:{\r\n");
      out.write("\t\t\t       width:165,\r\n");
      out.write("\t\t\t       xmlFileName : '\\\\eleasing\\\\workflow\\\\public\\\\SimpleCustSelectForManufacturer.xml',\r\n");
      out.write("\t\t\t       loadMode:'ajax',\r\n");
      out.write("\t\t\t       readOnly:false,\r\n");
      out.write("\t\t\t       isAjaxLenovo:true,\r\n");
      out.write("\t\t\t       displayField:'name',\r\n");
      out.write("\t\t\t       valueField:'id',\r\n");
      out.write("\t\t\t       isForceModify:true,\r\n");
      out.write("\t\t\t       params:{\r\n");
      out.write("\t\t\t    \t    cust_class_m:\"1\",\r\n");
      out.write("\t\t\t   \t\t\tcust_class1:'CUST_INFO_COMPANY',\r\n");
      out.write("\t\t\t   \t\t\tcust_class2:'CUST_INFO_PERSON',\r\n");
      out.write("\t\t\t  \t\t\tcust_type:'cust_type.manufacturer',\r\n");
      out.write("\t\t\t  \t\t\tcust_dealer_id:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope['currentDealerCustInfoId']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\"\r\n");
      out.write("\t\t\t       } \r\n");
      out.write("  \t\t\t}},\r\n");
      out.write("\t\t\r\n");
      out.write("  \t\t {header:'是否挂靠',name:'isaffiliatedname',type:'combobox',hiddenName:'isaffiliated',otherAttributes:'id=\"id_isaffiliated\"',\r\n");
      out.write("\t            config:{\r\n");
      out.write("  \t\t\t\twidth:165,\r\n");
      out.write("\t\t\t\tisNewLine:true,\r\n");
      out.write("\t\t\t\tcolSpan:3, \r\n");
      out.write("\t\t\t\tloadMode:'local',\r\n");
      out.write("\t\t\t\tdatas:[{title:'是',name:'0'},{title:'否',name:'1'}],\r\n");
      out.write("\t            displayField:'title',\r\n");
      out.write("\t            valueField:'name',\r\n");
      out.write("\t            defaultValue:1,\r\n");
      out.write("\t            value:'1',\r\n");
      out.write("\t            \r\n");
      out.write("\t            onSelected:function(combo,rowData,me,columnConfig){\r\n");
      out.write(" \t   \t\t\t   var isAffiliated;\r\n");
      out.write(" \t   \t\t\t   var isAffiliated  = combo.getValue();\r\n");
      out.write("\t\t\t\t   if(isAffiliated=='1'){\r\n");
      out.write("\t\t\t\t\t\t$(\"#id_affiliatedinfo\").hide();\r\n");
      out.write("\t\t\t\t\t\t$(\"#id_affiliatedinfo\").parent().parent().hide();\r\n");
      out.write("\t\t\t\t\t\t$(\"#id_affiliatedinfo\").attr(\"require\",\"false\").attr(\"sytle\",\"display:none\");\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t   }else{\r\n");
      out.write("\t\t\t\t\t    $(\"#id_affiliatedinfo\").show();\r\n");
      out.write("\t\t\t\t\t\t$(\"#id_affiliatedinfo\").parent().parent().show();\r\n");
      out.write("\t\t\t\t\t\t$(\"#id_affiliatedinfo\").attr(\"require\",\"true\").attr(\"label\",\"挂靠信息\").attr(\"style\",\"display:inline\");\r\n");
      out.write("\t\t\t\t   }\r\n");
      out.write("  \t\t\t\t},\r\n");
      out.write("\t  \t\t\totherConfig:{name:'isaffiliated'}\r\n");
      out.write("\t            }\r\n");
      out.write("\t           \r\n");
      out.write("            },\r\n");
      out.write("           {name:'isaffiliated', header:'是否挂靠id',hidden:true},\r\n");
      out.write("  \t\t   {name:'affiliatedinfo', header:\"挂靠单位及法人信息\",type:'textarea',otherAttributes:'maxB=\"2000\" id=\"id_affiliatedinfo\" onblur=\"AdjustAffiliatedinfo()\" '},\r\n");
      out.write("  \t\t   {name:'manufacturer', header:'制造商id',hidden:true},    \r\n");
      out.write("\t       {name:'equipdeliveryplace',  header:'交付地点',nullable:true,otherAttributes:'maxB=\"2000\"'},\r\n");
      out.write("\t       {name:'equipdeliverydate',  header:'预计交付时间',type:'date',nullable:true},\r\n");
      out.write("\t       {name:'cenote', header:'备注',type:'textarea',otherAttributes:'maxB=\"2000\"'}\r\n");
      out.write("\t     ]\r\n");
      out.write("\t });\r\n");
      out.write("\t    \r\n");
      out.write("});\r\n");
      out.write("\t\t\r\n");
      out.write("function AdjustAffiliatedinfo()\r\n");
      out.write("{\r\n");
      out.write("\t var id_affiliatedinfo = jQuery(\"#id_affiliatedinfo\").val();\r\n");
      out.write("\t id_affiliatedinfo=id_affiliatedinfo.replace(/\\n/g,'');\r\n");
      out.write("\t jQuery(\"#id_affiliatedinfo\").val(id_affiliatedinfo.trim());\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
